---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-file-access-tracing-filters.html'
summary: 'Retrieve information about security trace filter entries'
---

= Retrieve information about security trace filter entries

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/file-access-tracing/filters`#

*Introduced In:* 9.8

Retrieves information about security trace filter entries.

== Related ONTAP commands

* `vserver security trace filter show`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|windows_user
|string
|query
|False
a|Filter by windows_user


|protocol
|string
|query
|False
a|Filter by protocol


|enabled
|boolean
|query
|False
a|Filter by enabled


|index
|integer
|query
|False
a|Filter by index


|unix_user
|string
|query
|False
a|Filter by unix_user


|client_ip
|string
|query
|False
a|Filter by client_ip


|trace_allowed_ops
|boolean
|query
|False
a|Filter by trace_allowed_ops


|path
|string
|query
|False
a|Filter by path


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#collection_links[collection_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#file_access_filter[file_access_filter]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "records": [
    {
      "client_ip": "10.140.68.143",
      "index": "1",
      "path": "/dir1/dir2",
      "protocol": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "unix_user": "root",
      "windows_user": "cifs1/administrator"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#collection_links]
[.api-collapsible-fifth-title]
collection_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#svm_reference]
[.api-collapsible-fifth-title]
svm_reference

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#file_access_filter]
[.api-collapsible-fifth-title]
file_access_filter

ONTAP allows creation of filters for file access tracing for both CIFS and NFS. These filters have protocols, path, username  and client IP based on which file access operations are logged.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|client_ip
|string
a|Specifies the IP address from which the client accesses the file or directory.


|enabled
|boolean
a|Specifies whether to enable or disable the filter. Filters are enabled by default and are deleted after 60 mins.


|index
|integer
a|Position of the file access tracing filter.


|path
|string
a|Specifies the path for which permission tracing can be applied. The value can be complete path from root of CIFS share or root of volume for NFS.


|protocol
|string
a|Specifies the protocol for which permission trace is required.


|svm
|link:#svm_reference[svm_reference]
a|SVM, applies only to SVM-scoped objects.


|trace_allowed_ops
|boolean
a|Specifies if the filter can trace file access denied and allowed events. The value of trace-allow is false by default, and it traces access denied events. The value is set to true for tracing access allowed events.


|unix_user
|string
a|Specifies the UNIX username whose access requests you want to trace. The filter would match only if the request is received with this user.


|windows_user
|string
a|Specifies the Windows username whose access requests you want to trace. The filter would match only if the request is received with this user.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
