---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster.html'
summary: 'Retrieve the cluster configuration'
---

= Retrieve the cluster configuration

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster`#

*Introduced In:* 9.6

Retrieves the cluster configuration.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.


|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|certificate
|link:#certificate[certificate]
a|Certificate used by cluster and node management interfaces for TLS connection requests.


|contact
|string
a|

|dns_domains
|array[string]
a|A list of DNS domains.
Domain names have the following requirements:

* The name must contain only the following characters: A through Z,
a through z, 0 through 9, ".", "-" or "_".
* The first character of each label, delimited by ".", must be one
of the following characters: A through Z or a through z or 0
through 9.
* The last character of each label, delimited by ".", must be one of
the following characters: A through Z, a through z, or 0 through 9.
* The top level domain must contain only the following characters: A
through Z, a through z.
* The system reserves the following names:"all", "local", and "localhost".


|location
|string
a|

|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|metric
|link:#metric[metric]
a|Performance numbers, such as IOPS latency and throughput.


|name
|string
a|

|name_servers
|array[string]
a|The list of IP addresses of the DNS servers. Addresses can be either
IPv4 or IPv6 addresses.


|ntp_servers
|array[string]
a|Host name, IPv4 address, or IPv6 address for the external NTP time servers.


|san_optimized
|boolean
a|Specifies if this cluster is an All SAN Array.


|statistics
|link:#statistics[statistics]
a|These are raw performance numbers, such as IOPS latency and throughput. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster.


|timezone
|link:#timezone[timezone]
a|Provides the cluster-wide time zone information that localizes time found on messages displayed on each node's:

* console messages;
* logging to internal ONTAP log files; and
* localized REST API full ISO-8601 date, time, and time zone format information.
Machine-to-machine interfaces, such as file access protocols (NFS, CIFS), block access protocols (SAN), and other protocols
such as Manage ONTAP (ONTAPI), use second or subsecond time values that are based on world time or UTC.
* Introduced in: 9.7


|uuid
|string
a|

|version
|link:#version[version]
a|This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "certificate": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "cert1",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "contact": "support@company.com",
  "dns_domains": [
    "example.com",
    "example2.example3.com"
  ],
  "location": "building 1",
  "management_interfaces": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "ip": {
        "address": "10.10.10.7"
      },
      "name": "lif1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "metric": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "duration": "PT15S",
    "iops": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "latency": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "status": "ok",
    "throughput": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "timestamp": "2017-01-25T11:20:13Z"
  },
  "name": "cluster1",
  "name_servers": [
    "10.224.65.20",
    "2001:db08:a0b:12f0::1"
  ],
  "ntp_servers": [
    "time.nist.gov",
    "10.98.19.20",
    "2610:20:6F15:15::27"
  ],
  "statistics": {
    "iops_raw": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "latency_raw": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "status": "ok",
    "throughput_raw": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "timestamp": "2017-01-25T11:20:13Z"
  },
  "timezone": {
    "name": "America/New_York"
  },
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
  "version": {
    "full": "NetApp Release 9.4.0: Sun Nov 05 18:20:57 UTC 2017",
    "generation": "9",
    "major": "4",
    "minor": "0"
  }
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Certificate used by cluster and node management interfaces for TLS connection requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Certificate name


|uuid
|string
a|Certificate UUID


|===


[#configuration_backup]
[.api-collapsible-fifth-title]
configuration_backup

[cols=3*,options=header]
|===
|Name
|Type
|Description

|password
|string
a|

|url
|string
a|An external backup location for the cluster configuration. This is mostly required for single node clusters where node and cluster configuration backups cannot be copied to other nodes in the cluster.


|username
|string
a|

|validate_certificate
|boolean
a|Use this parameter with the value "true" to validate the digital certificate of the remote server. Digital certificate validation is available only when the HTTPS protocol is used in the URL; it is disabled by default.


|===


[#license]
[.api-collapsible-fifth-title]
license

License keys or NLF contents.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|keys
|array[string]
a|

|===


[#ip]
[.api-collapsible-fifth-title]
ip

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|gateway
|string
a|The IPv4 or IPv6 address of the default router.


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always netmask length.


|===


[#management_interface]
[.api-collapsible-fifth-title]
management_interface

The management interface of the cluster. The subnet mask and gateway for this interface are used for the node management interfaces provided in the node configuration.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|Object to setup an interface along with its default router.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|===


[#management_interfaces]
[.api-collapsible-fifth-title]
management_interfaces

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#iops]
[.api-collapsible-fifth-title]
iops

The rate of I/O operations observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#latency]
[.api-collapsible-fifth-title]
latency

The round trip latency in microseconds observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

Performance numbers, such as IOPS latency and throughput.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#node_setup_ip]
[.api-collapsible-fifth-title]
node_setup_ip

The IP configuration for cluster setup.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|===


[#cluster_interface]
[.api-collapsible-fifth-title]
cluster_interface

The cluster network IP address of the node to be added.

[#cluster_interfaces]
[.api-collapsible-fifth-title]
cluster_interfaces

Network interface


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#cpu]
[.api-collapsible-fifth-title]
cpu

CPU information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of CPUs on the node.


|firmware_release
|string
a|Firmware release number. Defined by the CPU manufacturer.


|processor
|string
a|CPU type on the node.


|===


[#message]
[.api-collapsible-fifth-title]
message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Error code describing the current condition of chassis fans.


|message
|string
a|Message describing the current condition of chassis fans. It is only of use when `failed_fan.count` is not zero.


|===


[#failed_fan]
[.api-collapsible-fifth-title]
failed_fan

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Specifies a count of the number of chassis fans that are not operating within the recommended RPM range.


|message
|link:#message[message]
a|

|===


[#message]
[.api-collapsible-fifth-title]
message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Error code describing the current condition of power supply.


|message
|string
a|Message describing the state of any power supplies that are currently degraded. It is only of use when `failed_power_supply.count` is not zero.


|===


[#failed_power_supply]
[.api-collapsible-fifth-title]
failed_power_supply

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of failed power supply units.


|message
|link:#message[message]
a|

|===


[#flash_cache]
[.api-collapsible-fifth-title]
flash_cache

[cols=3*,options=header]
|===
|Name
|Type
|Description

|capacity
|integer
a|Size in bytes


|device_id
|integer
a|

|firmware_file
|string
a|

|firmware_version
|string
a|

|hardware_revision
|string
a|

|model
|string
a|

|part_number
|string
a|

|serial_number
|string
a|

|slot
|string
a|

|state
|string
a|

|===


[#frus]
[.api-collapsible-fifth-title]
frus

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|string
a|

|state
|string
a|

|type
|string
a|

|===


[#controller]
[.api-collapsible-fifth-title]
controller

Controller information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|board
|string
a|Type of the system board. This is defined by vendor.


|cpu
|link:#cpu[cpu]
a|CPU information.


|failed_fan
|link:#failed_fan[failed_fan]
a|

|failed_power_supply
|link:#failed_power_supply[failed_power_supply]
a|

|flash_cache
|array[link:#flash_cache[flash_cache]]
a|A list of Flash-Cache devices. Only returned when requested by name.


|frus
|array[link:#frus[frus]]
a|List of FRUs on the node. Only returned when requested by name.


|memory_size
|integer
a|Memory available on the node, in bytes.


|over_temperature
|string
a|Specifies whether the hardware is currently operating outside of its recommended temperature range. The hardware shuts down if the temperature exceeds critical thresholds.


|===


[#failure]
[.api-collapsible-fifth-title]
failure

Indicates the failure code and message.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Message code


|message
|string
a|Detailed message based on the state.


|===


[#giveback]
[.api-collapsible-fifth-title]
giveback

Represents the state of the node that is giving storage back to its HA partner.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|failure
|link:#failure[failure]
a|Indicates the failure code and message.


|state
|string
a|

|===


[#partners]
[.api-collapsible-fifth-title]
partners

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#ports]
[.api-collapsible-fifth-title]
ports

[cols=3*,options=header]
|===
|Name
|Type
|Description

|number
|integer
a|HA port number


|state
|string
a|HA port state:

* _down_ - Logical HA link is down.
* _initialized_ - Logical HA link is initialized. The physical link is up, but the subnet manager hasn't started to configure the port.
* _armed_ - Logical HA link is armed. The physical link is up and the subnet manager started but did not yet complete configuring the port.
* _active_ - Logical HA link is active.
* _reserved_ - Logical HA link is active, but the physical link is down.


|===


[#takeover]
[.api-collapsible-fifth-title]
takeover

This represents the state of the node that is taking over storage from its HA partner.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|failure
|link:#failure[failure]
a|Indicates the failure code and message.


|state
|string
a|

|===


[#ha]
[.api-collapsible-fifth-title]
ha

[cols=3*,options=header]
|===
|Name
|Type
|Description

|auto_giveback
|boolean
a|Specifies whether giveback is automatically initiated when the node that owns the storage is ready.


|enabled
|boolean
a|Specifies whether or not storage failover is enabled.


|giveback
|link:#giveback[giveback]
a|Represents the state of the node that is giving storage back to its HA partner.


|partners
|array[link:#partners[partners]]
a|Nodes in this node's High Availability (HA) group.


|ports
|array[link:#ports[ports]]
a|

|takeover
|link:#takeover[takeover]
a|This represents the state of the node that is taking over storage from its HA partner.


|===


[#management_interface]
[.api-collapsible-fifth-title]
management_interface

The management interface of the node to be added. The subnet mask is set based on the management interface of the cluster or the managment interfaces of other nodes.

[#management_interfaces]
[.api-collapsible-fifth-title]
management_interfaces

Network interface


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

CPU performance for the nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|processor_utilization
|integer
a|Average CPU Utilization for the node


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#ports]
[.api-collapsible-fifth-title]
ports

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#metrocluster]
[.api-collapsible-fifth-title]
metrocluster

Metrocluster


[cols=3*,options=header]
|===
|Name
|Type
|Description

|custom_vlan_capable
|boolean
a|Indicates whether the MetroCluster over IP platform supports custom VLAN IDs.


|ports
|array[link:#ports[ports]]
a|MetroCluster over IP ports.


|type
|string
a|The Metrocluster configuration type


|===


[#nvram]
[.api-collapsible-fifth-title]
nvram

[cols=3*,options=header]
|===
|Name
|Type
|Description

|battery_state
|string
a|Specifies status of the NVRAM battery. Possible values:

* _battery_ok_
* _battery_partially_discharged_
* _battery_fully_discharged_
* _battery_not_present_
* _battery_near_end_of_life_
* _battery_at_end_of_life_
* _battery_unknown_
* _battery_over_charged_
* _battery_fully_charged_


|id
|integer
a|Vendor specific NVRAM ID of the node.


|===


[#ipv4_interface]
[.api-collapsible-fifth-title]
ipv4_interface

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|gateway
|string
a|The IPv4 or IPv6 address of the default router.


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always netmask length.


|===


[#ipv6_interface]
[.api-collapsible-fifth-title]
ipv6_interface

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv6 address


|gateway
|string
a|The IPv6 address of the default router.


|netmask
|integer
a|The IPv6 netmask/prefix length. The default value is 64 with a valid range of 1 to 127.


|===


[#service_processor]
[.api-collapsible-fifth-title]
service_processor

[cols=3*,options=header]
|===
|Name
|Type
|Description

|dhcp_enabled
|boolean
a|Set to "true" to use DHCP to configure an IPv4 interface.


|firmware_version
|string
a|The version of firmware installed.


|ipv4_interface
|link:#ipv4_interface[ipv4_interface]
a|Object to setup an interface along with its default router.


|ipv6_interface
|link:#ipv6_interface[ipv6_interface]
a|Object to setup an interface along with its default router.


|link_status
|string
a|

|mac_address
|string
a|

|state
|string
a|

|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

Raw CPU performance for the nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|processor_utilization_base
|integer
a|Base counter for CPU Utilization.


|processor_utilization_raw
|integer
a|Raw CPU Utilization for the node. This should be divided by the processor_utilization_base to calculate the percentage CPU utilization for the node.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#version]
[.api-collapsible-fifth-title]
version

This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|full
|string
a|The full cluster version string.


|generation
|integer
a|The generation portion of the version.


|major
|integer
a|The major portion of the version.


|minor
|integer
a|The minor portion of the version.


|===


[#vm]
[.api-collapsible-fifth-title]
vm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|provider_type
|string
a|Cloud provider where the VM is hosted.


|===


[#nodes]
[.api-collapsible-fifth-title]
nodes

Complete node information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|cluster_interfaces
|array[link:#cluster_interfaces[cluster_interfaces]]
a|

|controller
|link:#controller[controller]
a|Controller information


|date
|string
a|The current or "wall clock" time of the node in ISO-8601 date, time, and time zone format.
The ISO-8601 date and time are localized based on the ONTAP cluster's timezone setting.

* example: 2019-04-17T11:49:26-04:00
* format: date-time
* readOnly: 1


|ha
|link:#ha[ha]
a|

|location
|string
a|

|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|membership
|string
a|Possible values:

* _available_ - A node is detected on the internal cluster network and can be added to the cluster.  Nodes that have a membership of "available" are not returned when a GET request is called when the cluster exists. Provide a query on the "membership" property for _available_ to scan for nodes on the cluster network. Nodes that have a membership of "available" are returned automatically before a cluster is created.
* _joining_ - Joining nodes are in the process of being added to the cluster. The node might be progressing through the steps to become a member or might have failed. The job to add the node or create the cluster provides details on the current progress of the node.
* _member_ - Nodes that are members have successfully joined the cluster.


|metric
|link:#metric[metric]
a|CPU performance for the nodes.


|metrocluster
|link:#metrocluster[metrocluster]
a|Metrocluster


|model
|string
a|

|name
|string
a|

|nvram
|link:#nvram[nvram]
a|

|owner
|string
a|Owner of the node.


|serial_number
|string
a|

|service_processor
|link:#service_processor[service_processor]
a|

|state
|string
a|State of the node:

* _up_ - Node is up and operational.
* _booting_ - Node is booting up.
* _down_ - Node has stopped or is dumping core.
* _taken_over_ - Node has been taken over by its HA partner and is not yet waiting for giveback.
* _waiting_for_giveback_ - Node has been taken over by its HA partner and is waiting for the HA partner to giveback disks.
* _degraded_ - Node has one or more critical services offline.
* _unknown_ - Node or its HA partner cannot be contacted and there is no information on the node's state.


|statistics
|link:#statistics[statistics]
a|Raw CPU performance for the nodes.


|storage_configuration
|string
a|The storage configuration in the system. Possible values:

* _mixed_path_
* _single_path_
* _multi_path_
* _quad_path_
* _mixed_path_ha_
* _single_path_ha_
* _multi_path_ha_
* _quad_path_ha_
* _unknown_


|system_id
|string
a|

|system_machine_type
|string
a|OEM system machine type.


|uptime
|integer
a|The total time, in seconds, that the node has been up.


|uuid
|string
a|

|vendor_serial_number
|string
a|OEM vendor serial number.


|version
|link:#version[version]
a|This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


|vm
|link:#vm[vm]
a|

|===


[#iops_raw]
[.api-collapsible-fifth-title]
iops_raw

The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#latency_raw]
[.api-collapsible-fifth-title]
latency_raw

The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#throughput_raw]
[.api-collapsible-fifth-title]
throughput_raw

Throughput bytes observed at the storage object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

These are raw performance numbers, such as IOPS latency and throughput. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the storage object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#timezone]
[.api-collapsible-fifth-title]
timezone

Provides the cluster-wide time zone information that localizes time found on messages displayed on each node's:

* console messages;
* logging to internal ONTAP log files; and
* localized REST API full ISO-8601 date, time, and time zone format information.
Machine-to-machine interfaces, such as file access protocols (NFS, CIFS), block access protocols (SAN), and other protocols
such as Manage ONTAP (ONTAPI), use second or subsecond time values that are based on world time or UTC.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The ONTAP time zone name or identification in either IANA time zone format "Area/Location", or an ONTAP traditional time zone.

The initial first node in cluster setting for time zone is "Etc/UTC".
"Etc/UTC" is the IANA timezone "Area/Location" specifier for
Coordinated Universal Time (UTC), which is an offset of 0.

===== IANA time zone format

The IANA time zone, formatted as "Area/Location", is based on geographic areas that have had the same time zone offset for many years.

"Location" represents a compound name using additional forward slashes.

An example of the "Area/Location" time zone is "America/New_York" and represents most of the United States Eastern Time Zone.
Examples of "Area/Location" with "Location" as a compound name are "America/Argentina/Buenos_Aires" and "America/Indiana/Indianapolis".

===== ONTAP traditional time zone

Examples of the traditional time zones are "EST5EDT" for the United States Eastern Time Zone and "CET" for Central European Time Zone.

* example: America/New_York
* Introduced in: 9.7


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
