---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-nfs-services.html'
summary: 'Retrieve NFS configuration for SVMs'
---

= Retrieve NFS configuration for SVMs

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/nfs/services`#

*Introduced In:* 9.6

Retrieves the NFS configuration of SVMs.

== Expensive properties

There is an added cost to retrieving values for these properties. They are not included by default in GET results and must be explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.

* `statistics.+*+`
* `metric.+*+`

== Related ONTAP commands

* `vserver nfs show`
* `vserver nfs status`

== Learn more

* link:manage_nfs_services.html[DOC /protocols/nfs/services]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|positive_cached_credential_ttl
|integer
|query
|False
a|Filter by positive_cached_credential_ttl

* Introduced in: 9.8


|transport.tcp_enabled
|boolean
|query
|False
a|Filter by transport.tcp_enabled


|transport.udp_enabled
|boolean
|query
|False
a|Filter by transport.udp_enabled


|enabled
|boolean
|query
|False
a|Filter by enabled


|statistics.v4.timestamp
|string
|query
|False
a|Filter by statistics.v4.timestamp

* Introduced in: 9.8


|statistics.v4.iops_raw.total
|integer
|query
|False
a|Filter by statistics.v4.iops_raw.total

* Introduced in: 9.8


|statistics.v4.iops_raw.other
|integer
|query
|False
a|Filter by statistics.v4.iops_raw.other

* Introduced in: 9.8


|statistics.v4.iops_raw.read
|integer
|query
|False
a|Filter by statistics.v4.iops_raw.read

* Introduced in: 9.8


|statistics.v4.iops_raw.write
|integer
|query
|False
a|Filter by statistics.v4.iops_raw.write

* Introduced in: 9.8


|statistics.v4.latency_raw.total
|integer
|query
|False
a|Filter by statistics.v4.latency_raw.total

* Introduced in: 9.8


|statistics.v4.latency_raw.other
|integer
|query
|False
a|Filter by statistics.v4.latency_raw.other

* Introduced in: 9.8


|statistics.v4.latency_raw.read
|integer
|query
|False
a|Filter by statistics.v4.latency_raw.read

* Introduced in: 9.8


|statistics.v4.latency_raw.write
|integer
|query
|False
a|Filter by statistics.v4.latency_raw.write

* Introduced in: 9.8


|statistics.v4.status
|string
|query
|False
a|Filter by statistics.v4.status

* Introduced in: 9.8


|statistics.v4.throughput_raw.total
|integer
|query
|False
a|Filter by statistics.v4.throughput_raw.total

* Introduced in: 9.8


|statistics.v4.throughput_raw.read
|integer
|query
|False
a|Filter by statistics.v4.throughput_raw.read

* Introduced in: 9.8


|statistics.v4.throughput_raw.write
|integer
|query
|False
a|Filter by statistics.v4.throughput_raw.write

* Introduced in: 9.8


|statistics.v3.timestamp
|string
|query
|False
a|Filter by statistics.v3.timestamp

* Introduced in: 9.7


|statistics.v3.iops_raw.total
|integer
|query
|False
a|Filter by statistics.v3.iops_raw.total

* Introduced in: 9.7


|statistics.v3.iops_raw.other
|integer
|query
|False
a|Filter by statistics.v3.iops_raw.other

* Introduced in: 9.7


|statistics.v3.iops_raw.read
|integer
|query
|False
a|Filter by statistics.v3.iops_raw.read

* Introduced in: 9.7


|statistics.v3.iops_raw.write
|integer
|query
|False
a|Filter by statistics.v3.iops_raw.write

* Introduced in: 9.7


|statistics.v3.latency_raw.total
|integer
|query
|False
a|Filter by statistics.v3.latency_raw.total

* Introduced in: 9.7


|statistics.v3.latency_raw.other
|integer
|query
|False
a|Filter by statistics.v3.latency_raw.other

* Introduced in: 9.7


|statistics.v3.latency_raw.read
|integer
|query
|False
a|Filter by statistics.v3.latency_raw.read

* Introduced in: 9.7


|statistics.v3.latency_raw.write
|integer
|query
|False
a|Filter by statistics.v3.latency_raw.write

* Introduced in: 9.7


|statistics.v3.status
|string
|query
|False
a|Filter by statistics.v3.status

* Introduced in: 9.7


|statistics.v3.throughput_raw.total
|integer
|query
|False
a|Filter by statistics.v3.throughput_raw.total

* Introduced in: 9.7


|statistics.v3.throughput_raw.read
|integer
|query
|False
a|Filter by statistics.v3.throughput_raw.read

* Introduced in: 9.7


|statistics.v3.throughput_raw.write
|integer
|query
|False
a|Filter by statistics.v3.throughput_raw.write

* Introduced in: 9.7


|statistics.v41.timestamp
|string
|query
|False
a|Filter by statistics.v41.timestamp

* Introduced in: 9.8


|statistics.v41.iops_raw.total
|integer
|query
|False
a|Filter by statistics.v41.iops_raw.total

* Introduced in: 9.8


|statistics.v41.iops_raw.other
|integer
|query
|False
a|Filter by statistics.v41.iops_raw.other

* Introduced in: 9.8


|statistics.v41.iops_raw.read
|integer
|query
|False
a|Filter by statistics.v41.iops_raw.read

* Introduced in: 9.8


|statistics.v41.iops_raw.write
|integer
|query
|False
a|Filter by statistics.v41.iops_raw.write

* Introduced in: 9.8


|statistics.v41.latency_raw.total
|integer
|query
|False
a|Filter by statistics.v41.latency_raw.total

* Introduced in: 9.8


|statistics.v41.latency_raw.other
|integer
|query
|False
a|Filter by statistics.v41.latency_raw.other

* Introduced in: 9.8


|statistics.v41.latency_raw.read
|integer
|query
|False
a|Filter by statistics.v41.latency_raw.read

* Introduced in: 9.8


|statistics.v41.latency_raw.write
|integer
|query
|False
a|Filter by statistics.v41.latency_raw.write

* Introduced in: 9.8


|statistics.v41.status
|string
|query
|False
a|Filter by statistics.v41.status

* Introduced in: 9.8


|statistics.v41.throughput_raw.total
|integer
|query
|False
a|Filter by statistics.v41.throughput_raw.total

* Introduced in: 9.8


|statistics.v41.throughput_raw.read
|integer
|query
|False
a|Filter by statistics.v41.throughput_raw.read

* Introduced in: 9.8


|statistics.v41.throughput_raw.write
|integer
|query
|False
a|Filter by statistics.v41.throughput_raw.write

* Introduced in: 9.8


|protocol.v40_features.acl_enabled
|boolean
|query
|False
a|Filter by protocol.v40_features.acl_enabled


|protocol.v40_features.write_delegation_enabled
|boolean
|query
|False
a|Filter by protocol.v40_features.write_delegation_enabled


|protocol.v40_features.read_delegation_enabled
|boolean
|query
|False
a|Filter by protocol.v40_features.read_delegation_enabled


|protocol.v4_id_domain
|string
|query
|False
a|Filter by protocol.v4_id_domain


|protocol.v4_64bit_identifiers_enabled
|boolean
|query
|False
a|Filter by protocol.v4_64bit_identifiers_enabled

* Introduced in: 9.8


|protocol.v41_features.acl_enabled
|boolean
|query
|False
a|Filter by protocol.v41_features.acl_enabled


|protocol.v41_features.pnfs_enabled
|boolean
|query
|False
a|Filter by protocol.v41_features.pnfs_enabled


|protocol.v41_features.write_delegation_enabled
|boolean
|query
|False
a|Filter by protocol.v41_features.write_delegation_enabled


|protocol.v41_features.read_delegation_enabled
|boolean
|query
|False
a|Filter by protocol.v41_features.read_delegation_enabled


|protocol.v41_enabled
|boolean
|query
|False
a|Filter by protocol.v41_enabled


|protocol.v3_enabled
|boolean
|query
|False
a|Filter by protocol.v3_enabled


|protocol.v3_64bit_identifiers_enabled
|boolean
|query
|False
a|Filter by protocol.v3_64bit_identifiers_enabled

* Introduced in: 9.8


|protocol.v40_enabled
|boolean
|query
|False
a|Filter by protocol.v40_enabled


|auth_sys_extended_groups_enabled
|boolean
|query
|False
a|Filter by auth_sys_extended_groups_enabled

* Introduced in: 9.8


|showmount_enabled
|boolean
|query
|False
a|Filter by showmount_enabled

* Introduced in: 9.8


|state
|string
|query
|False
a|Filter by state


|metric.v41.timestamp
|string
|query
|False
a|Filter by metric.v41.timestamp

* Introduced in: 9.8


|metric.v41.throughput.total
|integer
|query
|False
a|Filter by metric.v41.throughput.total

* Introduced in: 9.8


|metric.v41.throughput.read
|integer
|query
|False
a|Filter by metric.v41.throughput.read

* Introduced in: 9.8


|metric.v41.throughput.write
|integer
|query
|False
a|Filter by metric.v41.throughput.write

* Introduced in: 9.8


|metric.v41.latency.total
|integer
|query
|False
a|Filter by metric.v41.latency.total

* Introduced in: 9.8


|metric.v41.latency.other
|integer
|query
|False
a|Filter by metric.v41.latency.other

* Introduced in: 9.8


|metric.v41.latency.read
|integer
|query
|False
a|Filter by metric.v41.latency.read

* Introduced in: 9.8


|metric.v41.latency.write
|integer
|query
|False
a|Filter by metric.v41.latency.write

* Introduced in: 9.8


|metric.v41.iops.total
|integer
|query
|False
a|Filter by metric.v41.iops.total

* Introduced in: 9.8


|metric.v41.iops.other
|integer
|query
|False
a|Filter by metric.v41.iops.other

* Introduced in: 9.8


|metric.v41.iops.read
|integer
|query
|False
a|Filter by metric.v41.iops.read

* Introduced in: 9.8


|metric.v41.iops.write
|integer
|query
|False
a|Filter by metric.v41.iops.write

* Introduced in: 9.8


|metric.v41.duration
|string
|query
|False
a|Filter by metric.v41.duration

* Introduced in: 9.8


|metric.v41.status
|string
|query
|False
a|Filter by metric.v41.status

* Introduced in: 9.8


|metric.v3.timestamp
|string
|query
|False
a|Filter by metric.v3.timestamp

* Introduced in: 9.7


|metric.v3.throughput.total
|integer
|query
|False
a|Filter by metric.v3.throughput.total

* Introduced in: 9.7


|metric.v3.throughput.read
|integer
|query
|False
a|Filter by metric.v3.throughput.read

* Introduced in: 9.7


|metric.v3.throughput.write
|integer
|query
|False
a|Filter by metric.v3.throughput.write

* Introduced in: 9.7


|metric.v3.latency.total
|integer
|query
|False
a|Filter by metric.v3.latency.total

* Introduced in: 9.7


|metric.v3.latency.other
|integer
|query
|False
a|Filter by metric.v3.latency.other

* Introduced in: 9.7


|metric.v3.latency.read
|integer
|query
|False
a|Filter by metric.v3.latency.read

* Introduced in: 9.7


|metric.v3.latency.write
|integer
|query
|False
a|Filter by metric.v3.latency.write

* Introduced in: 9.7


|metric.v3.iops.total
|integer
|query
|False
a|Filter by metric.v3.iops.total

* Introduced in: 9.7


|metric.v3.iops.other
|integer
|query
|False
a|Filter by metric.v3.iops.other

* Introduced in: 9.7


|metric.v3.iops.read
|integer
|query
|False
a|Filter by metric.v3.iops.read

* Introduced in: 9.7


|metric.v3.iops.write
|integer
|query
|False
a|Filter by metric.v3.iops.write

* Introduced in: 9.7


|metric.v3.duration
|string
|query
|False
a|Filter by metric.v3.duration

* Introduced in: 9.7


|metric.v3.status
|string
|query
|False
a|Filter by metric.v3.status

* Introduced in: 9.7


|metric.v4.timestamp
|string
|query
|False
a|Filter by metric.v4.timestamp

* Introduced in: 9.8


|metric.v4.throughput.total
|integer
|query
|False
a|Filter by metric.v4.throughput.total

* Introduced in: 9.8


|metric.v4.throughput.read
|integer
|query
|False
a|Filter by metric.v4.throughput.read

* Introduced in: 9.8


|metric.v4.throughput.write
|integer
|query
|False
a|Filter by metric.v4.throughput.write

* Introduced in: 9.8


|metric.v4.latency.total
|integer
|query
|False
a|Filter by metric.v4.latency.total

* Introduced in: 9.8


|metric.v4.latency.other
|integer
|query
|False
a|Filter by metric.v4.latency.other

* Introduced in: 9.8


|metric.v4.latency.read
|integer
|query
|False
a|Filter by metric.v4.latency.read

* Introduced in: 9.8


|metric.v4.latency.write
|integer
|query
|False
a|Filter by metric.v4.latency.write

* Introduced in: 9.8


|metric.v4.iops.total
|integer
|query
|False
a|Filter by metric.v4.iops.total

* Introduced in: 9.8


|metric.v4.iops.other
|integer
|query
|False
a|Filter by metric.v4.iops.other

* Introduced in: 9.8


|metric.v4.iops.read
|integer
|query
|False
a|Filter by metric.v4.iops.read

* Introduced in: 9.8


|metric.v4.iops.write
|integer
|query
|False
a|Filter by metric.v4.iops.write

* Introduced in: 9.8


|metric.v4.duration
|string
|query
|False
a|Filter by metric.v4.duration

* Introduced in: 9.8


|metric.v4.status
|string
|query
|False
a|Filter by metric.v4.status

* Introduced in: 9.8


|extended_groups_limit
|integer
|query
|False
a|Filter by extended_groups_limit

* Introduced in: 9.8


|vstorage_enabled
|boolean
|query
|False
a|Filter by vstorage_enabled


|rquota_enabled
|boolean
|query
|False
a|Filter by rquota_enabled

* Introduced in: 9.8


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of NFS Server Records


|records
|array[link:#nfs_service[nfs_service]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "extended_groups_limit": "32",
      "metric": {
        "v3": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "duration": "PT15S",
          "iops": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "latency": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "status": "ok",
          "throughput": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "timestamp": "2017-01-25T11:20:13Z"
        },
        "v4": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "duration": "PT15S",
          "iops": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "latency": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "status": "ok",
          "throughput": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "timestamp": "2017-01-25T11:20:13Z"
        },
        "v41": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "duration": "PT15S",
          "iops": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "latency": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "status": "ok",
          "throughput": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "timestamp": "2017-01-25T11:20:13Z"
        }
      },
      "positive_cached_credential_ttl": "7200000",
      "protocol": {
        "v4_id_domain": "string"
      },
      "state": "string",
      "statistics": {
        "v3": {
          "iops_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "latency_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "status": "ok",
          "throughput_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "timestamp": "2017-01-25T11:20:13Z"
        },
        "v4": {
          "iops_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "latency_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "status": "ok",
          "throughput_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "timestamp": "2017-01-25T11:20:13Z"
        },
        "v41": {
          "iops_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "latency_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "status": "ok",
          "throughput_raw": {
            "read": "200",
            "total": "1000",
            "write": "100"
          },
          "timestamp": "2017-01-25T11:20:13Z"
        }
      },
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#iops]
[.api-collapsible-fifth-title]
iops

The rate of I/O operations observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#latency]
[.api-collapsible-fifth-title]
latency

The round trip latency in microseconds observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#v3]
[.api-collapsible-fifth-title]
v3

The NFSv3 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#v4]
[.api-collapsible-fifth-title]
v4

The NFSv4 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#v41]
[.api-collapsible-fifth-title]
v41

The NFSv4.1 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

Historical performance numbers, such as IOPS latency and throughput, for SVM-NFS protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|v3
|link:#v3[v3]
a|The NFSv3 operations


|v4
|link:#v4[v4]
a|The NFSv4 operations


|v41
|link:#v41[v41]
a|The NFSv4.1 operations


|===


[#v40_features]
[.api-collapsible-fifth-title]
v40_features

[cols=3*,options=header]
|===
|Name
|Type
|Description

|acl_enabled
|boolean
a|Specifies whether NFSv4.0 ACLs is enabled.


|read_delegation_enabled
|boolean
a|Specifies whether NFSv4.0 Read Delegation is enabled.


|write_delegation_enabled
|boolean
a|Specifies whether NFSv4.0 Write Delegation is enabled.


|===


[#v41_features]
[.api-collapsible-fifth-title]
v41_features

[cols=3*,options=header]
|===
|Name
|Type
|Description

|acl_enabled
|boolean
a|Specifies whether NFSv4.1 or later ACLs is enabled.


|pnfs_enabled
|boolean
a|Specifies whether NFSv4.1 or later Parallel NFS is enabled.


|read_delegation_enabled
|boolean
a|Specifies whether NFSv4.1 or later Read Delegation is enabled.


|write_delegation_enabled
|boolean
a|Specifies whether NFSv4.1 or later Write Delegation is enabled.


|===


[#protocol]
[.api-collapsible-fifth-title]
protocol

[cols=3*,options=header]
|===
|Name
|Type
|Description

|v3_64bit_identifiers_enabled
|boolean
a|Specifies whether 64-bit support for NFSv3 FSIDs and file IDs is enabled.


|v3_enabled
|boolean
a|Specifies whether NFSv3 protocol is enabled.


|v40_enabled
|boolean
a|Specifies whether NFSv4.0 protocol is enabled.


|v40_features
|link:#v40_features[v40_features]
a|

|v41_enabled
|boolean
a|Specifies whether NFSv4.1 or later protocol is enabled.


|v41_features
|link:#v41_features[v41_features]
a|

|v4_64bit_identifiers_enabled
|boolean
a|Specifies whether 64-bit support for NFSv4.x FSIDs and file IDs is enabled.


|v4_id_domain
|string
a|Specifies the domain portion of the string form of user and group
names as defined by the NFSv4 protocol.


|===


[#iops_raw]
[.api-collapsible-fifth-title]
iops_raw

The number of I/O operations observed at the storage object. This should be used along with delta time to calculate the rate of I/O operations per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#latency_raw]
[.api-collapsible-fifth-title]
latency_raw

The raw latency in microseconds observed at the storage object. This should be divided by the raw IOPS value to calculate the average latency per I/O operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#throughput_raw]
[.api-collapsible-fifth-title]
throughput_raw

Throughput bytes observed at the storage object. This should be used along with delta time to calculate the rate of throughput bytes per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#v3]
[.api-collapsible-fifth-title]
v3

The NFSv3 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This should be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This should be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the storage object. This should be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#v4]
[.api-collapsible-fifth-title]
v4

The NFSv4 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This should be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This should be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the storage object. This should be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#v41]
[.api-collapsible-fifth-title]
v41

The NFSv4.1 operations


[cols=3*,options=header]
|===
|Name
|Type
|Description

|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This should be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This should be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Any errors associated with the sample. For example, if the aggregation of data over multiple nodes fails then any of the partial errors might be returned, "ok" on success, or "error" on any internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the storage object. This should be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

Realtime performance numbers, such as IOPS latency and throughput, for SVM-NFS protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|v3
|link:#v3[v3]
a|The NFSv3 operations


|v4
|link:#v4[v4]
a|The NFSv4 operations


|v41
|link:#v41[v41]
a|The NFSv4.1 operations


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#transport]
[.api-collapsible-fifth-title]
transport

[cols=3*,options=header]
|===
|Name
|Type
|Description

|tcp_enabled
|boolean
a|Specifies whether TCP transports are enabled on the server.


|udp_enabled
|boolean
a|Specifies whether UDP transports are enabled on the server.


|===


[#nfs_service]
[.api-collapsible-fifth-title]
nfs_service

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|auth_sys_extended_groups_enabled
|boolean
a|Specifies whether or not extended groups support over AUTH_SYS is enabled.


|enabled
|boolean
a|Specifies if the NFS service is administratively enabled.


|extended_groups_limit
|integer
a|Specifies the maximum auxillary groups supported over AUTH_SYS and RPCSEC_GSS.


|metric
|link:#metric[metric]
a|Historical performance numbers, such as IOPS latency and throughput, for SVM-NFS protocol.


|positive_cached_credential_ttl
|integer
a|Specifies the time to live value (in msecs) of a positive cached credential


|protocol
|link:#protocol[protocol]
a|

|rquota_enabled
|boolean
a|Specifies whether or not the remote quota feature is enabled.


|showmount_enabled
|boolean
a|Specifies whether or not the showmount feature is enabled.


|state
|string
a|Specifies the state of the NFS service on the SVM. The following values are supported:
        * online - NFS server is ready to accept client requests.
        * offline - NFS server is not ready to accept client requests.


|statistics
|link:#statistics[statistics]
a|Realtime performance numbers, such as IOPS latency and throughput, for SVM-NFS protocol.


|svm
|link:#svm[svm]
a|

|transport
|link:#transport[transport]
a|

|vstorage_enabled
|boolean
a|Specifies whether or not the VMware vstorage feature is enabled.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
