---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-qos-policies.html'
summary: 'Retrieve QoS policies'
---

= Retrieve QoS policies

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/qos/policies`#

*Introduced In:* 9.6

Retrieves a collection of QoS policies.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|object_count
|integer
|query
|False
a|Filter by object_count


|adaptive.expected_iops
|integer
|query
|False
a|Filter by adaptive.expected_iops


|adaptive.absolute_min_iops
|integer
|query
|False
a|Filter by adaptive.absolute_min_iops


|adaptive.peak_iops
|integer
|query
|False
a|Filter by adaptive.peak_iops


|fixed.min_throughput_mbps
|integer
|query
|False
a|Filter by fixed.min_throughput_mbps

* Introduced in: 9.8


|fixed.min_throughput_iops
|integer
|query
|False
a|Filter by fixed.min_throughput_iops


|fixed.capacity_shared
|boolean
|query
|False
a|Filter by fixed.capacity_shared


|fixed.max_throughput_iops
|integer
|query
|False
a|Filter by fixed.max_throughput_iops


|fixed.max_throughput_mbps
|integer
|query
|False
a|Filter by fixed.max_throughput_mbps


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|uuid
|string
|query
|False
a|Filter by uuid


|name
|string
|query
|False
a|Filter by name


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|error
|link:#error[error]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#qos_policy[qos_policy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  },
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "extreme",
      "object_count": 0,
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#adaptive]
[.api-collapsible-fifth-title]
adaptive

Adaptive QoS policy-groups define measurable service level objectives (SLOs) that adjust based on the storage object used space and the storage object allocated space.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|absolute_min_iops
|integer
a|Specifies the absolute minimum IOPS that is used as an override when the expected_iops is less than this value. These floors are not guaranteed on non-AFF platforms or when FabricPool tiering policies are set.


|expected_iops
|integer
a|Expected IOPS. Specifies the minimum expected IOPS per TB allocated based on the storage object allocated size. These floors are not guaranteed on non-AFF platforms or when FabricPool tiering policies are set.


|peak_iops
|integer
a|Peak IOPS. Specifies the maximum possible IOPS per TB allocated based on the storage object allocated size or the storage object used size.


|===


[#fixed]
[.api-collapsible-fifth-title]
fixed

QoS policy-groups define a fixed service level objective (SLO) for a storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|capacity_shared
|boolean
a|Specifies whether the capacities are shared across all objects that use this QoS policy-group. Default is false.


|max_throughput_iops
|integer
a|Maximum throughput defined by this policy.  It is specified in terms of IOPS. 0 means no maximum throughput is enforced.


|max_throughput_mbps
|integer
a|Maximum throughput defined by this policy.  It is specified in terms of Mbps. 0 means no maximum throughput is enforced.


|min_throughput_iops
|integer
a|Minimum throughput defined by this policy.  It is specified in terms of IOPS. 0 means no minimum throughput is enforced. These floors are not guaranteed on non-AFF platforms or when FabricPool tiering policies are set.


|min_throughput_mbps
|integer
a|Minimum throughput defined by this policy.  It is specified in terms of Mbps. 0 means no minimum throughput is enforced.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#qos_policy]
[.api-collapsible-fifth-title]
qos_policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|adaptive
|link:#adaptive[adaptive]
a|Adaptive QoS policy-groups define measurable service level objectives (SLOs) that adjust based on the storage object used space and the storage object allocated space.


|fixed
|link:#fixed[fixed]
a|QoS policy-groups define a fixed service level objective (SLO) for a storage object.


|name
|string
a|Name of the QoS policy.


|object_count
|integer
a|Number of objects attached to this policy.


|svm
|link:#svm[svm]
a|

|uuid
|string
a|

|===


//end collapsible .Definitions block
====
