---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-cluster-metrocluster-diagnostics.html'
summary: 'Retrieve diagnostic operation results for a MetroCluster configuration'
---

= Retrieve diagnostic operation results for a MetroCluster configuration

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/cluster/metrocluster/diagnostics`#

*Introduced In:* 9.8

Retrieves the results of a completed diagnostic operation for the MetroCluster configuration.


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregate
|link:#aggregate[aggregate]
a|

|cluster
|link:#cluster[cluster]
a|

|config-replication
|link:#config-replication[config-replication]
a|

|connection
|link:#connection[connection]
a|

|interface
|link:#interface[interface]
a|

|node
|link:#node[node]
a|

|volume
|link:#volume[volume]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "aggregate": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10T14:35:16-08:00"
  },
  "cluster": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10T14:35:16-08:00"
  },
  "config-replication": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-14T14:35:16-08:00"
  },
  "connection": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10T14:35:16-08:00"
  },
  "interface": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10T14:35:16-08:00"
  },
  "node": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10T14:35:16-08:00"
  },
  "volume": {
    "state": "string",
    "summary": {
      "code": "string",
      "message": "string"
    },
    "timestamp": "2016-03-10T14:35:16-08:00"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2425734
| An internal error occurred. Wait a few minutes, and try the operation again. For further assistance, contact technical support.

| 2427132
| MetroCluster is not configured on this cluster.

| 2432856
| MetroCluster diagnostics result is not available. Use the REST API GET method on "/api/cluster/metrocluster/operations?type=check&fields=*" for more information.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#summary]
[.api-collapsible-fifth-title]
summary

Additional information or recovery steps to take.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#aggregate]
[.api-collapsible-fifth-title]
aggregate

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#config-replication]
[.api-collapsible-fifth-title]
config-replication

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#connection]
[.api-collapsible-fifth-title]
connection

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#interface]
[.api-collapsible-fifth-title]
interface

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|state
|string
a|Status of diagnostic operation for this component.


|summary
|link:#summary[summary]
a|Additional information or recovery steps to take.


|timestamp
|string
a|Time of the most recent diagnostic operation for this component


|===


//end collapsible .Definitions block
====
