---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-storage-volumes-.html'
summary: 'Retrieve a volume'
---

= Retrieve a volume

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/storage/volumes/{uuid}`#

*Introduced In:* 9.6

Retrieves a volume. The GET API can be used to retrieve the quota state for a FlexVol or a FlexGroup volume.

== Expensive properties

There is an added cost to retrieving values for these properties. They are not included by default in GET results and must be explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.

* `is_svm_root`
* `analytics.+*+`
* `application.+*+`
* `encryption.+*+`
* `clone.parent_snapshot.name`
* `clone.parent_snapshot.uuid`
* `clone.parent_svm.name`
* `clone.parent_svm.uuid`
* `clone.parent_volume.name`
* `clone.parent_volume.uuid`
* `clone.split_complete_percent`
* `clone.split_estimate`
* `clone.split_initiated`
* `efficiency.+*+`
* `error_state.+*+`
* `files.+*+`
* `nas.export_policy.id`
* `nas.gid`
* `nas.path`
* `nas.security_style`
* `nas.uid`
* `nas.unix_permissions`
* `nas.junction_parent.name`
* `nas.junction_parent.uuid`
* `snaplock.+*+`
* `restore_to.+*+`
* `snapshot_policy.uuid`
* `quota.+*+`
* `qos.+*+`
* `flexcache_endpoint_type`
* `space.block_storage_inactive_user_data`
* `space.capacity_tier_footprint`
* `space.performance_tier_footprint`
* `space.local_tier_footprint`
* `space.footprint`
* `space.over_provisioned`
* `space.metadata`
* `space.total_footprint`
* `space.logical_space.+*+`
* `space.snapshot.+*+`
* `space.used_by_afs`
* `space.afs_total`
* `space.available_percent`
* `space.full_threshold_percent`
* `space.nearly_full_threshold_percent`
* `space.overwrite_reserve`
* `space.overwrite_reserve_used`
* `space.size_available_for_snapshots`
* `space.percent_used`
* `space.fractional_reserve`
* `space.block_storage_inactive_user_data_percent`
* `guarantee.+*+`
* `autosize.+*+`
* `movement.+*+`
* `statistics.+*+`

== Related ONTAP commands

* `volume show`
* `volume clone show`
* `volume efficiency show`
* `volume encryption show`
* `volume flexcache show`
* `volume flexgroup show`
* `volume move show`
* `volume quota show`
* `volume show-space`
* `volume snaplock show`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|Unique identifier of the volume.


|fields
|array[string]
|query
|False
a|Specify the fields to return.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|access_time_enabled
|boolean
a|Indicates whether or not access time updates are enabled on the volume.


|aggregates
|array[link:#aggregates[aggregates]]
a|Aggregate hosting the volume. Required on POST.


|analytics
|link:#analytics[analytics]
a|

|application
|link:#application[application]
a|

|autosize
|link:#autosize[autosize]
a|

|clone
|link:#clone[clone]
a|

|cloud_retrieval_policy
|string
a|This parameter specifies the cloud retrieval policy for the volume. This policy determines which tiered out blocks to retrieve from the capacity tier to the performance tier. The available cloud retrieval policies are
"default" policy retrieves tiered data based on the underlying tiering policy. If the tiering policy is 'auto', tiered data is retrieved only for random client driven data reads. If the tiering policy is 'none' or 'snapshot_only', tiered data is retrieved for random and sequential client driven data reads. If the tiering policy is 'all', tiered data is not retrieved.
"on_read" policy retrieves tiered data for all client driven data reads.
"never" policy never retrieves tiered data.
"promote" policy retrieves all eligible tiered data automatically during the next scheduled scan. It is only supported when the tiering policy is 'none' or 'snapshot_only'. If the tiering policy is 'snapshot_only', the only data brought back is the data in the AFS. Data that is only in a snapshot copy stays in the cloud and if tiering policy is 'none' then all data is retrieved.


|comment
|string
a|A comment for the volume. Valid in POST or PATCH.


|consistency_group
|link:#consistency_group[consistency_group]
a|Consistency group the volume is part of.


|constituents
|array[link:#constituents[constituents]]
a|

|create_time
|string
a|Creation time of the volume. This field is generated when the volume is created.


|efficiency
|link:#efficiency[efficiency]
a|

|encryption
|link:#encryption[encryption]
a|

|error_state
|link:#error_state[error_state]
a|

|files
|link:#files[files]
a|

|flexcache_endpoint_type
|string
a|FlexCache endpoint type.
none &dash; The volume is neither a FlexCache nor origin of any FlexCache.
cache &dash; The volume is a FlexCache volume.
origin &dash; The volume is origin of a FlexCache volume.


|guarantee
|link:#guarantee[guarantee]
a|

|is_object_store
|boolean
a|Specifies whether the volume is provisioned for an object store server.


|is_svm_root
|boolean
a|Specifies whether the volume is a root volume of the SVM it belongs to.


|language
|string
a|Language encoding setting for volume. If no language is specified, the volume inherits its SVM language encoding setting.


|metric
|link:#metric[metric]
a|Performance numbers, such as IOPS, latency and throughput.


|movement
|link:#movement[movement]
a|Volume movement. All attributes are modify, that is, not writable through POST. Set PATCH state to destination_aggregate to initiate a volume move operation. Volume movement on FlexGroup constituents are not supported.


|name
|string
a|Volume name. The name of volume must start with an alphabetic character (a to z or A to Z) or an underscore (_). The name must be 197 or fewer characters in length for FlexGroups, and 203 or fewer characters in length for all other types of volumes. Volume names must be unique within an SVM. Required on POST.


|nas
|link:#nas[nas]
a|

|qos
|link:#qos[qos]
a|QoS information


|queue_for_encryption
|boolean
a|Specifies whether the volume is queued for encryption.


|quota
|link:#quota[quota]
a|Quotas track the space or file usage of a user, group, or qtree in a FlexVol or a FlexGroup volume.


|size
|integer
a|Physical size of the volume, in bytes. The minimum size for a FlexVol volume is 20MB and the minimum size for a FlexGroup volume is 200MB per constituent. The recommended size for a FlexGroup volume is a minimum of 100GB per constituent. For all volumes, the default size is equal to the minimum size.


|snaplock
|link:#snaplock[snaplock]
a|

|snapmirror
|link:#snapmirror[snapmirror]
a|Specifies attributes for SnapMirror protection.


|snapshot_policy
|link:#snapshot_policy[snapshot_policy]
a|This is a reference to the Snapshot copy policy.


|space
|link:#space[space]
a|

|state
|string
a|Volume state. A volume can only be brought online if it is offline. Taking a volume offline removes its junction path. The 'mixed' state applies to FlexGroup volumes only and cannot be specified as a target state. An 'error' state implies that the volume is not in a state to serve data.


|statistics
|link:#statistics[statistics]
a|These are raw performance numbers, such as IOPS latency and throughput. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster.


|status
|array[string]
a|Describes the current status of a volume.


|style
|string
a|The style of the volume. If "style" is not specified, the volume type is determined based on the specified aggregates. Specifying a single aggregate, without "constituents_per_aggregate", creates a flexible volume. Specifying multiple aggregates, or a single aggregate with "constituents_per_aggregate", creates a FlexGroup. Specifying a volume "style" creates a volume of that type. For example, if the style is "flexvol" you must specify a single aggregate. If the style is "flexgroup", the system either uses the specified aggregates or automatically provisions aggregates if there are no specified aggregates.
flexvol &dash; flexible volumes and FlexClone volumes
flexgroup &dash; FlexGroups.


|svm
|link:#svm[svm]
a|SVM containing the volume. Required on POST.


|tiering
|link:#tiering[tiering]
a|

|type
|string
a|Type of the volume.
rw &dash; read-write volume.
dp &dash; data-protection volume.
ls &dash; load-sharing `dp` volume. Valid in GET.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* readOnly: 1
* Introduced in: 9.6


|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "aggregates": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "aggr1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "analytics": {
    "scan_progress": "17",
    "state": "string",
    "unsupported_reason": {
      "code": "111411207",
      "message": "File system analytics cannot be enabled on volumes that contain LUNs."
    }
  },
  "application": {
    "name": "string",
    "uuid": "1cd8a442-86d1-11e0-ae1d-123478563412"
  },
  "autosize": {
    "mode": "string"
  },
  "clone": {
    "parent_snapshot": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "this_snapshot",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "parent_svm": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "svm1",
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
    },
    "parent_volume": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "volume1",
      "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
    },
    "split_complete_percent": 0,
    "split_estimate": 0
  },
  "cloud_retrieval_policy": "string",
  "comment": "string",
  "consistency_group": {
    "name": "consistency_group_1"
  },
  "constituents": [
    {
      "aggregates": {
        "name": "string",
        "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
      },
      "movement": {
        "cutover_window": "30",
        "destination_aggregate": {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "aggr1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "percent_complete": 0,
        "state": "replicating",
        "tiering_policy": "string"
      },
      "name": "string",
      "space": {
        "available": 0,
        "block_storage_inactive_user_data": 0,
        "capacity_tier_footprint": 0,
        "footprint": 0,
        "local_tier_footprint": 0,
        "logical_space": {
          "available": 0,
          "used_by_afs": 0
        },
        "metadata": 0,
        "over_provisioned": 0,
        "performance_tier_footprint": 0,
        "snapshot": {
          "used": 0
        },
        "total_footprint": 0,
        "used": 0
      }
    }
  ],
  "create_time": "2018-06-04T19:00:00Z",
  "efficiency": {
    "compaction": "string",
    "compression": "string",
    "cross_volume_dedupe": "string",
    "dedupe": "string",
    "last_op_begin": "string",
    "last_op_end": "string",
    "last_op_err": "string",
    "last_op_state": "string",
    "op_state": "string",
    "path": "string",
    "policy": {
      "name": "string"
    },
    "progress": "string",
    "schedule": "string",
    "state": "string",
    "type": "string"
  },
  "encryption": {
    "key_id": "string",
    "state": "string",
    "status": {
      "code": "string",
      "message": "string"
    },
    "type": "string"
  },
  "files": {
    "used": 0
  },
  "flexcache_endpoint_type": "string",
  "guarantee": {
    "type": "string"
  },
  "language": "string",
  "metric": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "cloud": {
      "duration": "PT15S",
      "iops": {
        "read": "200",
        "total": "1000",
        "write": "100"
      },
      "latency": {
        "read": "200",
        "total": "1000",
        "write": "100"
      },
      "status": "ok",
      "timestamp": "2017-01-25T11:20:13Z"
    },
    "duration": "PT15S",
    "flexcache": {
      "bandwidth_savings": "4096",
      "cache_miss_percent": "20",
      "duration": "PT1D",
      "status": "ok",
      "timestamp": "2017-01-25T11:20:13Z"
    },
    "iops": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "latency": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "status": "ok",
    "throughput": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "timestamp": "2017-01-25T11:20:13Z"
  },
  "movement": {
    "cutover_window": "30",
    "destination_aggregate": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "aggr1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "percent_complete": 0,
    "start_time": "2020-12-07T03:45:12-05:00",
    "state": "replicating",
    "tiering_policy": "string"
  },
  "name": "vol_cs_dept",
  "nas": {
    "export_policy": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "id": "100",
      "name": "default"
    },
    "junction_parent": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "name": "vs1_root",
      "uuid": "75c9cfb0-3eb4-11eb-9fb4-005056bb088a"
    },
    "path": "/user/my_volume",
    "security_style": "string",
    "unix_permissions": "0755"
  },
  "qos": {
    "policy": {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "max_throughput_iops": "10000",
      "max_throughput_mbps": "500",
      "min_throughput_iops": "2000",
      "min_throughput_mbps": "500",
      "name": "performance",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  },
  "quota": {
    "state": "string"
  },
  "snaplock": {
    "append_mode_enabled": "",
    "autocommit_period": "P30M",
    "compliance_clock_time": "2018-06-04T19:00:00Z",
    "expiry_time": "Wed Sep  5 11:02:42 GMT 2018",
    "is_audit_log": 1,
    "litigation_count": "10",
    "privileged_delete": "enabled",
    "retention": {
      "default": "P30Y",
      "maximum": "P30Y",
      "minimum": "P30Y"
    },
    "type": "enterprise",
    "unspecified_retention_file_count": "10"
  },
  "snapshot_policy": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "default",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "space": {
    "available": 0,
    "block_storage_inactive_user_data": 0,
    "block_storage_inactive_user_data_percent": 0,
    "capacity_tier_footprint": 0,
    "footprint": 0,
    "local_tier_footprint": 0,
    "logical_space": {
      "available": 0,
      "used": 0,
      "used_by_afs": 0,
      "used_percent": 0
    },
    "metadata": 0,
    "over_provisioned": 0,
    "overwrite_reserve": 0,
    "overwrite_reserve_used": 0,
    "percent_used": 0,
    "performance_tier_footprint": 0,
    "size_available_for_snapshots": 0,
    "snapshot": {
      "reserve_size": 0,
      "space_used_percent": 0,
      "used": 0
    },
    "total_footprint": 0,
    "used": 0
  },
  "state": "string",
  "statistics": {
    "cloud": {
      "iops_raw": {
        "read": "200",
        "total": "1000",
        "write": "100"
      },
      "latency_raw": {
        "read": "200",
        "total": "1000",
        "write": "100"
      },
      "status": "ok",
      "timestamp": "2017-01-25T11:20:13Z"
    },
    "flexcache_raw": {
      "cache_miss_blocks": "10",
      "client_requested_blocks": "500",
      "status": "ok",
      "timestamp": "2017-01-25T11:20:13Z"
    },
    "iops_raw": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "latency_raw": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "status": "ok",
    "throughput_raw": {
      "read": "200",
      "total": "1000",
      "write": "100"
    },
    "timestamp": "2017-01-25T11:20:13Z"
  },
  "status": [
    "string"
  ],
  "style": "string",
  "svm": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "tiering": {
    "object_tags": [
      "string"
    ],
    "policy": "string",
    "supported": null
  },
  "type": "string",
  "use_mirrored_aggregates": null,
  "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#aggregates]
[.api-collapsible-fifth-title]
aggregates

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#unsupported_reason]
[.api-collapsible-fifth-title]
unsupported_reason

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|If file system analytics is not supported on the volume, this field provides the error code explaining why.


|message
|string
a|If file system analytics is not supported on the volume, this field provides the error message explaining why.


|===


[#analytics]
[.api-collapsible-fifth-title]
analytics

[cols=3*,options=header]
|===
|Name
|Type
|Description

|scan_progress
|integer
a|Percentage of files in the volume that the file system analytics initialization scan has processed. Only returned when the state is `initializing`.


|state
|string
a|File system analytics state of the volume. If this value is "on", ONTAP collects extra file system analytics information for all directories on the volume.  There will be a slight impact to I/O performance to collect this information. If this value is "off", file system analytics information is not collected and not available to be viewed. If this value is "initializing", that means file system analytics was recently turned on, and the initialization scan to gather information all all existing files and directories is currently running. If this value is 'unknown' that means there was an internal error when determining the file system analytics state for the volume.

* enum: ["unknown", "initializing", "off", "on"]
* Introduced in: 9.8


|supported
|boolean
a|This field indicates whether or not file system analytics is supported on the volume. If file system analytics is not supported, the reason will be specified in the "analytics.unsupported_reason" field.


|unsupported_reason
|link:#unsupported_reason[unsupported_reason]
a|

|===


[#application]
[.api-collapsible-fifth-title]
application

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the application to which the volume belongs. Available only when the volume is part of an application.


|uuid
|string
a|UUID of the application to which the volume belongs. Available only when the volume is part of an application.


|===


[#autosize]
[.api-collapsible-fifth-title]
autosize

[cols=3*,options=header]
|===
|Name
|Type
|Description

|grow_threshold
|integer
a|Used space threshold size, in percentage, for the automatic growth of the volume. When the amount of used space in the volume becomes greater than this threhold, the volume automatically grows unless it has reached the maximum size. The volume grows when 'space.used' is greater than this percent of 'space.size'. The 'grow_threshold' size cannot be less than or equal to the 'shrink_threshold' size..


|maximum
|integer
a|Maximum size in bytes up to which a volume grows automatically. This size cannot be less than the current volume size, or less than or equal to the minimum size of volume.


|minimum
|integer
a|Minimum size in bytes up to which the volume shrinks automatically. This size cannot be greater than or equal to the maximum size of volume.


|mode
|string
a|Autosize mode for the volume.
grow &dash; Volume automatically grows when the amount of used space is above the 'grow_threshold' value.
grow_shrink &dash; Volume grows or shrinks in response to the amount of space used.
off &dash; Autosizing of the volume is disabled.


|shrink_threshold
|integer
a|Used space threshold size, in percentage, for the automatic shrinkage of the volume.  When the amount of used space in the volume drops below this threshold, the volume automatically shrinks unless it has reached the minimum size. The volume shrinks when the 'space.used' is less than the 'shrink_threshold' percent of 'space.size'. The 'shrink_threshold' size cannot be greater than or equal to the 'grow_threshold' size.


|===


[#snapshot_reference]
[.api-collapsible-fifth-title]
snapshot_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#parent_svm]
[.api-collapsible-fifth-title]
parent_svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#parent_volume]
[.api-collapsible-fifth-title]
parent_volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6


|===


[#clone]
[.api-collapsible-fifth-title]
clone

[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_flexclone
|boolean
a|Specifies if this volume is a normal FlexVol or FlexClone. This field needs to be set when creating a FlexClone. Valid in POST.


|parent_snapshot
|link:#snapshot_reference[snapshot_reference]
a|

|parent_svm
|link:#parent_svm[parent_svm]
a|

|parent_volume
|link:#parent_volume[parent_volume]
a|

|split_complete_percent
|integer
a|Percentage of FlexClone blocks split from its parent volume.


|split_estimate
|integer
a|Space required by the containing-aggregate to split the FlexClone volume.


|split_initiated
|boolean
a|This field is set when split is executed on any FlexClone, that is when the FlexClone volume is split from its parent FlexVol. This field needs to be set for splitting a FlexClone form FlexVol. Valid in PATCH.


|===


[#consistency_group]
[.api-collapsible-fifth-title]
consistency_group

Consistency group the volume is part of.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the consistency group.


|===


[#aggregates]
[.api-collapsible-fifth-title]
aggregates

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the aggregate hosting the FlexGroup Constituent.


|uuid
|string
a|Unique identifier for the aggregate.


|===


[#destination_aggregate]
[.api-collapsible-fifth-title]
destination_aggregate

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#movement]
[.api-collapsible-fifth-title]
movement

Volume movement. All attributes are modify, that is, not writable through POST. Set PATCH state to destination_aggregate to initiate a volume move operation. Volume movement on FlexGroup constituents are not supported.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cutover_window
|integer
a|Time window in seconds for cutover. The allowed range is between 30 to 300 seconds.


|destination_aggregate
|link:#destination_aggregate[destination_aggregate]
a|Aggregate


|percent_complete
|integer
a|Completion percentage


|state
|string
a|State of volume move operation. PATCH the state to "aborted" to abort the move operation. PATCH the state to "cutover" to trigger cutover. PATCH the state to "paused" to pause the volume move operation in progress. PATCH the state to "replicating" to resume the paused volume move operation. PATCH the state to "cutover_wait" to go into cutover manually. When volume move operation is waiting to go into "cutover" state, this is indicated by the "cutover_pending" state. A change of state is only supported if volume movement is in progress.


|tiering_policy
|string
a|Tiering policy for FabricPool


|===


[#logical_space]
[.api-collapsible-fifth-title]
logical_space

[cols=3*,options=header]
|===
|Name
|Type
|Description

|available
|integer
a|The amount of space available in this volume with storage efficiency space considered used, in bytes.


|enforcement
|boolean
a|Specifies whether space accounting for operations on the volume is done along with storage efficiency.


|reporting
|boolean
a|Specifies whether space reporting on the volume is done along with storage efficiency.


|used_by_afs
|integer
a|The virtual space used by AFS alone (includes volume reserves) and along with storage efficiency, in bytes.


|===


[#snapshot]
[.api-collapsible-fifth-title]
snapshot

[cols=3*,options=header]
|===
|Name
|Type
|Description

|autodelete_enabled
|boolean
a|Specifies whether Snapshot copy autodelete is currently enabled on this volume.


|reserve_percent
|integer
a|The space that has been set aside as a reserve for Snapshot copy usage, in percent.


|used
|integer
a|The total space used by Snapshot copies in the volume, in bytes.


|===


[#space]
[.api-collapsible-fifth-title]
space

[cols=3*,options=header]
|===
|Name
|Type
|Description

|afs_total
|integer
a|Total size of AFS, excluding snap-reserve, in bytes.


|available
|integer
a|The available space, in bytes.


|available_percent
|integer
a|The space available, as a percent.


|block_storage_inactive_user_data
|integer
a|The size that is physically used in the block storage of the volume and has a cold temperature. In bytes. This parameter is only supported if the volume is in an aggregate that is either attached to a cloud store or could be attached to a cloud store.


|capacity_tier_footprint
|integer
a|Space used by capacity tier for this volume in the FabricPool aggregate, in bytes.


|footprint
|integer
a|Data used for this volume in the aggregate, in bytes.


|local_tier_footprint
|integer
a|Space used by the local tier for this volume in the aggregate, in bytes.


|logical_space
|link:#logical_space[logical_space]
a|

|metadata
|integer
a|Space used by the volume metadata in the aggregate, in bytes.


|over_provisioned
|integer
a|The amount of space not available for this volume in the aggregate, in bytes.


|performance_tier_footprint
|integer
a|Space used by the performance tier for this volume in the FabricPool aggregate, in bytes.


|size
|integer
a|Total provisioned size. The default size is equal to the minimum size of 20MB, in bytes.


|snapshot
|link:#snapshot[snapshot]
a|

|total_footprint
|integer
a|Data and metadata used for this volume in the aggregate, in bytes.


|used
|integer
a|The virtual space used (includes volume reserves) before storage efficiency, in bytes.


|used_by_afs
|integer
a|The space used by Active Filesystem, in bytes.


|===


[#constituents]
[.api-collapsible-fifth-title]
constituents

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|link:#aggregates[aggregates]
a|

|movement
|link:#movement[movement]
a|Volume movement. All attributes are modify, that is, not writable through POST. Set PATCH state to destination_aggregate to initiate a volume move operation. Volume movement on FlexGroup constituents are not supported.


|name
|string
a|FlexGroup Constituents name


|space
|link:#space[space]
a|

|===


[#policy]
[.api-collapsible-fifth-title]
policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Specifies the name of the efficiency policy. Valid for PATCH.


|===


[#efficiency]
[.api-collapsible-fifth-title]
efficiency

[cols=3*,options=header]
|===
|Name
|Type
|Description

|compaction
|string
a|The system can be enabled/disabled compaction.
inline &dash; Data will be compacted first and written to the volume.
none &dash; None
mixed &dash; Read only field for FlexGroups, where some of the constituent volumes are compaction enabled and some are disabled.


|compression
|string
a|The system can be enabled/disabled compression.
inline &dash; Data will be compressed first and written to the volume.
background &dash; Data will be written to the volume and compressed later.
both &dash; Inline compression compresses the data and write to the volume, background compression compresses only the blocks on which inline compression is not run.
none &dash; None
mixed &dash; Read only field for FlexGroups, where some of the constituent volumes are compression enabled and some are disabled.


|cross_volume_dedupe
|string
a|The system can be enabled/disabled cross volume dedupe. it can be enabled only when dedupe is enabled.
inline &dash; Data will be cross volume deduped first and written to the volume.
background &dash; Data will be written to the volume and cross volume deduped later.
both &dash; Inline cross volume dedupe dedupes the data and write to the volume, background cross volume dedupe dedupes only the blocks on which inline dedupe is not run.
none &dash; None
mixed &dash; Read only field for FlexGroups, where some of the constituent volumes are cross volume dedupe enabled and some are disabled.


|dedupe
|string
a|The system can be enabled/disabled dedupe.
inline &dash; Data will be deduped first and written to the volume.
background &dash; Data will be written to the volume and deduped later.
both &dash; Inline dedupe dedupes the data and write to the volume, background dedupe dedupes only the blocks on which inline dedupe is not run.
none &dash; None
mixed &dash; Read only field for FlexGroups, where some of the constituent volumes are dedupe enabled and some are disabled.


|last_op_begin
|string
a|Last sis operation begin timestamp.


|last_op_end
|string
a|Last sis operation end timestamp.


|last_op_err
|string
a|Last sis operation error text.


|last_op_size
|integer
a|Last sis operation size.


|last_op_state
|string
a|Last sis operation state.


|op_state
|string
a|Sis status of the volume.


|path
|string
a|Absolute volume path of the volume.


|policy
|link:#policy[policy]
a|

|progress
|string
a|Sis progress of the volume.


|schedule
|string
a|Schedule associated with volume.


|state
|string
a|Sis state of the volume.


|type
|string
a|Sis Type of the volume.


|===


[#status]
[.api-collapsible-fifth-title]
status

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Encryption progress message code.


|message
|string
a|Encryption progress message.


|===


[#encryption]
[.api-collapsible-fifth-title]
encryption

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Creates an encrypted or an unencrypted volume. For POST, when set to 'true', a new key is generated and used to encrypt the given volume. In that case, the underlying SVM must be configured with the key manager. When set to 'false', the volume created will be unencrypted. For PATCH, when set to 'true', it encrypts an unencrypted volume. Specifying the parameter as 'false' in a PATCH operation for an encrypted volume is only supported when moving the volume to another aggregate.


|key_id
|string
a|The key ID used for creating encrypted volume. A new key-id is generated for creating an encrypted volume. This key-id is associated with the generated key.


|rekey
|boolean
a|If set to 'true', re-encrypts the volume with a new key. Valid in PATCH.


|state
|string
a|Volume encryption state.
encrypted &dash; The volume is completely encrypted.
encrypting &dash; Encryption operation is in progress.
partial &dash; Some constituents are encrypted and some are not. Applicable only for FlexGroup volume.
rekeying. Encryption of volume with a new key is in progress.
unencrypted &dash; The volume is a plain-text one.


|status
|link:#status[status]
a|

|type
|string
a|Volume encryption type.
none &dash; The volume is a plain-text one.
volume &dash; The volume is encrypted with NVE (NetApp Volume Encryption).
aggregate &dash; The volume is encrypted with NAE (NetApp Aggregate Encryption).


|===


[#error_state]
[.api-collapsible-fifth-title]
error_state

[cols=3*,options=header]
|===
|Name
|Type
|Description

|has_bad_blocks
|boolean
a|Indicates whether the volume has any corrupt data blocks. If the damaged data block is accessed, an IO error, such as EIO for NFS or STATUS_FILE_CORRUPT for CIFS, is returned.


|is_inconsistent
|boolean
a|Indicates whether the file system has any inconsistencies.
true &dash; File system is inconsistent.
false &dash; File system in not inconsistent.


|===


[#files]
[.api-collapsible-fifth-title]
files

[cols=3*,options=header]
|===
|Name
|Type
|Description

|maximum
|integer
a|The maximum number of files (inodes) for user-visible data allowed on the volume. This value can be increased or decreased. Increasing the maximum number of files does not immediately cause additional disk space to be used to track files. Instead, as more files are created on the volume, the system dynamically increases the number of disk blocks that are used to track files. The space assigned to track files is never freed, and this value cannot be decreased below the current number of files that can be tracked within the assigned space for the volume. Valid in PATCH.


|used
|integer
a|Number of files (inodes) used for user-visible data permitted on the volume. This field is valid only when the volume is online.


|===


[#guarantee]
[.api-collapsible-fifth-title]
guarantee

[cols=3*,options=header]
|===
|Name
|Type
|Description

|honored
|boolean
a|Is the space guarantee of this volume honored in the aggregate?


|type
|string
a|The type of space guarantee of this volume in the aggregate.


|===


[#iops]
[.api-collapsible-fifth-title]
iops

The rate of I/O operations observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#latency]
[.api-collapsible-fifth-title]
latency

The round trip latency in microseconds observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#cloud]
[.api-collapsible-fifth-title]
cloud

Performance numbers (IOPS and latency) for cloud store. These numbers are relevant only for volumes hosted on FabricPools.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#flexcache]
[.api-collapsible-fifth-title]
flexcache

Performance number for FlexCache used to measure cache effectiveness.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|bandwidth_savings
|integer
a|Bandwidth savings denoting the amount of data served locally by the cache, in bytes.


|cache_miss_percent
|integer
a|Cache miss percentage.


|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the storage object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

Performance numbers, such as IOPS, latency and throughput.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|cloud
|link:#cloud[cloud]
a|Performance numbers (IOPS and latency) for cloud store. These numbers are relevant only for volumes hosted on FabricPools.


|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|flexcache
|link:#flexcache[flexcache]
a|Performance number for FlexCache used to measure cache effectiveness.


|iops
|link:#iops[iops]
a|The rate of I/O operations observed at the storage object.


|latency
|link:#latency[latency]
a|The round trip latency in microseconds observed at the storage object.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the storage object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#movement]
[.api-collapsible-fifth-title]
movement

Volume movement. All attributes are modify, that is, not writable through POST. Set PATCH state to destination_aggregate to initiate a volume move operation. Volume movement on FlexGroup constituents are not supported.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cutover_window
|integer
a|Time window in seconds for cutover. The allowed range is between 30 to 300 seconds.


|destination_aggregate
|link:#destination_aggregate[destination_aggregate]
a|Aggregate


|percent_complete
|integer
a|Completion percentage


|start_time
|string
a|Start time of volume move.


|state
|string
a|State of volume move operation. PATCH the state to "aborted" to abort the move operation. PATCH the state to "cutover" to trigger cutover. PATCH the state to "paused" to pause the volume move operation in progress. PATCH the state to "replicating" to resume the paused volume move operation. PATCH the state to "cutover_wait" to go into cutover manually. When volume move operation is waiting to go into "cutover" state, this is indicated by the "cutover_pending" state. A change of state is only supported if volume movement is in progress.


|tiering_policy
|string
a|Tiering policy for FabricPool


|===


[#export_policy]
[.api-collapsible-fifth-title]
export_policy

Export Policy


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|id
|integer
a|

|name
|string
a|

|===


[#junction_parent]
[.api-collapsible-fifth-title]
junction_parent

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the parent volume that contains the junction inode of this volume. The junction parent volume must belong to the same SVM that owns this volume.


|uuid
|string
a|Unique identifier for the parent volume.


|===


[#nas]
[.api-collapsible-fifth-title]
nas

[cols=3*,options=header]
|===
|Name
|Type
|Description

|export_policy
|link:#export_policy[export_policy]
a|Export Policy


|gid
|integer
a|The UNIX group ID of the volume. Valid in POST or PATCH.


|junction_parent
|link:#junction_parent[junction_parent]
a|

|path
|string
a|The fully-qualified path in the owning SVM's namespace at which the volume is mounted. The path is case insensitive and must be unique within a SVM's namespace. Path must begin with '/' and must not end with '/'. Only one volume can be mounted at any given junction path. An empty path in POST creates an unmounted volume. An empty path in PATCH deactivates and unmounts the volume. Taking a volume offline removes its junction path. This attribute is reported in GET only when the volume is mounted.


|security_style
|string
a|Security style associated with the volume. Valid in POST or PATCH.
mixed &dash; Mixed-style security
ntfs &dash; NTFS/WIndows-style security
unified &dash; Unified-style security, unified UNIX, NFS and CIFS permissions
unix &dash; Unix-style security.


|uid
|integer
a|The UNIX user ID of the volume. Valid in POST or PATCH.


|unix_permissions
|integer
a|UNIX permissions to be viewed as an octal number. It consists of 4 digits derived by adding up bits 4 (read), 2 (write) and 1 (execute). First digit selects the set user ID(4), set group ID (2) and sticky (1) attributes. The second digit selects permission for the owner of the file; the third selects permissions for other users in the same group; the fourth for other users not in the group. Valid in POST or PATCH. For security style "mixed" or "unix", the default setting is 0755 in octal (493 in decimal) and for security style "ntfs", the default setting is 0000. In cases where only owner, group and other permissions are given (as in 755, representing the second, third and fourth dight), first digit is assumed to be zero.


|===


[#policy]
[.api-collapsible-fifth-title]
policy

When "min_throughput_iops", "min_throughput_mbps", "max_throughput_iops" or "max_throughput_mbps" attributes are specified, the storage object is assigned to an auto-generated QoS policy group. If the attributes are later modified, the auto-generated QoS policy-group attributes are modified. Attributes can be removed by specifying "0" and policy group by specifying "none". Upon deletion of the storage object or if the attributes are removed, then the QoS policy-group is also removed.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|max_throughput_mbps
|integer
a|Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none. Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH.


|min_throughput_mbps
|integer
a|Specifies the minimum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#qos]
[.api-collapsible-fifth-title]
qos

QoS information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|policy
|link:#policy[policy]
a|When "min_throughput_iops", "min_throughput_mbps", "max_throughput_iops" or "max_throughput_mbps" attributes are specified, the storage object is assigned to an auto-generated QoS policy group. If the attributes are later modified, the auto-generated QoS policy-group attributes are modified. Attributes can be removed by specifying "0" and policy group by specifying "none". Upon deletion of the storage object or if the attributes are removed, then the QoS policy-group is also removed.


|===


[#quota]
[.api-collapsible-fifth-title]
quota

Quotas track the space or file usage of a user, group, or qtree in a FlexVol or a FlexGroup volume.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|This option is used to enable or disable the quota for the volume. This option is valid only in PATCH. Quotas are enabled for FlexVols or FlexGroup volumes when the quota state is "on". Quotas are disabled for FlexVols or FlexGroup volumes when the quota state is "off".


|state
|string
a|Quota state of the volume


|===


[#retention]
[.api-collapsible-fifth-title]
retention

[cols=3*,options=header]
|===
|Name
|Type
|Description

|default
|string
a|Specifies the default retention period that is applied to files while committing them to the WORM state without an associated retention period. The retention value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours, and minutes. A duration specified for years, months, and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. A duration in hours and minutes is represented by "PT+++<num>+++H" and "PT+++<num>+++M" respectively. The retention string must contain only a single time element that is, either years, months, days, hours, or minutes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the duration field also accepts the string "infinite" to set an infinite retention period and the string "unspecified" to set an unspecified retention period.+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|maximum
|string
a|Specifies the maximum allowed retention period for files committed to the WORM state on the volume. The retention value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours, and minutes. A duration specified for years, months, and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. A duration in hours and minutes is represented by "PT+++<num>+++H" and "PT+++<num>+++M" respectively. The retention string must contain only a single time element that is, either years, months, days, hours, or minutes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the duration field also accepts the string "infinite" to set an infinite retention period.+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|minimum
|string
a|Specifies the minimum allowed retention period for files committed to the WORM state on the volume. The retention value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours, and minutes. A duration specified for years, month,s and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. A duration in hours and minutes is represented by "PT+++<num>+++H" and "PT+++<num>+++M" respectively. The retention string must contain only a single time element that is, either years, months, days, hours, or minutes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the duration field also accepts the string "infinite" to set an infinite retention period.+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|===


[#snaplock]
[.api-collapsible-fifth-title]
snaplock

[cols=3*,options=header]
|===
|Name
|Type
|Description

|append_mode_enabled
|boolean
a|Specifies if the volume append mode is enabled or disabled. When it is enabled, all the files created with write permissions on the volume are, by default, WORM appendable files. The user can append the data to a WORM appendable file but cannot modify the existing contents of the file nor delete the file until it expires.


|autocommit_period
|string
a|Specifies the autocommit period for SnapLock volume. All files which are not modified for a period greater than the autocommit period of the volume are committed to the WORM state. The autocommit period value represents a duration and must be specified in the ISO-8601 duration format. The autocommit period can be in years, months, days, hours, and minutes. A period specified for years, months, and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively, for example "P10Y" represents a duration of 10 years. A duration in hours and minutes is represented by "PT+++<num>+++H" and "PT+++<num>+++M" respectively. The period string must contain only a single time element that is, either years, months, days, hours, or minutes. A duration which combines different periods is not supported, for example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the autocommit field also accepts the string "none".+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|compliance_clock_time
|string
a|This is the volume compliance clock time which is used to manage the SnapLock objects in the volume.


|expiry_time
|string
a|Expiry time of the volume.


|is_audit_log
|boolean
a|Indicates if this volume has been configured as SnapLock audit log volume for the SVM .


|litigation_count
|integer
a|Litigation count indicates the number of active legal-holds on the volume.


|privileged_delete
|string
a|Specifies the privileged-delete attribute of a SnapLock volume. On a SnapLock Enterprise (SLE) volume, a designated privileged user can selectively delete files irrespective of the retention time of the file. SLE volumes can have privileged delete as disabled, enabled or permanently_disabled and for SnapLock Compliance (SLC) volumes it is always permanently_disabled.


|retention
|link:#retention[retention]
a|

|type
|string
a|The SnapLock type of the volume.
compliance &dash; A SnapLock Compliance(SLC) volume provides the highest level of WORM protection and an administrator cannot destroy a SLC volume if it contains unexpired WORM files.
 enterprise &dash; An administrator can delete a SnapLock Enterprise(SLE) volume.
 non_snaplock &dash; Indicates the volume is non-snaplock.


|unspecified_retention_file_count
|integer
a|Indicates the number of files with an unspecified retention time in the volume.


|===


[#destinations]
[.api-collapsible-fifth-title]
destinations

[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_cloud
|boolean
a|Specifies whether a volume is a SnapMirror source volume, using SnapMirror to protect its data to a cloud destination.


|is_ontap
|boolean
a|Specifies whether a volume is a SnapMirror source volume, using SnapMirror to protect its data to an ONTAP destination.

* readOnly: 1
* Introduced in: 9.9


|===


[#snapmirror]
[.api-collapsible-fifth-title]
snapmirror

Specifies attributes for SnapMirror protection.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|destinations
|link:#destinations[destinations]
a|

|is_protected
|boolean
a|Specifies whether a volume is a SnapMirror source volume, using SnapMirror to protect its data.


|===


[#snapshot_policy]
[.api-collapsible-fifth-title]
snapshot_policy

This is a reference to the Snapshot copy policy.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#logical_space]
[.api-collapsible-fifth-title]
logical_space

[cols=3*,options=header]
|===
|Name
|Type
|Description

|available
|integer
a|The amount of space available in this volume with storage efficiency space considered used, in bytes.


|enforcement
|boolean
a|Specifies whether space accounting for operations on the volume is done along with storage efficiency.


|reporting
|boolean
a|Specifies whether space reporting on the volume is done along with storage efficiency.


|used
|integer
a|SUM of (physical-used, shared_refs, compression_saved_in_plane0, vbn_zero, future_blk_cnt), in bytes.


|used_by_afs
|integer
a|The virtual space used by AFS alone (includes volume reserves) and along with storage efficiency, in bytes.


|used_percent
|integer
a|SUM of (physical-used, shared_refs, compression_saved_in_plane0, vbn_zero, future_blk_cnt), as a percentage.


|===


[#snapshot]
[.api-collapsible-fifth-title]
snapshot

[cols=3*,options=header]
|===
|Name
|Type
|Description

|autodelete_enabled
|boolean
a|Specifies whether Snapshot copy autodelete is currently enabled on this volume.


|reserve_percent
|integer
a|The space that has been set aside as a reserve for Snapshot copy usage, in percent.


|reserve_size
|integer
a|Size in the volume that has been set aside as a reserve for Snapshot copy usage, in bytes.


|space_used_percent
|integer
a|Percentage of snapshot reserve size that has been used.


|used
|integer
a|The total space used by Snapshot copies in the volume, in bytes.


|===


[#space]
[.api-collapsible-fifth-title]
space

[cols=3*,options=header]
|===
|Name
|Type
|Description

|afs_total
|integer
a|Total size of AFS, excluding snap-reserve, in bytes.


|available
|integer
a|The available space, in bytes.


|available_percent
|integer
a|The space available, as a percent.


|block_storage_inactive_user_data
|integer
a|The size that is physically used in the block storage of the volume and has a cold temperature. In bytes. This parameter is only supported if the volume is in an aggregate that is either attached to a cloud store or could be attached to a cloud store.


|block_storage_inactive_user_data_percent
|integer
a|Percentage of size that is physically used in the performance tier of the volume.


|capacity_tier_footprint
|integer
a|Space used by capacity tier for this volume in the FabricPool aggregate, in bytes.


|footprint
|integer
a|Data used for this volume in the aggregate, in bytes.


|fractional_reserve
|integer
a|Used to change the amount of space reserved for overwrites of reserved objects in a volume.


|full_threshold_percent
|integer
a|Volume full threshold percentage at which EMS warnings can be sent.


|local_tier_footprint
|integer
a|Space used by the local tier for this volume in the aggregate, in bytes.


|logical_space
|link:#logical_space[logical_space]
a|

|metadata
|integer
a|Space used by the volume metadata in the aggregate, in bytes.


|nearly_full_threshold_percent
|integer
a|Volume nearly full threshold percentage at which EMS warnings can be sent.


|over_provisioned
|integer
a|The amount of space not available for this volume in the aggregate, in bytes.


|overwrite_reserve
|integer
a|Reserved space for overwrites, in bytes.


|overwrite_reserve_used
|integer
a|Overwrite logical reserve space used, in bytes.


|percent_used
|integer
a|Percentage of the volume size that is used.


|performance_tier_footprint
|integer
a|Space used by the performance tier for this volume in the FabricPool aggregate, in bytes.


|size
|integer
a|Total provisioned size. The default size is equal to the minimum size of 20MB, in bytes.


|size_available_for_snapshots
|integer
a|Available space for Snapshot copies from snap-reserve, in bytes.


|snapshot
|link:#snapshot[snapshot]
a|

|total_footprint
|integer
a|Data and metadata used for this volume in the aggregate, in bytes.


|used
|integer
a|The virtual space used (includes volume reserves) before storage efficiency, in bytes.


|used_by_afs
|integer
a|The space used by Active Filesystem, in bytes.


|===


[#iops_raw]
[.api-collapsible-fifth-title]
iops_raw

The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#latency_raw]
[.api-collapsible-fifth-title]
latency_raw

The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#cloud]
[.api-collapsible-fifth-title]
cloud

These are raw performance numbers (IOPS and latency) for the cloud store. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster. These numbers are relevant only for volumes hosted on FabricPools.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#flexcache_raw]
[.api-collapsible-fifth-title]
flexcache_raw

Performance numbers for FlexCache used to measure cache effectiveness.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cache_miss_blocks
|integer
a|Blocks retrieved from origin in case of a cache miss. This can be divided by the raw client_requested_blocks and multiplied by 100 to calculate the cache miss percentage.


|client_requested_blocks
|integer
a|Total blocks requested by the client.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#throughput_raw]
[.api-collapsible-fifth-title]
throughput_raw

Throughput bytes observed at the storage object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|other
|integer
a|Performance metric for other I/O operations. Other I/O operations can be metadata operations, such as directory lookups and so on.


|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

These are raw performance numbers, such as IOPS latency and throughput. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cloud
|link:#cloud[cloud]
a|These are raw performance numbers (IOPS and latency) for the cloud store. These numbers are aggregated across all nodes in the cluster and increase with the uptime of the cluster. These numbers are relevant only for volumes hosted on FabricPools.


|flexcache_raw
|link:#flexcache_raw[flexcache_raw]
a|Performance numbers for FlexCache used to measure cache effectiveness.


|iops_raw
|link:#iops_raw[iops_raw]
a|The number of I/O operations observed at the storage object. This can be used along with delta time to calculate the rate of I/O operations per unit of time.


|latency_raw
|link:#latency_raw[latency_raw]
a|The raw latency in microseconds observed at the storage object. This can be divided by the raw IOPS value to calculate the average latency per I/O operation.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "Inconsistent_ delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "Inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the storage object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

SVM containing the volume. Required on POST.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#tiering]
[.api-collapsible-fifth-title]
tiering

[cols=3*,options=header]
|===
|Name
|Type
|Description

|min_cooling_days
|integer
a|This parameter specifies the minimum number of days that user data blocks of the volume must be cooled before they can be considered cold and tiered out to the cloud tier. Note that this parameter is only used for tiering purposes and does not affect the reporting of inactive data. The value specified should be greater than the frequency with which applications in the volume shift between different sets of data. This parameter cannot be set when volume tiering policy is either "none" or "all". The default value of this parameter depends on the volume's tiering policy. See the tiering policy section of this documentation for corresponding default values. If the tiering policy on the volume gets changed, then this parameter will be reset to the default value corresponding to the new tiering policy.


|object_tags
|array[string]
a|This parameter specifies tags of a volume for objects stored on a FabricPool-enabled aggregate. Each tag is a key,value pair and should be in the format "key=value".


|policy
|string
a|Policy that determines whether the user data blocks of a volume in a FabricPool will be tiered to the cloud store when they become cold. FabricPool combines flash (performance tier) with a cloud store into a single aggregate. Temperature of a volume block increases if it is accessed frequently and decreases when it is not. Valid in POST or PATCH.
all &dash; This policy allows tiering of both Snapshot copies and active file system user data to the cloud store as soon as possible by ignoring the temperature on the volume blocks.
auto &dash; This policy allows tiering of both snapshot and active file system user data to the cloud store
none &dash; Volume blocks will not be tiered to the cloud store.
snapshot_only &dash; This policy allows tiering of only the volume Snapshot copies not associated with the active file system. The default tiering policy is "snapshot-only" for a FlexVol and "none" for a FlexGroup. The default minimum cooling period for the "snapshot-only" tiering policy is 2 days and for the "auto" tiering policy is 31 days.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
