---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-protocols-fpolicy.html'
summary: 'Retrieve an FPolicy configuration'
---

= Retrieve an FPolicy configuration

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/protocols/fpolicy`#

*Introduced In:* 9.6

Retrieves an FPolicy configuration.

== Related ONTAP commands

* `fpolicy show`
* `fpolicy policy show`
* `fpolicy policy scope show`
* `fpolicy policy event show`
* `fpolicy policy external-engine show`

== Learn more

* link:manage_fpolicy_configuration.html[DOC /protocols/fpolicy]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|engines.secondary_servers
|string
|query
|False
a|Filter by engines.secondary_servers


|engines.type
|string
|query
|False
a|Filter by engines.type


|engines.primary_servers
|string
|query
|False
a|Filter by engines.primary_servers


|engines.port
|integer
|query
|False
a|Filter by engines.port


|engines.name
|string
|query
|False
a|Filter by engines.name


|events.file_operations.read
|boolean
|query
|False
a|Filter by events.file_operations.read


|events.file_operations.rename
|boolean
|query
|False
a|Filter by events.file_operations.rename


|events.file_operations.close
|boolean
|query
|False
a|Filter by events.file_operations.close


|events.file_operations.symlink
|boolean
|query
|False
a|Filter by events.file_operations.symlink


|events.file_operations.write
|boolean
|query
|False
a|Filter by events.file_operations.write


|events.file_operations.link
|boolean
|query
|False
a|Filter by events.file_operations.link


|events.file_operations.delete_dir
|boolean
|query
|False
a|Filter by events.file_operations.delete_dir


|events.file_operations.lookup
|boolean
|query
|False
a|Filter by events.file_operations.lookup


|events.file_operations.rename_dir
|boolean
|query
|False
a|Filter by events.file_operations.rename_dir


|events.file_operations.getattr
|boolean
|query
|False
a|Filter by events.file_operations.getattr


|events.file_operations.setattr
|boolean
|query
|False
a|Filter by events.file_operations.setattr


|events.file_operations.create_dir
|boolean
|query
|False
a|Filter by events.file_operations.create_dir


|events.file_operations.delete
|boolean
|query
|False
a|Filter by events.file_operations.delete


|events.file_operations.open
|boolean
|query
|False
a|Filter by events.file_operations.open


|events.file_operations.create
|boolean
|query
|False
a|Filter by events.file_operations.create


|events.protocol
|string
|query
|False
a|Filter by events.protocol


|events.volume_monitoring
|boolean
|query
|False
a|Filter by events.volume_monitoring


|events.filters.setattr_with_access_time_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_access_time_change


|events.filters.setattr_with_sacl_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_sacl_change


|events.filters.setattr_with_size_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_size_change


|events.filters.setattr_with_allocation_size_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_allocation_size_change


|events.filters.setattr_with_modify_time_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_modify_time_change


|events.filters.write_with_size_change
|boolean
|query
|False
a|Filter by events.filters.write_with_size_change


|events.filters.setattr_with_mode_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_mode_change


|events.filters.monitor_ads
|boolean
|query
|False
a|Filter by events.filters.monitor_ads


|events.filters.close_with_modification
|boolean
|query
|False
a|Filter by events.filters.close_with_modification


|events.filters.first_read
|boolean
|query
|False
a|Filter by events.filters.first_read


|events.filters.setattr_with_owner_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_owner_change


|events.filters.first_write
|boolean
|query
|False
a|Filter by events.filters.first_write


|events.filters.setattr_with_creation_time_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_creation_time_change


|events.filters.setattr_with_dacl_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_dacl_change


|events.filters.exclude_directory
|boolean
|query
|False
a|Filter by events.filters.exclude_directory


|events.filters.offline_bit
|boolean
|query
|False
a|Filter by events.filters.offline_bit


|events.filters.open_with_write_intent
|boolean
|query
|False
a|Filter by events.filters.open_with_write_intent


|events.filters.setattr_with_group_change
|boolean
|query
|False
a|Filter by events.filters.setattr_with_group_change


|events.filters.close_without_modification
|boolean
|query
|False
a|Filter by events.filters.close_without_modification


|events.filters.close_with_read
|boolean
|query
|False
a|Filter by events.filters.close_with_read


|events.filters.open_with_delete_intent
|boolean
|query
|False
a|Filter by events.filters.open_with_delete_intent


|events.name
|string
|query
|False
a|Filter by events.name


|policies.enabled
|boolean
|query
|False
a|Filter by policies.enabled


|policies.scope.exclude_volumes
|string
|query
|False
a|Filter by policies.scope.exclude_volumes


|policies.scope.include_export_policies
|string
|query
|False
a|Filter by policies.scope.include_export_policies


|policies.scope.exclude_shares
|string
|query
|False
a|Filter by policies.scope.exclude_shares


|policies.scope.include_volumes
|string
|query
|False
a|Filter by policies.scope.include_volumes


|policies.scope.include_extension
|string
|query
|False
a|Filter by policies.scope.include_extension


|policies.scope.exclude_extension
|string
|query
|False
a|Filter by policies.scope.exclude_extension


|policies.scope.exclude_export_policies
|string
|query
|False
a|Filter by policies.scope.exclude_export_policies


|policies.scope.include_shares
|string
|query
|False
a|Filter by policies.scope.include_shares


|policies.priority
|integer
|query
|False
a|Filter by policies.priority


|policies.events.name
|string
|query
|False
a|Filter by policies.events.name


|policies.engine.name
|string
|query
|False
a|Filter by policies.engine.name


|policies.mandatory
|boolean
|query
|False
a|Filter by policies.mandatory


|policies.name
|string
|query
|False
a|Filter by policies.name


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#fpolicy[fpolicy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "engines": [
        {
          "name": "fp_ex_eng",
          "port": "9876",
          "primary_servers": [
            "10.132.145.20",
            "10.140.101.109"
          ],
          "secondary_servers": [
            "10.132.145.20",
            "10.132.145.21"
          ],
          "type": "string"
        }
      ],
      "events": [
        {
          "name": "event_nfs_close",
          "protocol": "string"
        }
      ],
      "policies": [
        {
          "engine": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "string"
          },
          "events": [
            "event_nfs_close",
            "event_open"
          ],
          "name": "fp_policy_1",
          "scope": {
            "exclude_export_policies": [
              "string"
            ],
            "exclude_extension": [
              "string"
            ],
            "exclude_shares": [
              "string"
            ],
            "exclude_volumes": [
              "vol1",
              "vol_svm1",
              "*"
            ],
            "include_export_policies": [
              "string"
            ],
            "include_extension": [
              "string"
            ],
            "include_shares": [
              "sh1",
              "share_cifs"
            ],
            "include_volumes": [
              "vol1",
              "vol_svm1"
            ]
          }
        }
      ],
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#fpolicy_engine]
[.api-collapsible-fifth-title]
fpolicy_engine

The engine defines how ONTAP makes and manages connections to external FPolicy servers.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Specifies the name to assign to the external server configuration.


|port
|integer
a|Port number of the FPolicy server application.


|primary_servers
|array[string]
a|

|secondary_servers
|array[string]
a|

|type
|string
a|The notification mode determines what ONTAP does after sending notifications to FPolicy servers.
The possible values are:

***** synchronous  - After sending a notification, wait for a response from the FPolicy server.

***** asynchronous - After sending a notification, file request processing continues.

* Default value: 1
* enum: ["synchronous", "asynchronous"]
* Introduced in: 9.6


|===


[#file_operations]
[.api-collapsible-fifth-title]
file_operations

Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|close
|boolean
a|File close operations


|create
|boolean
a|File create operations


|create_dir
|boolean
a|Directory create operations


|delete
|boolean
a|File delete operations


|delete_dir
|boolean
a|Directory delete operations


|getattr
|boolean
a|Get attribute operations


|link
|boolean
a|Link operations


|lookup
|boolean
a|Lookup operations


|open
|boolean
a|File open operations


|read
|boolean
a|File read operations


|rename
|boolean
a|File rename operations


|rename_dir
|boolean
a|Directory rename operations


|setattr
|boolean
a|Set attribute operations


|symlink
|boolean
a|Symbolic link operations


|write
|boolean
a|File write operations


|===


[#filters]
[.api-collapsible-fifth-title]
filters

Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|close_with_modification
|boolean
a|Filter the client request for close with modification.


|close_with_read
|boolean
a|Filter the client request for close with read.


|close_without_modification
|boolean
a|Filter the client request for close without modification.


|exclude_directory
|boolean
a|Filter the client requests for directory operations. When this filter is specified directory operations are not monitored.


|first_read
|boolean
a|Filter the client requests for the first-read.


|first_write
|boolean
a|Filter the client requests for the first-write.


|monitor_ads
|boolean
a|Filter the client request for alternate data stream.


|offline_bit
|boolean
a|Filter the client request for offline bit set. FPolicy server receives notification only when offline files are accessed.


|open_with_delete_intent
|boolean
a|Filter the client request for open with delete intent.


|open_with_write_intent
|boolean
a|Filter the client request for open with write intent.


|setattr_with_access_time_change
|boolean
a|Filter the client setattr requests for changing the access time of a file or directory.


|setattr_with_allocation_size_change
|boolean
a|Filter the client setattr requests for changing the allocation size of a file.


|setattr_with_creation_time_change
|boolean
a|Filter the client setattr requests for changing the creation time of a file or directory.


|setattr_with_dacl_change
|boolean
a|Filter the client setattr requests for changing dacl on a file or directory.


|setattr_with_group_change
|boolean
a|Filter the client setattr requests for changing group of a file or directory.


|setattr_with_mode_change
|boolean
a|Filter the client setattr requests for changing the mode bits on a file or directory.


|setattr_with_modify_time_change
|boolean
a|Filter the client setattr requests for changing the modification time of a file or directory.


|setattr_with_owner_change
|boolean
a|Filter the client setattr requests for changing owner of a file or directory.


|setattr_with_sacl_change
|boolean
a|Filter the client setattr requests for changing sacl on a file or directory.


|setattr_with_size_change
|boolean
a|Filter the client setattr requests for changing the size of a file.


|write_with_size_change
|boolean
a|Filter the client request for write with size change.


|===


[#fpolicy_event]
[.api-collapsible-fifth-title]
fpolicy_event

The information that a FPolicy process needs to determine what file access operations to monitor and for which of the monitored events notifications should be sent to the external FPolicy server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|file_operations
|link:#file_operations[file_operations]
a|Specifies the file operations for the FPolicy event. You must specify a valid protocol in the protocol parameter.
The event will check the operations specified from all client requests using the protocol.


|filters
|link:#filters[filters]
a|Specifies the list of filters for a given file operation for the specified protocol.
When you specify the filters, you must specify the valid protocols and a valid file operations.


|name
|string
a|Specifies the name of the FPolicy event.


|protocol
|string
a|Protocol for which event is created. If you specify protocol, then you
must also specify a valid value for the file operation parameters.
The value of this parameter must be one of the following:

***** cifs  - for the CIFS protocol.

***** nfsv3 - for the NFSv3 protocol.

***** nfsv4 - for the NFSv4 protocol.


|volume_monitoring
|boolean
a|Specifies whether volume operation monitoring is required.


|===


[#fpolicy_engine_reference]
[.api-collapsible-fifth-title]
fpolicy_engine_reference

FPolicy external engine


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the FPolicy external engine.


|===


[#fpolicy_event_reference]
[.api-collapsible-fifth-title]
fpolicy_event_reference

FPolicy events


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|===


[#scope]
[.api-collapsible-fifth-title]
scope

[cols=3*,options=header]
|===
|Name
|Type
|Description

|exclude_export_policies
|array[string]
a|

|exclude_extension
|array[string]
a|

|exclude_shares
|array[string]
a|

|exclude_volumes
|array[string]
a|

|include_export_policies
|array[string]
a|

|include_extension
|array[string]
a|

|include_shares
|array[string]
a|

|include_volumes
|array[string]
a|

|===


[#fpolicy_policy]
[.api-collapsible-fifth-title]
fpolicy_policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Specifies if the policy is enabled on the SVM or not. If no value is
mentioned for this field but priority is set, then this policy will be enabled.


|engine
|link:#fpolicy_engine_reference[fpolicy_engine_reference]
a|FPolicy external engine


|events
|array[link:#fpolicy_event_reference[fpolicy_event_reference]]
a|

|mandatory
|boolean
a|Specifies what action to take on a file access event in a case when all primary and secondary servers are down or no response is received from the FPolicy servers within a given timeout period. When this parameter is set to true, file access events will be denied under these circumstances.


|name
|string
a|Specifies the name of the policy.


|priority
|integer
a|Specifies the priority that is assigned to this policy.


|scope
|link:#scope[scope]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#fpolicy]
[.api-collapsible-fifth-title]
fpolicy

FPolicy is an infrastructure component of ONTAP that enables partner applications connected to your storage systems to monitor and set file access permissions. Every time a client accesses a file from a storage system, based on the configuration of FPolicy, the partner application is notified about file access.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|engines
|array[link:#fpolicy_engine[fpolicy_engine]]
a|

|events
|array[link:#fpolicy_event[fpolicy_event]]
a|

|policies
|array[link:#fpolicy_policy[fpolicy_policy]]
a|

|svm
|link:#svm[svm]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
