---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-snapmirror-policies.html'
summary: 'Retrieve SnapMirror async and sync policy types'
---

= Retrieve SnapMirror async and sync policy types

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/snapmirror/policies`#

*Introduced In:* 9.6

Retrieves SnapMirror policies of type "async" and "sync".

== Related ONTAP commands

* `snapmirror policy show`

== Example

The following example shows how to retrieve a collection of SnapMirror policies.

----
GET "/api/snapmirror/policies"
----

== Learn more

* link:manage_snapmirror_policies.html[DOC /snapmirror/policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|scope
|string
|query
|False
a|Filter by scope


|sync_type
|string
|query
|False
a|Filter by sync_type


|copy_latest_source_snapshot
|boolean
|query
|False
a|Filter by copy_latest_source_snapshot

* Introduced in: 9.9


|network_compression_enabled
|boolean
|query
|False
a|Filter by network_compression_enabled


|identity_preservation
|string
|query
|False
a|Filter by identity_preservation


|uuid
|string
|query
|False
a|Filter by uuid


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|svm.name
|string
|query
|False
a|Filter by svm.name


|comment
|string
|query
|False
a|Filter by comment


|transfer_schedule.uuid
|string
|query
|False
a|Filter by transfer_schedule.uuid


|transfer_schedule.name
|string
|query
|False
a|Filter by transfer_schedule.name


|copy_all_source_snapshots
|boolean
|query
|False
a|Filter by copy_all_source_snapshots

* Introduced in: 9.9


|sync_common_snapshot_schedule.uuid
|string
|query
|False
a|Filter by sync_common_snapshot_schedule.uuid


|sync_common_snapshot_schedule.name
|string
|query
|False
a|Filter by sync_common_snapshot_schedule.name


|name
|string
|query
|False
a|Filter by name


|throttle
|integer
|query
|False
a|Filter by throttle


|create_snapshot_on_source
|boolean
|query
|False
a|Filter by create_snapshot_on_source

* Introduced in: 9.9


|retention.count
|integer
|query
|False
a|Filter by retention.count


|retention.label
|string
|query
|False
a|Filter by retention.label


|retention.creation_schedule.uuid
|string
|query
|False
a|Filter by retention.creation_schedule.uuid


|retention.creation_schedule.name
|string
|query
|False
a|Filter by retention.creation_schedule.name


|retention.prefix
|string
|query
|False
a|Filter by retention.prefix


|type
|string
|query
|False
a|Filter by type


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|num_records
|integer
a|Number of records


|records
|array[link:#snapmirror_policy[snapmirror_policy]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "comment": "string",
      "copy_all_source_snapshots": 1,
      "copy_latest_source_snapshot": 1,
      "create_snapshot_on_source": "",
      "identity_preservation": "string",
      "name": "Asynchronous",
      "retention": [
        {
          "count": "7",
          "creation_schedule": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "weekly",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "label": "hourly",
          "prefix": "string"
        }
      ],
      "scope": "string",
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "sync_common_snapshot_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "sync_type": "string",
      "throttle": 0,
      "transfer_schedule": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "type": "string",
      "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 13303842
| SnapMirror policy is not supported.
|===



[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#error[error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#creation_schedule]
[.api-collapsible-fifth-title]
creation_schedule

Schedule used to create Snapshot copies on the destination for long term retention.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy_rule]
[.api-collapsible-fifth-title]
snapmirror_policy_rule

SnapMirror policy rule for retention.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of Snapshot copies to be kept for retention.


|creation_schedule
|link:#creation_schedule[creation_schedule]
a|Schedule used to create Snapshot copies on the destination for long term retention.


|label
|string
a|Snapshot copy label


|prefix
|string
a|Specifies the prefix for the Snapshot copy name to be created as per the schedule. If no value is specified, then the label is used as the prefix.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#sync_common_snapshot_schedule]
[.api-collapsible-fifth-title]
sync_common_snapshot_schedule

Schedule used to create common Snapshot copies for synchronous relationships.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

The schedule used to update asynchronous relationships.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy]
[.api-collapsible-fifth-title]
snapmirror_policy

SnapMirror policy information. SnapMirror policy can either be of type "async" or "sync".
The policy type "async" can be associated with a SnapMirror relationship that has either the FlexVol volume or FlexGroup volume or SVM as the endpoint.
The policy type "sync" along with "sync_type" as "sync" or "strict_sync" can be associated with a SnapMirror relationship that has FlexVol volume as the endpoint. The policy type "sync" can have a "sync_type" of either "sync", "strict_sync" or "automated_failover". If the "sync_type" is "sync" then a write success is returned to the client after writing the data to the source endpoint and before writing the data to the destination endpoint. If the "sync_type" is "strict_sync" then a write success is returned to the client after writing the data to the both source and destination endpoints.
If the "sync_type" is "automated_failover" then the policy can be associated with a SnapMirror relationship that has Consistency Group as the endpoint. Use the "sync" policy with "sync_type" as "automated_failover" to establish SnapMirror relationships for business continuity usecases. SnapMirror relationships with policy type as "sync" and "sync_type" as "automated_failover" can be monitored by the Mediator, if configured. In case the source Consistency Group endpoint is not reachable, the Mediator may trigger a failover to the destination Consistency Group endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|comment
|string
a|Comment associated with the policy.


|copy_all_source_snapshots
|boolean
a|Specifies that all the source Snapshot copies (including the one created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|copy_latest_source_snapshot
|boolean
a|Specifies that the latest source Snapshot copy (created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|create_snapshot_on_source
|boolean
a|Specifies whether a new Snapshot copy should be created on the source at the beginning of an update or resync operation. This is applicable only to async policies. Property can only be set to 'false'.


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type.


|name
|string
a|Name of the policy.


|network_compression_enabled
|boolean
a|Specifies whether network compression is enabled for transfers. This is applicable only to the policies of type "async".


|retention
|array[link:#snapmirror_policy_rule[snapmirror_policy_rule]]
a|Policy on Snapshot copy retention.


|scope
|string
a|Set to "svm" for policies owned by an SVM, otherwise set to "cluster".


|svm
|link:#svm[svm]
a|

|sync_common_snapshot_schedule
|link:#sync_common_snapshot_schedule[sync_common_snapshot_schedule]
a|Schedule used to create common Snapshot copies for synchronous relationships.


|sync_type
|string
a|

|throttle
|integer
a|Throttle in KB/s. Default to unlimited.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|The schedule used to update asynchronous relationships.


|type
|string
a|

|uuid
|string
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
