---
sidebar: sidebar
api: true
explorer: false
permalink: 'manage_snapmirror_policies.html'
summary: 'Manage SnapMirror policies'
---

= Manage SnapMirror policies



== Managing SnapMirror policies

This API is used to manage SnapMirror policies of type "async" and "sync". When applied to a SnapMirror relationship, the SnapMirror policy controls the behavior of the relationship and specifies the configuration attributes for that relationship.
The policy type "async" can be associated with a SnapMirror relationship that has either the FlexVol volume or FlexGroup volume or SVM as the endpoint.
The policy type "sync" can be associated with a SnapMirror relationship that has FlexVol volume or a Consistency Group as the endpoint. The policy type "sync" can have a "sync_type" of either "sync", "strict_sync" or "automated_failover". If the "sync_type" is "sync" then a write success is returned to the client after writing the data to the primary endpoint and before writing the data to the secondary endpoint. If the "sync_type" is "strict_sync" then a write success is returned to the client after writing the data to the both primary and secondary endpoints.
The "sync_type" of "automated_failover" can be associated with a SnapMirror relationship that has Consistency Group as the endpoint.<\br>
Mapping of SnapMirror policies from CLI to REST

|===
| CLI | REST

| mirror-vault
| async

| async-mirror w/
| async w/

| all_source_snapshots
| copy_all_source_snapshots

| async-mirror w/o
| async w/

| all_source_snapshots
| copy_latest_source_snapshot

| vault
| async w/

|
| create_snapshot_on_source
|===

|===
| CLI | REST | sync_type

| sync-mirror
| sync
| sync

| strict-sync-mirror
| sync
| strict_sync

| automated-failover
| sync
| automated_failover
|===


