---
sidebar: sidebar
api: true
explorer: false
permalink: 'manage_svms.html'
summary: 'Manage SVMs'
---

= Manage SVMs



== Managing SVMs

Cluster administrators can manage any SVM bound to the cluster. In addition, SVMs can also be managed by their SVM administrators. The SVM administrator manages the SVM resources, such as volumes, protocols and services, depending on the capabilities assigned by the cluster administrator. SVM administrators cannot create, modify, or delete SVMs. The cluster administrator manages SVM create, modify, or delete operations.

While configuring CIFS, you must also configure IP interfaces and DNS. No other protocol configuration is allowed when configuring NVMe. NFS, FCP, CIFS and iSCSI protocols can be configured together.

SVM administrators might have all or some of the following administration capabilities:

. Data access protocol configuration
 Configures data access protocols, such as NFS, CIFS, iSCSI, and Fibre Channel (FC) protocol (Fibre Channel over Ethernet included).
. Services configuration
 Configures services such as LDAP, NIS, and DNS.
. Monitoring SVM
 Monitors jobs, network connections, network interfaces, and SVM health.
. Updating the TLS certificate for this SVM.


