---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-name-services-name-mappings--.html'
summary: 'Update the name mapping configuration for an SVM'
---

= Update the name mapping configuration for an SVM

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/name-services/name-mappings/{svm.uuid}/{direction}/{index}`#

*Introduced In:* 9.6

Updates the name mapping configuration of an SVM. The positions can be swapped by providing the `new_index` property.
Swapping is not allowed for entries that have `client_match` property configured.

== Related ONTAP commands

* `vserver name-mapping insert`
* `vserver name-mapping modify`
* `vserver name-mapping swap`

== Learn more

* link:manage_name_mappings_for_svms.html[DOC /name-services/name-mappings]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|direction
|string
|path
|True
a|Direction


|index
|integer
|path
|True
a|Position of the entry in the list


|new_index
|integer
|query
|False
a|New position of the Index after a swap is completed.

* Introduced in: 9.7


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|client_match
|string
a|Client workstation IP Address which is matched when searching for the pattern.
You can specify the value in any of the following formats:

* As an IPv4 address with a subnet mask expressed as a number of bits; for instance, 10.1.12.0/24
* As an IPv6 address with a subnet mask expressed as a number of bits; for instance, fd20:8b1e:b255:4071::/64
* As an IPv4 address with a network mask; for instance, 10.1.16.0/255.255.255.0
* As a hostname


|pattern
|string
a|Pattern used to match the name while searching for a name that can be used as a replacement. The pattern is a UNIX-style regular expression. Regular expressions are case-insensitive when mapping from Windows to UNIX, and they are case-sensitive for mappings from Kerberos to UNIX and UNIX to Windows.


|replacement
|string
a|The name that is used as a replacement, if the pattern associated with this entry matches.


|svm
|link:#svm[svm]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "client_match": "10.254.101.111/28",
  "pattern": "ENGCIFS_AD_USER",
  "replacement": "unix_user1",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 65798185
| Failed to resolve the specified hostname

| 65798179
| Cannot swap entries because one or both entries have hostname or address configured.

|
| Delete and recreate the new entry at the specified position.
|===

schema:
$ref: "#/definitions/error_response"


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#name_mapping]
[.api-collapsible-fifth-title]
name_mapping

Name mapping is used to map CIFS identities to UNIX identities, Kerberos identities to UNIX identities, and UNIX identities to CIFS identities. It needs this information to obtain user credentials and provide proper file access regardless of whether they are connecting from an NFS client or a CIFS client.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|client_match
|string
a|Client workstation IP Address which is matched when searching for the pattern.
You can specify the value in any of the following formats:

* As an IPv4 address with a subnet mask expressed as a number of bits; for instance, 10.1.12.0/24
* As an IPv6 address with a subnet mask expressed as a number of bits; for instance, fd20:8b1e:b255:4071::/64
* As an IPv4 address with a network mask; for instance, 10.1.16.0/255.255.255.0
* As a hostname


|pattern
|string
a|Pattern used to match the name while searching for a name that can be used as a replacement. The pattern is a UNIX-style regular expression. Regular expressions are case-insensitive when mapping from Windows to UNIX, and they are case-sensitive for mappings from Kerberos to UNIX and UNIX to Windows.


|replacement
|string
a|The name that is used as a replacement, if the pattern associated with this entry matches.


|svm
|link:#svm[svm]
a|

|===


//end collapsible .Definitions block
====
