---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-svm-svms-.html'
summary: 'Update SVM properties'
---

= Update SVM properties

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/svm/svms/{uuid}`#

*Introduced In:* 9.6

Updates one or more of the following properties of an individual SVM: SVM name, SVM default volume language code, SVM comment, and SVM state.

== Related ONTAP commands

* `vserver modify`
* `vserver rename`
* `vserver start`
* `vserver stop`
* `security ssl modify`
* `vserver add-protocols`
* `vserver remove-protocols`

== Examples

. Stops an SVM and updates the "comment" field for an individual SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"state":"stopped", "comment":"This SVM is stopped."}'
----

. Starts an SVM and updates the "comment" field for an individual SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"state":"running", "comment":"This SVM is running."}'
----

. Updates the "language" field for an individual SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"language":"en.UTF-8"}'
----

. Updates the "name" field for an SVM or renames the SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"name":"svm_new"}'
----

. Updates the aggregates for an individual SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"aggregates":{"name":["aggr1","aggr2","aggr3"]}}'
----

. Updates the Snapshot copy policy for an individual SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"snapshot_policy":{"name":"custom1"}}'
----

. Updates the TLS certificate for an individual SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"certificate":{"uuid":"1cd8a442-86d1-11e0-ae1c-123478563412"}}'
----

. Updates the QoS policy for the SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"qos_policy_group":{"name":"qpolicy1"}}'
----

. Allows NFS protocol which was previously disallowed for the SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"nfs":{"enabled":"true"}}'
----

. Updates the max volume limit for the SVM

----
  PATCH "/api/svm/svms/f16f0935-5281-11e8-b94d-005056b46485" '{"max_volumes":"200"}'
----

== Learn more

* link:manage_svms.html[DOC /svm/svms]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|Filter by UUID


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|array[link:#aggregates[aggregates]]
a|List of allowed aggregates for SVM volumes. An administrator is allowed to create volumes on these aggregates.


|aggregates_delegated
|boolean
a|This property is true when the administrator has delegated the aggregates for the SVM volumes.


|certificate
|link:#certificate[certificate]
a|Certificate for incoming TLS connection requests.


|cifs
|link:#cifs[cifs]
a|

|comment
|string
a|Comment


|fc_interfaces
|array[link:#fc_interface_svm[fc_interface_svm]]
a|FC Interface for the SVM


|fcp
|link:#fcp[fcp]
a|

|ip_interfaces
|array[link:#ip_interface_svm[ip_interface_svm]]
a|IP interfaces for the SVM


|iscsi
|link:#iscsi[iscsi]
a|

|language
|string
a|Default volume language code. UTF-8 encoded languages are valid in POST or PATCH. Non UTF-8 language encodings are for backward compatibility and are not valid input for POST and PATCH requests.


|max_volumes
|string
a|This property is used by cluster administrator to specify the limit on maximum number of volumes allowed in the SVM. The value can be either the string "unlimited" or a number.


|name
|string
a|The name of the SVM.


|nfs
|link:#nfs[nfs]
a|

|nsswitch
|link:#nsswitch[nsswitch]
a|Name service switch configuration


|nvme
|link:#nvme[nvme]
a|

|qos_policy
|link:#qos_policy[qos_policy]
a|This optionally specifies which QoS policy group to apply to the Vserver. This policy group defines measurable service level objectives (SLOs) that apply to the storage objects with which the policy group is associated.


|snapmirror
|link:#snapmirror[snapmirror]
a|Specifies attributes for SVM DR protection.


|snapshot_policy
|link:#snapshot_policy[snapshot_policy]
a|This is a reference to the Snapshot copy policy.


|state
|string
a|SVM State


|uuid
|string
a|The unique identifier of the SVM.


|volume_efficiency_policy
|link:#volume_efficiency_policy[volume_efficiency_policy]
a|This is a reference to the volume efficiency policy.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "aggregates": [
    {
      "name": "aggr1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "certificate": {
    "name": "cert1",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "cifs": {
    "enabled": null
  },
  "comment": "string",
  "fc_interfaces": [
    {
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "fcp": {
    "enabled": null
  },
  "ip_interfaces": [
    {
      "services": [
        "data_nfs"
      ],
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "iscsi": {
    "enabled": null
  },
  "language": "c.utf_8",
  "max_volumes": "string",
  "name": "svm1",
  "nfs": {
    "enabled": null
  },
  "nsswitch": {
    "group": [
      "string"
    ],
    "hosts": [
      "string"
    ],
    "namemap": [
      "string"
    ],
    "netgroup": [
      "string"
    ],
    "passwd": [
      "string"
    ]
  },
  "nvme": {
    "enabled": null
  },
  "qos_policy": {
    "max_throughput_iops": "10000",
    "max_throughput_mbps": "500",
    "min_throughput_iops": "2000",
    "min_throughput_mbps": "500",
    "name": "performance",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "snapmirror": {
    "protected_volumes_count": 0
  },
  "snapshot_policy": {
    "name": "default",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "state": "running",
  "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7",
  "volume_efficiency_policy": {
    "name": "default",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error codes | Description

| 13434880
| Failed to modify SVM parameters.

| 13434881
| Failed to rename SVM.

| 13434883
| SVM parameters except name modified successfully.

| 13434885
| Non-UTF8 language(s) not supported.

| 13434886
| Invalid Snapshot copy policy.

| 13434902
| Modification of NSSwitch parameters failed for the SVM.

| 13434906
| Operation not supported for an SVM of type sync-destination.

| 12451843
| Certificate does not exist.

| 13434908
| Invalid SVM name. The name is already in use by another SVM, IPSpace or cluster.

| 13434916
| SVM is in the process of being created. Wait a few minutes, and then try the command again.

| 13434915
| Failed to unlock the SVM because SVM create or delete job is in progress. Wait a few minutes, and then try the command again.

| 13434911
| Invalid SVM name. Maximum supported length is 41 if SVM is of type \"sync-source\", otherwise 47.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#aggregates]
[.api-collapsible-fifth-title]
aggregates

Aggregate


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Certificate for incoming TLS connection requests.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Certificate name


|uuid
|string
a|Certificate UUID


|===


[#ad_domain]
[.api-collapsible-fifth-title]
ad_domain
[#cifs]
[.api-collapsible-fifth-title]
cifs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the CIFS service. If it is false, only the cluster administrator can manage the service.


|===


[#dns]
[.api-collapsible-fifth-title]
dns

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domains
|array[string]
a|A list of DNS domains.
Domain names have the following requirements:

* The name must contain only the following characters: A through Z,
a through z, 0 through 9, ".", "-" or "_".
* The first character of each label, delimited by ".", must be one
of the following characters: A through Z or a through z or 0
through 9.
* The last character of each label, delimited by ".", must be one of
the following characters: A through Z, a through z, or 0 through 9.
* The top level domain must contain only the following characters: A
through Z, a through z.
* The system reserves the following names:"all", "local", and "localhost".


|servers
|array[string]
a|The list of IP addresses of the DNS servers. Addresses can be either
IPv4 or IPv6 addresses.


|===


[#node]
[.api-collapsible-fifth-title]
node

The node on which the FC port is located.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the node on which the FC port is located.


|===


[#fc_port_reference]
[.api-collapsible-fifth-title]
fc_port_reference

An FC port is the physical port of an FC adapter on a cluster node that can be connected to an FC network.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the FC port.


|node
|link:#node[node]
a|The node on which the FC port is located.


|uuid
|string
a|The unique identifier of the FC port.


|===


[#location]
[.api-collapsible-fifth-title]
location

The location of the Fibre Channel interface is defined by the location of its port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|port
|link:#fc_port_reference[fc_port_reference]
a|An FC port is the physical port of an FC adapter on a cluster node that can be connected to an FC network.


|===


[#fc_interface_svm]
[.api-collapsible-fifth-title]
fc_interface_svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The unique identifier of the Fibre Channel interface.


|===


[#fcp]
[.api-collapsible-fifth-title]
fcp

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the FCP service. If it is false, only the cluster administrator can manage the service.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information

[#broadcast_domain]
[.api-collapsible-fifth-title]
broadcast_domain

Broadcast domain UUID along with a readable name.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the broadcast domain, scoped to its IPspace


|uuid
|string
a|Broadcast domain UUID


|===


[#home_node]
[.api-collapsible-fifth-title]
home_node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#location]
[.api-collapsible-fifth-title]
location

Home_node is optional.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|broadcast_domain
|link:#broadcast_domain[broadcast_domain]
a|Broadcast domain UUID along with a readable name.


|home_node
|link:#home_node[home_node]
a|

|===


[#ip_interface_svm]
[.api-collapsible-fifth-title]
ip_interface_svm

Interface parameters.  Name and home_node are optional.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|services
|array[string]
a|The services associated with the interface.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#ipspace]
[.api-collapsible-fifth-title]
ipspace

Either the UUID or name may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|IPspace name


|uuid
|string
a|IPspace UUID


|===


[#iscsi]
[.api-collapsible-fifth-title]
iscsi

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the iSCSI service. If it is false, only the cluster administrator can manage the service.


|===


[#ldap]
[.api-collapsible-fifth-title]
ldap

[cols=3*,options=header]
|===
|Name
|Type
|Description

|ad_domain
|string
a|This parameter specifies the name of the Active Directory domain
used to discover LDAP servers for use by this client.
This is mutually exclusive with `servers` during POST.


|base_dn
|string
a|Specifies the default base DN for all searches.


|bind_dn
|string
a|Specifies the user that binds to the LDAP servers. SVM API supports anonymous binding. For Simple and SASL LDAP binding, use the LDAP API endpoint.


|enabled
|boolean
a|Enable LDAP? Setting to true creates a configuration if not already created.


|servers
|array[string]
a|

|===


[#nfs]
[.api-collapsible-fifth-title]
nfs

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the NFS service. If it is false, only the cluster administrator can manage the service.


|===


[#nis]
[.api-collapsible-fifth-title]
nis

[cols=3*,options=header]
|===
|Name
|Type
|Description

|domain
|string
a|The NIS domain to which this configuration belongs.


|enabled
|boolean
a|Enable NIS? Setting to true creates a configuration if not already created.


|servers
|array[string]
a|A list of hostnames or IP addresses of NIS servers used
by the NIS domain configuration.


|===


[#nsswitch]
[.api-collapsible-fifth-title]
nsswitch

Name service switch configuration


[cols=3*,options=header]
|===
|Name
|Type
|Description

|group
|array[string]
a|Group sources


|hosts
|array[string]
a|Host sources


|namemap
|array[string]
a|NameMap sources


|netgroup
|array[string]
a|NetGroup sources


|passwd
|array[string]
a|Password sources


|===


[#nvme]
[.api-collapsible-fifth-title]
nvme

[cols=3*,options=header]
|===
|Name
|Type
|Description

|allowed
|boolean
a|If this is set to true, an SVM administrator can manage the NVMe service. If it is false, only the cluster administrator can manage the service.


|===


[#qos_policy]
[.api-collapsible-fifth-title]
qos_policy

This optionally specifies which QoS policy group to apply to the Vserver. This policy group defines measurable service level objectives (SLOs) that apply to the storage objects with which the policy group is associated.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|max_throughput_iops
|integer
a|Specifies the maximum throughput in IOPS, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|max_throughput_mbps
|integer
a|Specifies the maximum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|min_throughput_iops
|integer
a|Specifies the minimum throughput in IOPS, 0 means none. Setting "min_throughput" is supported on AFF platforms only, unless FabricPool tiering policies are set. This is mutually exclusive with name and UUID during POST and PATCH.


|min_throughput_mbps
|integer
a|Specifies the minimum throughput in Megabytes per sec, 0 means none. This is mutually exclusive with name and UUID during POST and PATCH.


|name
|string
a|The QoS policy group name. This is mutually exclusive with UUID and other QoS attributes during POST and PATCH.


|uuid
|string
a|The QoS policy group UUID. This is mutually exclusive with name and other QoS attributes during POST and PATCH.


|===


[#ip_info]
[.api-collapsible-fifth-title]
ip_info

IP information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always netmask length.


|===


[#network_route_for_svm]
[.api-collapsible-fifth-title]
network_route_for_svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination
|link:#ip_info[ip_info]
a|IP information


|gateway
|string
a|The IP address of the gateway router leading to the destination.


|===


[#certificate]
[.api-collapsible-fifth-title]
certificate

Specifies the certificate that will be used for creating HTTPS connections to the S3 server.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Certificate name


|uuid
|string
a|Certificate UUID


|===


[#s3]
[.api-collapsible-fifth-title]
s3

[cols=3*,options=header]
|===
|Name
|Type
|Description

|certificate
|link:#certificate[certificate]
a|Specifies the certificate that will be used for creating HTTPS connections to the S3 server.


|enabled
|boolean
a|Specifies whether or not to enable S3. Setting this value to true creates a service if one is not yet created.


|is_http_enabled
|boolean
a|Specifies whether HTTP is enabled on the S3 server. By default, HTTP is disabled on the S3 server.


|is_https_enabled
|boolean
a|Specifies whether HTTPS is enabled on the S3 server. By default, HTTPS is enabled on the S3 server.


|name
|string
a|Specifies the name of the S3 server. A server name length can range from 1 to 253 characters and can only contain the following combination of characters 0-9, A-Z, a-z, ".", and "-".


|port
|integer
a|Specifies the HTTP listener port for the S3 server. By default, HTTP is enabled on port 80.


|secure_port
|integer
a|Specifies the HTTPS listener port for the S3 server. By default, HTTPS is enabled on port 443.


|===


[#snapmirror]
[.api-collapsible-fifth-title]
snapmirror

Specifies attributes for SVM DR protection.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|is_protected
|boolean
a|Specifies whether the SVM is a SnapMirror source SVM, using SnapMirror to protect its data.


|protected_volumes_count
|integer
a|Specifies the number of SVM DR protected volumes in the SVM.


|===


[#snapshot_policy]
[.api-collapsible-fifth-title]
snapshot_policy

This is a reference to the Snapshot copy policy.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#volume_efficiency_policy]
[.api-collapsible-fifth-title]
volume_efficiency_policy

This is a reference to the volume efficiency policy.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the volume efficiency policy


|uuid
|string
a|Unique identifier of the volume efficiency policy.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|aggregates
|array[link:#aggregates[aggregates]]
a|List of allowed aggregates for SVM volumes. An administrator is allowed to create volumes on these aggregates.


|aggregates_delegated
|boolean
a|This property is true when the administrator has delegated the aggregates for the SVM volumes.


|certificate
|link:#certificate[certificate]
a|Certificate for incoming TLS connection requests.


|cifs
|link:#cifs[cifs]
a|

|comment
|string
a|Comment


|fc_interfaces
|array[link:#fc_interface_svm[fc_interface_svm]]
a|FC Interface for the SVM


|fcp
|link:#fcp[fcp]
a|

|ip_interfaces
|array[link:#ip_interface_svm[ip_interface_svm]]
a|IP interfaces for the SVM


|iscsi
|link:#iscsi[iscsi]
a|

|language
|string
a|Default volume language code. UTF-8 encoded languages are valid in POST or PATCH. Non UTF-8 language encodings are for backward compatibility and are not valid input for POST and PATCH requests.


|max_volumes
|string
a|This property is used by cluster administrator to specify the limit on maximum number of volumes allowed in the SVM. The value can be either the string "unlimited" or a number.


|name
|string
a|The name of the SVM.


|nfs
|link:#nfs[nfs]
a|

|nsswitch
|link:#nsswitch[nsswitch]
a|Name service switch configuration


|nvme
|link:#nvme[nvme]
a|

|qos_policy
|link:#qos_policy[qos_policy]
a|This optionally specifies which QoS policy group to apply to the Vserver. This policy group defines measurable service level objectives (SLOs) that apply to the storage objects with which the policy group is associated.


|snapmirror
|link:#snapmirror[snapmirror]
a|Specifies attributes for SVM DR protection.


|snapshot_policy
|link:#snapshot_policy[snapshot_policy]
a|This is a reference to the Snapshot copy policy.


|state
|string
a|SVM State


|uuid
|string
a|The unique identifier of the SVM.


|volume_efficiency_policy
|link:#volume_efficiency_policy[volume_efficiency_policy]
a|This is a reference to the volume efficiency policy.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
