---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-storage-flexcache-origins-.html'
summary: 'Modify origin options for a FlexCache origin volume in the cluster'
---

= Modify origin options for a FlexCache origin volume in the cluster

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/storage/flexcache/origins/{uuid}`#

*Introduced In:* 9.9

Modifies origin options for a origin volume in the cluster.

== Required properties

* `uuid` - Origin volume UUID.
* `block_level_invalidation` - Value for the Block Level Invalidation flag - options {true\|false}.

== Related ONTAP commands

* `volume flexcache origin config modify`

== Learn more

* link:manage_storage_flexcache_origin_volumes.html[DOC /storage/flexcache/origins]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|Unique identifier of the origin of the FlexCache volume.

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|block_level_invalidation
|boolean
a|Block level invalidation enables the FlexCache volume to retain blocks that are not changed at the FlexCache volume without having to evict them. This means that the FlexCache volume does not have to again incur the cost of fetching blocks over the WAN from the FlexCache volume origin on the next client access. Block level invalidation is a property of the origin volume. Without block level invalidation, any write at the origin volume would evict the whole file at the FlexCache volume, since by default, origin volume does a file level invalidation.


|name
|string
a|Origin volume name


|uuid
|string
a|Origin volume UUID. Unique identifier for origin of FlexCache.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "global_file_locking_enabled": null,
  "name": "vol1, vol_2",
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563512"
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 66846870
| Either origin volume uuid or BLI option value is missing

| 66847020
| Failed to get origin volume details using volume uuid

| 66847021
| Failed to modify origin volume options
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6


|===


[#flexcache_relationship]
[.api-collapsible-fifth-title]
flexcache_relationship

[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster
|link:#cluster[cluster]
a|

|create_time
|string
a|Creation time of the relationship.


|ip_address
|string
a|Cluster managerment IP of the remote cluster.


|size
|integer
a|Size of the remote volume.


|state
|string
a|Volume state


|volume
|link:#volume[volume]
a|

|===


[#svm]
[.api-collapsible-fifth-title]
svm

Origin volume SVM


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#flexcache_origin]
[.api-collapsible-fifth-title]
flexcache_origin

Defines the origin endpoint of FlexCache.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|block_level_invalidation
|boolean
a|Block level invalidation enables the FlexCache volume to retain blocks that are not changed at the FlexCache volume without having to evict them. This means that the FlexCache volume does not have to again incur the cost of fetching blocks over the WAN from the FlexCache volume origin on the next client access. Block level invalidation is a property of the origin volume. Without block level invalidation, any write at the origin volume would evict the whole file at the FlexCache volume, since by default, origin volume does a file level invalidation.


|name
|string
a|Origin volume name


|uuid
|string
a|Origin volume UUID. Unique identifier for origin of FlexCache.


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
