---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-network-ethernet-ports-.html'
summary: 'Update a port'
---

= Update a port

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/network/ethernet/ports/{uuid}`#

*Introduced In:* 9.6

Updates a port.

== Related ONTAP commands

* `network port broadcast-domain add-ports`
* `network port broadcast-domain remove-ports`
* `network port ifgrp modify`
* `network port modify`
* `network port vlan modify`
* `network port reachability repair`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|uuid
|string
|path
|True
a|Port UUID

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|broadcast_domain
|link:#broadcast_domain[broadcast_domain]
a|Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


|enabled
|boolean
a|

|lag
|link:#lag[lag]
a|

|mac_address
|string
a|

|mtu
|integer
a|MTU of the port in bytes. Set by broadcast domain.


|name
|string
a|Portname, such as e0a, e1b-100 (VLAN on ethernet), a0c (LAG/ifgrp), a0d-200 (vlan on LAG/ifgrp)


|reachability
|string
a|Reachability status of the port. Enum value "ok" is the only acceptable value for a PATCH request to repair a port.


|reachable_broadcast_domains
|array[link:#reachable_broadcast_domains[reachable_broadcast_domains]]
a|Reachable broadcast domains.


|speed
|integer
a|Link speed in Mbps


|state
|string
a|Operational state of the port.


|uuid
|string
a|Port UUID


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "broadcast_domain": {
    "ipspace": {
      "name": "ipspace1"
    },
    "name": "bd1",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "lag": {
    "active_ports": [
      {
        "name": "e1b",
        "node": {
          "name": "node1"
        },
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      }
    ],
    "member_ports": [
      {
        "name": "e1b",
        "node": {
          "name": "node1"
        },
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      }
    ]
  },
  "mac_address": "01:02:03:04:05:06",
  "mtu": "1500",
  "name": "e1b",
  "reachability": "ok",
  "reachable_broadcast_domains": [
    {
      "ipspace": {
        "name": "ipspace1"
      },
      "name": "bd1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "speed": "1000",
  "state": "string",
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1376361
| Port is already a member of a LAG.

| 1377562
| Port cannot be used because it is currently the home port or current port of an interface.

| 1377563
| Port is already a member of a LAG.

| 1967087
| The specified broadcast domain UUID is not valid.

| 1967088
| The specified broadcast domain name does not exist in the specified IPspace.

| 1967089
| The specified broadcast domain UUID, name and IPspace name do not match.

| 1967094
| The specified LAG member port UUID is not valid.

| 1967095
| The specified LAG member port name and node name combination is not valid.

| 1967096
| The specified node does not match the specified LAG member port node.

| 1967097
| The specified LAG member ports UUID, name, and node name do not match.

| 1967148
| Failure to remove port from broadcast domain.

| 1967149
| Failure to add port to broadcast domain.

| 1967184
| The reachability parameter cannot be patched in the same request as other parameters that might affect the target port's reachability status.

| 1967185
| The port cannot be repaired because the port is deemed as non-repairable.

| 1967186
| Invalid value for the reachability parameter.

| 1967580
| This command is not supported as the effective cluster version is earlier than 9.8.

| 1967582
| The reachability parameter is not supported on this cluster.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#ipspace]
[.api-collapsible-fifth-title]
ipspace

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of the broadcast domain's IPspace


|===


[#broadcast_domain]
[.api-collapsible-fifth-title]
broadcast_domain

Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ipspace
|link:#ipspace[ipspace]
a|

|name
|string
a|Name of the broadcast domain, scoped to its IPspace


|uuid
|string
a|Broadcast domain UUID


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Name of node on which the port is located.


|===


[#active_ports]
[.api-collapsible-fifth-title]
active_ports

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#member_ports]
[.api-collapsible-fifth-title]
member_ports

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#lag]
[.api-collapsible-fifth-title]
lag

[cols=3*,options=header]
|===
|Name
|Type
|Description

|active_ports
|array[link:#active_ports[active_ports]]
a|Active ports of a LAG (ifgrp). (Some member ports may be inactive.)


|member_ports
|array[link:#member_ports[member_ports]]
a|

|===


[#throughput]
[.api-collapsible-fifth-title]
throughput

The rate of throughput bytes per second observed at the port object.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

The most recent sample of I/O metrics for the port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput
|link:#throughput[throughput]
a|The rate of throughput bytes per second observed at the port object.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#reachable_broadcast_domains]
[.api-collapsible-fifth-title]
reachable_broadcast_domains

Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ipspace
|link:#ipspace[ipspace]
a|

|name
|string
a|Name of the broadcast domain, scoped to its IPspace


|uuid
|string
a|Broadcast domain UUID


|===


[#receive_raw]
[.api-collapsible-fifth-title]
receive_raw

Packet receive counters for the Ethernet port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|discards
|integer
a|Total number of discarded packets.


|errors
|integer
a|Number of packet errors.


|packets
|integer
a|Total packet count.


|===


[#transmit_raw]
[.api-collapsible-fifth-title]
transmit_raw

Packet transmit counters for the Ethernet port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|discards
|integer
a|Total number of discarded packets.


|errors
|integer
a|Number of packet errors.


|packets
|integer
a|Total packet count.


|===


[#device]
[.api-collapsible-fifth-title]
device

Device-related counters for the port object. These counters are applicable at the lowest layer of the networking stack. These values can be used to calculate both transmit and receive packet and error rates by comparing two samples taken at different times and calculating the increase in counter value divided by the elapsed time between the two samples.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|link_down_count_raw
|integer
a|The number of link state changes from up to down seen on the device.


|timestamp
|string
a|The timestamp when the device specific counters were collected.


|===


[#throughput_raw]
[.api-collapsible-fifth-title]
throughput_raw

Throughput bytes observed at the port object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|read
|integer
a|Performance metric for read I/O operations.


|total
|integer
a|Performance metric aggregated over all types of I/O operations.


|write
|integer
a|Peformance metric for write I/O operations.


|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

The real time I/O statistics for the port.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|throughput_raw
|link:#throughput_raw[throughput_raw]
a|Throughput bytes observed at the port object. This can be used along with delta time to calculate the rate of throughput bytes per unit of time.


|timestamp
|string
a|The timestamp of the throughput_raw performance data.


|===


[#base_port]
[.api-collapsible-fifth-title]
base_port

Port UUID along with readable names. Either the UUID or both names may be supplied on input.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|node
|link:#node[node]
a|

|uuid
|string
a|

|===


[#vlan]
[.api-collapsible-fifth-title]
vlan

[cols=3*,options=header]
|===
|Name
|Type
|Description

|base_port
|link:#base_port[base_port]
a|Port UUID along with readable names. Either the UUID or both names may be supplied on input.


|tag
|integer
a|VLAN ID


|===


[#port]
[.api-collapsible-fifth-title]
port

[cols=3*,options=header]
|===
|Name
|Type
|Description

|broadcast_domain
|link:#broadcast_domain[broadcast_domain]
a|Broadcast domain UUID along with a readable name. Either the UUID or both names may be provided on input.


|enabled
|boolean
a|

|lag
|link:#lag[lag]
a|

|mac_address
|string
a|

|mtu
|integer
a|MTU of the port in bytes. Set by broadcast domain.


|name
|string
a|Portname, such as e0a, e1b-100 (VLAN on ethernet), a0c (LAG/ifgrp), a0d-200 (vlan on LAG/ifgrp)


|reachability
|string
a|Reachability status of the port. Enum value "ok" is the only acceptable value for a PATCH request to repair a port.


|reachable_broadcast_domains
|array[link:#reachable_broadcast_domains[reachable_broadcast_domains]]
a|Reachable broadcast domains.


|speed
|integer
a|Link speed in Mbps


|state
|string
a|Operational state of the port.


|uuid
|string
a|Port UUID


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
