---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-storage-snaplock-event-retention-policies-.html'
summary: 'Update the retention period of an EBR policy'
---

= Update the retention period of an EBR policy

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/storage/snaplock/event-retention/policies/{policy.name}`#

*Introduced In:* 9.7

Updates the retention period of an Event Based Retention (EBR) policy.

== Related ONTAP commands

* `snaplock event-retention policy modify`

== Example

Updates the retention period of an EBR policy "policy_name":

----
PATCH "/api/storage/snaplock/event-retention/policies/" '{"name": "policy_name","retention_period": "P20Y"}'
----

== Learn more

* link:manage_event_based_retention_policies.html[DOC /storage/snaplock/event-retention/policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|policy.name
|string
|path
|True
a|Name of the retention policy

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Specifies the EBR policy name


|retention_period
|string
a|Specifies the retention period of an event based retention policy. The retention period value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours or minutes. A period specified for years, months and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively. For example "P10Y" represents a duration of 10 years. Similarly, a duration in hours, minutes is represented by "PT+++<num>+++H", "PT+++<num>+++M" respectively. The period string must contain only a single time element i.e. either years, months, days, hours or minutes. A duration which combines different periods is not supported, example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the retention period field also accepts the strings "infinite" and "unspecified".+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|svm
|link:#svm[svm]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "name": "string",
  "retention_period": "P30M",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default, Error
```

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#snaplock_retention_policy]
[.api-collapsible-fifth-title]
snaplock_retention_policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Specifies the EBR policy name


|retention_period
|string
a|Specifies the retention period of an event based retention policy. The retention period value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours or minutes. A period specified for years, months and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively. For example "P10Y" represents a duration of 10 years. Similarly, a duration in hours, minutes is represented by "PT+++<num>+++H", "PT+++<num>+++M" respectively. The period string must contain only a single time element i.e. either years, months, days, hours or minutes. A duration which combines different periods is not supported, example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the retention period field also accepts the strings "infinite" and "unspecified".+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|svm
|link:#svm[svm]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
