---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-storage-snaplock-file-.html'
summary: 'Update the SnapLock retention time of a file'
---

= Update the SnapLock retention time of a file

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/storage/snaplock/file/{volume.uuid}/{path}`#

*Introduced In:* 9.7

Updates the SnapLock retention time of a file or extends the retention time of a WORM file. Input parameter "expiry_time" expects the date in ISO 8601 format, "infinite", or "unspecified".

== Related ONTAP commands

* `volume file retention set`

== Learn more

* link:manage_snaplock_file_retention_time.html[DOC /storage/snaplock/file/{volume.uuid}/\{path}]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|volume.uuid
|string
|path
|True
a|Volume UUID


|path
|string
|path
|True
a|Path of the file in the form "/<dirpath>/<filename>"

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|expiry_time
|string
a|Expiry time of the file in date-time format, "infinite", "indefinite", or "unspecified". An "infinite" retention time indicates that the file will be retained forever. An "unspecified" retention time indicates that the file will be retained forever; however, the retention time of the file can be changed to an absolute value. An "indefinite" retention time indicates that the file is under Legal-Hold.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "expiry_time": "2058-06-04T19:00:00Z"
}
====

== Response

```
Status: 200, Ok
```

== Error

```
Status: Default
```

ONTAP Error Response codes

|===
| Error code | Description

| 14090347
| File path must be in the format "/+++<dir>+++/+++<file path="">+++\"+++</file>++++++</dir>+++

| 14090348
| Invalid Expiry time
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6


|===


[#snaplock_file_retention]
[.api-collapsible-fifth-title]
snaplock_file_retention

[cols=3*,options=header]
|===
|Name
|Type
|Description

|expiry_time
|string
a|Expiry time of the file in date-time format, "infinite", "indefinite", or "unspecified". An "infinite" retention time indicates that the file will be retained forever. An "unspecified" retention time indicates that the file will be retained forever; however, the retention time of the file can be changed to an absolute value. An "indefinite" retention time indicates that the file is under Legal-Hold.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
