---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-cluster-nodes.html'
summary: 'Add a node or nodes to a cluster'
---

= Add a node or nodes to a cluster

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/cluster/nodes`#

*Introduced In:* 9.6

Adds a node or nodes to the cluster.

== Required properties

* `cluster_interface.ip.address`

== Related ONTAP commands

* `cluster add-node`
* `network interface create`
* `storage aggregate auto-provision`
* `system node modify`
* `system service-processor network modify`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|create_recommended_aggregates
|boolean
|query
|False
a|Creates aggregates based on an optimal layout recommended by the system.

* Default value:
* Introduced in: 9.7


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster_interface
|link:#cluster_interface[cluster_interface]
a|The cluster network IP address of the node to be added.


|cluster_interfaces
|array[link:#cluster_interfaces[cluster_interfaces]]
a|

|controller
|link:#controller[controller]
a|Controller information


|date
|string
a|The current or "wall clock" time of the node in ISO-8601 date, time, and time zone format.
The ISO-8601 date and time are localized based on the ONTAP cluster's timezone setting.

* example: 2019-04-17T11:49:26-04:00
* format: date-time
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|ha
|link:#ha[ha]
a|

|location
|string
a|

|management_interface
|link:#management_interface[management_interface]
a|The management interface of the node to be added. The subnet mask is set based on the management interface of the cluster or the managment interfaces of other nodes.


|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|membership
|string
a|Possible values:

* _available_ - A node is detected on the internal cluster network and can be added to the cluster.  Nodes that have a membership of "available" are not returned when a GET request is called when the cluster exists. Provide a query on the "membership" property for _available_ to scan for nodes on the cluster network. Nodes that have a membership of "available" are returned automatically before a cluster is created.
* _joining_ - Joining nodes are in the process of being added to the cluster. The node might be progressing through the steps to become a member or might have failed. The job to add the node or create the cluster provides details on the current progress of the node.
* _member_ - Nodes that are members have successfully joined the cluster.


|metrocluster
|link:#metrocluster[metrocluster]
a|Metrocluster


|model
|string
a|

|name
|string
a|

|nvram
|link:#nvram[nvram]
a|

|owner
|string
a|Owner of the node.


|serial_number
|string
a|

|service_processor
|link:#service_processor[service_processor]
a|

|state
|string
a|State of the node:

* _up_ - Node is up and operational.
* _booting_ - Node is booting up.
* _down_ - Node has stopped or is dumping core.
* _taken_over_ - Node has been taken over by its HA partner and is not yet waiting for giveback.
* _waiting_for_giveback_ - Node has been taken over by its HA partner and is waiting for the HA partner to giveback disks.
* _degraded_ - Node has one or more critical services offline.
* _unknown_ - Node or its HA partner cannot be contacted and there is no information on the node's state.


|storage_configuration
|string
a|The storage configuration in the system. Possible values:

* _mixed_path_
* _single_path_
* _multi_path_
* _quad_path_
* _mixed_path_ha_
* _single_path_ha_
* _multi_path_ha_
* _quad_path_ha_
* _unknown_


|system_id
|string
a|

|system_machine_type
|string
a|OEM system machine type.


|uptime
|integer
a|The total time, in seconds, that the node has been up.


|uuid
|string
a|

|vendor_serial_number
|string
a|OEM vendor serial number.


|vm
|link:#vm[vm]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "cluster_interface": {
    "ip": {
      "address": "10.10.10.7"
    }
  },
  "cluster_interfaces": [
    {
      "name": "lif1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "controller": {
    "board": "System Board XXVIII",
    "cpu": {
      "count": "20",
      "firmware_release": "string",
      "processor": "string"
    },
    "failed_fan": {
      "count": "1",
      "message": {
        "code": "111411207",
        "message": "There are no failed fans."
      }
    },
    "failed_power_supply": {
      "count": "1",
      "message": {
        "code": "111411208",
        "message": "There are no failed power supplies."
      }
    },
    "flash_cache": [
      {
        "capacity": "1024000000000",
        "device_id": "0",
        "firmware_file": "X9170_O000Z6300NVM",
        "firmware_version": "NA05",
        "hardware_revision": "A1",
        "model": "X1970A",
        "part_number": "119-00207",
        "serial_number": "A22P5061550000187",
        "slot": "6-1",
        "state": "string"
      }
    ],
    "frus": [
      {
        "id": "string",
        "state": "string",
        "type": "string"
      }
    ],
    "memory_size": "1024000000",
    "over_temperature": "string"
  },
  "date": "2019-04-17T11:49:26-04:00",
  "ha": {
    "giveback": {
      "failure": {
        "code": "852126",
        "message": "Failed to initiate giveback. Run the \"storage failover show-giveback\" command for more information."
      },
      "state": "failed"
    },
    "partners": [
      {
        "name": "node1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      }
    ],
    "ports": [
      {
        "number": "0",
        "state": "active"
      }
    ],
    "takeover": {
      "failure": {
        "code": "852130",
        "message": "Failed to initiate takeover. Run the \"storage failover show-takeover\" command for more information."
      },
      "state": "failed"
    }
  },
  "location": "rack 2 row 5",
  "management_interface": {
    "ip": {
      "address": "10.10.10.7"
    }
  },
  "management_interfaces": [
    {
      "name": "lif1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ],
  "membership": "string",
  "metrocluster": {
    "ports": [
      {
        "name": "e1b"
      }
    ],
    "type": "string"
  },
  "model": "FAS3070",
  "name": "node-01",
  "nvram": {
    "battery_state": "string",
    "id": 0
  },
  "owner": "Example Corp",
  "serial_number": "4048820-60-9",
  "service_processor": {
    "dhcp_enabled": null,
    "firmware_version": "string",
    "ipv4_interface": {
      "address": "10.10.10.7",
      "gateway": "10.1.1.1",
      "netmask": "24"
    },
    "link_status": "string",
    "mac_address": "string",
    "state": "string"
  },
  "state": "string",
  "storage_configuration": "string",
  "system_id": "0537035403",
  "system_machine_type": "7Y56-CTOWW1",
  "uptime": "300536",
  "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412",
  "vendor_serial_number": "791603000068",
  "vm": {
    "provider_type": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 262245
| The value provided was invalid.

| 1179795
| A node being added is already in the cluster.

| 1179813
| Fields set for one node must be set for all nodes.

| 1179817
| The IP address, subnet mask, and gateway must all be provided for cluster manangement interface.

| 1179818
| The IP address and gateway must be of the same family.

| 1179821
| An IP address and subnet mask conflicts with an existing entry.

| 131727360
| A node cannot be added to the cluster. This is a generic code, see response message for details.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node_setup_ip]
[.api-collapsible-fifth-title]
node_setup_ip

The IP configuration for cluster setup.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|===


[#cluster_interface]
[.api-collapsible-fifth-title]
cluster_interface

The cluster network IP address of the node to be added.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#node_setup_ip[node_setup_ip]
a|The IP configuration for cluster setup.


|===


[#ip]
[.api-collapsible-fifth-title]
ip

IP information

[#cluster_interfaces]
[.api-collapsible-fifth-title]
cluster_interfaces

Network interface


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#cpu]
[.api-collapsible-fifth-title]
cpu

CPU information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of CPUs on the node.


|firmware_release
|string
a|Firmware release number. Defined by the CPU manufacturer.


|processor
|string
a|CPU type on the node.


|===


[#message]
[.api-collapsible-fifth-title]
message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Error code describing the current condition of chassis fans.


|message
|string
a|Message describing the current condition of chassis fans. It is only of use when `failed_fan.count` is not zero.


|===


[#failed_fan]
[.api-collapsible-fifth-title]
failed_fan

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Specifies a count of the number of chassis fans that are not operating within the recommended RPM range.


|message
|link:#message[message]
a|

|===


[#message]
[.api-collapsible-fifth-title]
message

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Error code describing the current condition of power supply.


|message
|string
a|Message describing the state of any power supplies that are currently degraded. It is only of use when `failed_power_supply.count` is not zero.


|===


[#failed_power_supply]
[.api-collapsible-fifth-title]
failed_power_supply

[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of failed power supply units.


|message
|link:#message[message]
a|

|===


[#flash_cache]
[.api-collapsible-fifth-title]
flash_cache

[cols=3*,options=header]
|===
|Name
|Type
|Description

|capacity
|integer
a|Size in bytes


|device_id
|integer
a|

|firmware_file
|string
a|

|firmware_version
|string
a|

|hardware_revision
|string
a|

|model
|string
a|

|part_number
|string
a|

|serial_number
|string
a|

|slot
|string
a|

|state
|string
a|

|===


[#frus]
[.api-collapsible-fifth-title]
frus

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|string
a|

|state
|string
a|

|type
|string
a|

|===


[#controller]
[.api-collapsible-fifth-title]
controller

Controller information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|board
|string
a|Type of the system board. This is defined by vendor.


|cpu
|link:#cpu[cpu]
a|CPU information.


|failed_fan
|link:#failed_fan[failed_fan]
a|

|failed_power_supply
|link:#failed_power_supply[failed_power_supply]
a|

|flash_cache
|array[link:#flash_cache[flash_cache]]
a|A list of Flash-Cache devices. Only returned when requested by name.


|frus
|array[link:#frus[frus]]
a|List of FRUs on the node. Only returned when requested by name.


|memory_size
|integer
a|Memory available on the node, in bytes.


|over_temperature
|string
a|Specifies whether the hardware is currently operating outside of its recommended temperature range. The hardware shuts down if the temperature exceeds critical thresholds.


|===


[#failure]
[.api-collapsible-fifth-title]
failure

Indicates the failure code and message.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Message code


|message
|string
a|Detailed message based on the state.


|===


[#giveback]
[.api-collapsible-fifth-title]
giveback

Represents the state of the node that is giving storage back to its HA partner.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|failure
|link:#failure[failure]
a|Indicates the failure code and message.


|state
|string
a|

|===


[#partners]
[.api-collapsible-fifth-title]
partners

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#ports]
[.api-collapsible-fifth-title]
ports

[cols=3*,options=header]
|===
|Name
|Type
|Description

|number
|integer
a|HA port number


|state
|string
a|HA port state:

* _down_ - Logical HA link is down.
* _initialized_ - Logical HA link is initialized. The physical link is up, but the subnet manager hasn't started to configure the port.
* _armed_ - Logical HA link is armed. The physical link is up and the subnet manager started but did not yet complete configuring the port.
* _active_ - Logical HA link is active.
* _reserved_ - Logical HA link is active, but the physical link is down.


|===


[#takeover]
[.api-collapsible-fifth-title]
takeover

This represents the state of the node that is taking over storage from its HA partner.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|failure
|link:#failure[failure]
a|Indicates the failure code and message.


|state
|string
a|

|===


[#ha]
[.api-collapsible-fifth-title]
ha

[cols=3*,options=header]
|===
|Name
|Type
|Description

|auto_giveback
|boolean
a|Specifies whether giveback is automatically initiated when the node that owns the storage is ready.


|enabled
|boolean
a|Specifies whether or not storage failover is enabled.


|giveback
|link:#giveback[giveback]
a|Represents the state of the node that is giving storage back to its HA partner.


|partners
|array[link:#partners[partners]]
a|Nodes in this node's High Availability (HA) group.


|ports
|array[link:#ports[ports]]
a|

|takeover
|link:#takeover[takeover]
a|This represents the state of the node that is taking over storage from its HA partner.


|===


[#management_interface]
[.api-collapsible-fifth-title]
management_interface

The management interface of the node to be added. The subnet mask is set based on the management interface of the cluster or the managment interfaces of other nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#node_setup_ip[node_setup_ip]
a|The IP configuration for cluster setup.


|===


[#management_interfaces]
[.api-collapsible-fifth-title]
management_interfaces

Network interface


[cols=3*,options=header]
|===
|Name
|Type
|Description

|ip
|link:#ip[ip]
a|IP information


|name
|string
a|The name of the interface.


|uuid
|string
a|The UUID that uniquely identifies the interface.


|===


[#metric]
[.api-collapsible-fifth-title]
metric

CPU performance for the nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|duration
|string
a|The duration over which this sample is calculated. The time durations are represented in the ISO-8601 standard format. Samples can be calculated over the following durations:


|processor_utilization
|integer
a|Average CPU Utilization for the node


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#ports]
[.api-collapsible-fifth-title]
ports

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|===


[#metrocluster]
[.api-collapsible-fifth-title]
metrocluster

Metrocluster


[cols=3*,options=header]
|===
|Name
|Type
|Description

|custom_vlan_capable
|boolean
a|Indicates whether the MetroCluster over IP platform supports custom VLAN IDs.


|ports
|array[link:#ports[ports]]
a|MetroCluster over IP ports.


|type
|string
a|The Metrocluster configuration type


|===


[#nvram]
[.api-collapsible-fifth-title]
nvram

[cols=3*,options=header]
|===
|Name
|Type
|Description

|battery_state
|string
a|Specifies status of the NVRAM battery. Possible values:

* _battery_ok_
* _battery_partially_discharged_
* _battery_fully_discharged_
* _battery_not_present_
* _battery_near_end_of_life_
* _battery_at_end_of_life_
* _battery_unknown_
* _battery_over_charged_
* _battery_fully_charged_


|id
|integer
a|Vendor specific NVRAM ID of the node.


|===


[#ipv4_interface]
[.api-collapsible-fifth-title]
ipv4_interface

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv4 or IPv6 address


|gateway
|string
a|The IPv4 or IPv6 address of the default router.


|netmask
|string
a|Input as netmask length (16) or IPv4 mask (255.255.0.0). For IPv6, the default value is 64 with a valid range of 1 to 127. Output is always netmask length.


|===


[#ipv6_interface]
[.api-collapsible-fifth-title]
ipv6_interface

Object to setup an interface along with its default router.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|address
|string
a|IPv6 address


|gateway
|string
a|The IPv6 address of the default router.


|netmask
|integer
a|The IPv6 netmask/prefix length. The default value is 64 with a valid range of 1 to 127.


|===


[#service_processor]
[.api-collapsible-fifth-title]
service_processor

[cols=3*,options=header]
|===
|Name
|Type
|Description

|firmware_version
|string
a|The version of firmware installed.


|ipv4_interface
|link:#ipv4_interface[ipv4_interface]
a|Object to setup an interface along with its default router.


|link_status
|string
a|

|mac_address
|string
a|

|state
|string
a|

|===


[#statistics]
[.api-collapsible-fifth-title]
statistics

Raw CPU performance for the nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|processor_utilization_base
|integer
a|Base counter for CPU Utilization.


|processor_utilization_raw
|integer
a|Raw CPU Utilization for the node. This should be divided by the processor_utilization_base to calculate the percentage CPU utilization for the node.


|status
|string
a|Errors associated with the sample. For example, if the aggregation of data over multiple nodes fails, then any partial errors might return "ok" on success or "error" on an internal uncategorized failure. Whenever a sample collection is missed but done at a later time, it is back filled to the previous 15 second timestamp and tagged with "backfilled_data". "inconsistent_delta_time" is encountered when the time between two collections is not the same for all nodes. Therefore, the aggregated value might be over or under inflated. "Negative_delta" is returned when an expected monotonically increasing value has decreased in value. "inconsistent_old_data" is returned when one or more nodes do not have the latest data.


|timestamp
|string
a|The timestamp of the performance data.


|===


[#version]
[.api-collapsible-fifth-title]
version

This returns the cluster version information.  When the cluster has more than one node, the cluster version is equivalent to the lowest of generation, major, and minor versions on all nodes.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|full
|string
a|The full cluster version string.


|generation
|integer
a|The generation portion of the version.


|major
|integer
a|The major portion of the version.


|minor
|integer
a|The minor portion of the version.


|===


[#vm]
[.api-collapsible-fifth-title]
vm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|provider_type
|string
a|Cloud provider where the VM is hosted.


|===


[#node]
[.api-collapsible-fifth-title]
node

Complete node information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cluster_interface
|link:#cluster_interface[cluster_interface]
a|The cluster network IP address of the node to be added.


|cluster_interfaces
|array[link:#cluster_interfaces[cluster_interfaces]]
a|

|controller
|link:#controller[controller]
a|Controller information


|date
|string
a|The current or "wall clock" time of the node in ISO-8601 date, time, and time zone format.
The ISO-8601 date and time are localized based on the ONTAP cluster's timezone setting.

* example: 2019-04-17T11:49:26-04:00
* format: date-time
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|ha
|link:#ha[ha]
a|

|location
|string
a|

|management_interface
|link:#management_interface[management_interface]
a|The management interface of the node to be added. The subnet mask is set based on the management interface of the cluster or the managment interfaces of other nodes.


|management_interfaces
|array[link:#management_interfaces[management_interfaces]]
a|

|membership
|string
a|Possible values:

* _available_ - A node is detected on the internal cluster network and can be added to the cluster.  Nodes that have a membership of "available" are not returned when a GET request is called when the cluster exists. Provide a query on the "membership" property for _available_ to scan for nodes on the cluster network. Nodes that have a membership of "available" are returned automatically before a cluster is created.
* _joining_ - Joining nodes are in the process of being added to the cluster. The node might be progressing through the steps to become a member or might have failed. The job to add the node or create the cluster provides details on the current progress of the node.
* _member_ - Nodes that are members have successfully joined the cluster.


|metrocluster
|link:#metrocluster[metrocluster]
a|Metrocluster


|model
|string
a|

|name
|string
a|

|nvram
|link:#nvram[nvram]
a|

|owner
|string
a|Owner of the node.


|serial_number
|string
a|

|service_processor
|link:#service_processor[service_processor]
a|

|state
|string
a|State of the node:

* _up_ - Node is up and operational.
* _booting_ - Node is booting up.
* _down_ - Node has stopped or is dumping core.
* _taken_over_ - Node has been taken over by its HA partner and is not yet waiting for giveback.
* _waiting_for_giveback_ - Node has been taken over by its HA partner and is waiting for the HA partner to giveback disks.
* _degraded_ - Node has one or more critical services offline.
* _unknown_ - Node or its HA partner cannot be contacted and there is no information on the node's state.


|storage_configuration
|string
a|The storage configuration in the system. Possible values:

* _mixed_path_
* _single_path_
* _multi_path_
* _quad_path_
* _mixed_path_ha_
* _single_path_ha_
* _multi_path_ha_
* _quad_path_ha_
* _unknown_


|system_id
|string
a|

|system_machine_type
|string
a|OEM system machine type.


|uptime
|integer
a|The total time, in seconds, that the node has been up.


|uuid
|string
a|

|vendor_serial_number
|string
a|OEM vendor serial number.


|vm
|link:#vm[vm]
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
