---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-cifs-shares.html'
summary: 'Create a CIFS share'
---

= Create a CIFS share

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/cifs/shares`#

*Introduced In:* 9.6

Creates a CIFS share.

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the CIFS share.
* `name` - Name of the CIFS share.
* `path` - Path in the owning SVM namespace that is shared through this share.

== Recommended optional properties

* `comment` - Optionally choose to add a text comment of up to 256 characters about the CIFS share.
* `acls` - Optionally choose to add share permissions that users and groups have on the CIFS share.

== Default property values

If not specified in POST, the following default property values are assigned:

* `home_directory` - _false_
* `oplocks` - _true_
* `access_based_enumeration` - _false_
* `change_notify` - _true_
* `encryption` - _false_
* `unix_symlink` - _local_

== Related ONTAP commands

* `vserver cifs share create`
* `vserver cifs share properties add`
* `vserver cifs share access-control create`

== Learn more

* link:manage_cifs_shares.html[DOC /protocols/cifs/shares]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_based_enumeration
|boolean
a|If enabled, all folders inside this share are visible to a user based on that individual user access right; prevents
the display of folders or other shared resources that the user does not have access to.


|acls
|array[link:#acls[acls]]
a|

|change_notify
|boolean
a|Specifies whether CIFS clients can request for change notifications for directories on this share.


|comment
|string
a|Specify the CIFS share descriptions.


|encryption
|boolean
a|Specifies that SMB encryption must be used when accessing this share. Clients that do not support encryption are not
able to access this share.


|home_directory
|boolean
a|Specifies whether or not the share is a home directory share, where the share and path names are dynamic.
ONTAP home directory functionality automatically offer each user a dynamic share to their home directory without creating an
individual SMB share for each user.
The ONTAP CIFS home directory feature enable us to configure a share that maps to
different directories based on the user that connects to it. Instead of creating a separate shares for each user,
a single share with a home directory parameters can be created.
In a home directory share, ONTAP dynamically generates the share-name and share-path by substituting
%w, %u, and %d variables with the corresponding Windows user name, UNIX user name, and domain name, respectively.

* Default value: 1
* Introduced in: 9.6
* readCreate: 1


|name
|string
a|Specifies the name of the CIFS share that you want to create. If this
is a home directory share then the share name includes the pattern as
%w (Windows user name), %u (UNIX user name) and %d (Windows domain name)
variables in any combination with this parameter to generate shares dynamically.


|no_strict_security
|boolean
a|Specifies whether or not CIFS clients can follow a unix symlinks outside the share boundaries.


|oplocks
|boolean
a|Specify whether opportunistic locks are enabled on this share. "Oplocks" allow clients to lock files and cache content locally,
which can increase performance for file operations.


|path
|string
a|The fully-qualified pathname in the owning SVM namespace that is shared through this share.
If this is a home directory share then the path should be dynamic by specifying the pattern
%w (Windows user name), %u (UNIX user name), or %d (domain name) variables in any combination.
ONTAP generates the path dynamically for the connected user and this path is appended to each
search path to find the full Home Directory path.

* example: /volume_1/eng_vol/
* maxLength: 256
* minLength: 1
* Introduced in: 9.6


|svm
|link:#svm[svm]
a|

|unix_symlink
|string
a|Controls the access of UNIX symbolic links to CIFS clients.
The supported values are:

***** local - Enables only local symbolic links which is within the same CIFS share.

***** widelink - Enables both local symlinks and widelinks.

***** disable - Disables local symlinks and widelinks.


|volume
|link:#volume[volume]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "acls": [
    {
      "permission": "string",
      "type": "string",
      "user_or_group": "ENGDOMAIN\\ad_user"
    }
  ],
  "comment": "HR Department Share",
  "name": "HR_SHARE",
  "path": "/volume_1/eng_vol/",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "unix_symlink": "string",
  "volume": {
    "name": "volume1",
    "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 201, Created
```

== Error

```
Status: Default
```

ONTAP Error Response Codes
//start table
[cols=2*,options=header]
|===
//header
| Error Code | Description
//end header
//end row
//start row
|655628   +
//end row
//start row
|CIFS Share Creation with property 'SMB_ENCRYPTION' failed because the CIFS server does not support SMB3.0
//end row
//start row
|
//end row
//start row
|655551   +
//end row
//start row
|CIFS Share Creation failed because the specified path does not exist
//end row
//start row
|
//end row
//start row
|655577   +
//end row
//start row
|The CIFS share name cannot be more than 80 characters long
//end row
//start row
|
//end row
//start row
|655399   +
//end row
//start row
|Failed to create CIFS share. The CIFS server does not exist for specified SVM
//end row
//start row
|
//end row
//start row
|656422   +
//end row
//start row
|Failed to create the home directory share because the directory shares must specify a path relative to one or more home directory search paths
//end row
//start row
|
//end row
//start row
|656423   +
//end row
//start row
|Failed to create CIFS share. The Shares must define an absolute share path
//end row
//start row
|
//end row
//start row
|656424   +
//end row
//start row
|Failed to create CIFS the administrator share 'c$' because you are not permitted to created any admin shares
//end row
//start row
|
//end row
//start row
|655625   +
//end row
//start row
|Failed to create CIFS share. The Shares path is not a valid file-type for CIFS share
//end row
//start row
|
//end row
//start row
|656426   +
//end row
//start row
|CIFS Share Creation failed because the share name is invalid
//end row
//start row
|
//end row
//start row
|655655   +
//end row
//start row
|no-strict-security should be set to true only if unix_symlink is configured as "local" or "widelink".
//end row
|===
//end table


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#acls]
[.api-collapsible-fifth-title]
acls

The permissions that users and groups have on a CIFS share.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|permission
|string
a|Specifies the access rights that a user or group has on the defined CIFS Share.
The following values are allowed:

* no_access    - User does not have CIFS share access
* read         - User has only read access
* change       - User has change access
* full_control - User has full_control access


|type
|string
a|Specifies the type of the user or group to add to the access control
list of a CIFS share. The following values are allowed:

* windows    - Windows user or group
* unix_user  - UNIX user
* unix_group - UNIX group


|user_or_group
|string
a|Specifies the user or group name to add to the access control list of a CIFS share.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6


|===


[#cifs_share]
[.api-collapsible-fifth-title]
cifs_share

CIFS share is a named access point in a volume. Before users and applications can access data on the CIFS server over SMB,
a CIFS share must be created with sufficient share permission. CIFS shares are tied to the CIFS server on the SVM.
When a CIFS share is created, ONTAP creates a default ACL for the share with Full Control permissions for Everyone.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_based_enumeration
|boolean
a|If enabled, all folders inside this share are visible to a user based on that individual user access right; prevents
the display of folders or other shared resources that the user does not have access to.


|acls
|array[link:#acls[acls]]
a|

|change_notify
|boolean
a|Specifies whether CIFS clients can request for change notifications for directories on this share.


|comment
|string
a|Specify the CIFS share descriptions.


|encryption
|boolean
a|Specifies that SMB encryption must be used when accessing this share. Clients that do not support encryption are not
able to access this share.


|home_directory
|boolean
a|Specifies whether or not the share is a home directory share, where the share and path names are dynamic.
ONTAP home directory functionality automatically offer each user a dynamic share to their home directory without creating an
individual SMB share for each user.
The ONTAP CIFS home directory feature enable us to configure a share that maps to
different directories based on the user that connects to it. Instead of creating a separate shares for each user,
a single share with a home directory parameters can be created.
In a home directory share, ONTAP dynamically generates the share-name and share-path by substituting
%w, %u, and %d variables with the corresponding Windows user name, UNIX user name, and domain name, respectively.

* Default value: 1
* Introduced in: 9.6
* readCreate: 1


|name
|string
a|Specifies the name of the CIFS share that you want to create. If this
is a home directory share then the share name includes the pattern as
%w (Windows user name), %u (UNIX user name) and %d (Windows domain name)
variables in any combination with this parameter to generate shares dynamically.


|no_strict_security
|boolean
a|Specifies whether or not CIFS clients can follow a unix symlinks outside the share boundaries.


|oplocks
|boolean
a|Specify whether opportunistic locks are enabled on this share. "Oplocks" allow clients to lock files and cache content locally,
which can increase performance for file operations.


|path
|string
a|The fully-qualified pathname in the owning SVM namespace that is shared through this share.
If this is a home directory share then the path should be dynamic by specifying the pattern
%w (Windows user name), %u (UNIX user name), or %d (domain name) variables in any combination.
ONTAP generates the path dynamically for the connected user and this path is appended to each
search path to find the full Home Directory path.

* example: /volume_1/eng_vol/
* maxLength: 256
* minLength: 1
* Introduced in: 9.6


|svm
|link:#svm[svm]
a|

|unix_symlink
|string
a|Controls the access of UNIX symbolic links to CIFS clients.
The supported values are:

***** local - Enables only local symbolic links which is within the same CIFS share.

***** widelink - Enables both local symlinks and widelinks.

***** disable - Disables local symlinks and widelinks.


|volume
|link:#volume[volume]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
