---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-file-security-permissions--acl.html'
summary: 'Add a new SACL or DACL ACE'
---

= Add a new SACL or DACL ACE

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/file-security/permissions/{svm.uuid}/{path}/acl`#

*Introduced In:* 9.9

Adds the new SACL/DACL ACL.

== Related ONTAP commands

* `vserver security file-directory ntfs dacl add`
* `vserver security file-directory ntfs sacl add`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|path
|string
|path
|True
a|path


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:


|svm.uuid
|string
|path
|True
a|UUID of the SVM to which this object belongs.

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|string
a|Specifies whether the ACL is for DACL or SACL.
The available values are:

* access_allow                     - DACL for allow access
* access_deny                      - DACL for deny access
* audit_success                    - SACL for success access
* audit_failure                    - SACL for failure access


|advanced_rights
|link:#advanced_rights[advanced_rights]
a|Specifies the advanced access right controlled by the ACE for the account specified.
 You can specify more than one "advanced-rights" value by using a comma-delimited list.


|apply_to
|link:#apply_to[apply_to]
a|Specifies where to apply the DACL or SACL entries.
You can specify more than one value by using a comma-delimited list.


|ignore_paths
|array[string]
a|Specifies that permissions on this file or directory cannot be replaced.


|propagation_mode
|string
a|Specifies how to propagate security settings to child subfolders and files.
This setting determines how child files/folders contained within a parent
folder inherit access control and audit information from the parent folder.
The available values are:

* propogate    - propagate inheritable permissions to all subfolders and files
* replace      - replace existing permissions on all subfolders and files with inheritable permissions


|rights
|string
a|Specifies the access right controlled by the ACE for the account specified.
The "rights" parameter is mutually exclusive with the "advanced_rights"
parameter. If you specify the "rights" parameter, you can specify one
of the following "rights" values:


|user
|string
a|Specifies the account to which the ACE applies.
You can specify either name or SID.


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "access": "access_allow",
  "ignore_paths": [
    "/dir1/dir2/",
    "/parent/dir3"
  ],
  "propagation_mode": "string",
  "rights": "full_control",
  "user": "S-1-5-21-2233347455-2266964949-1780268902-69304"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default, Error
```

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#advanced_rights]
[.api-collapsible-fifth-title]
advanced_rights

Specifies the advanced access right controlled by the ACE for the account specified.
 You can specify more than one "advanced-rights" value by using a comma-delimited list.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|append_data
|boolean
a|Append DAta


|delete
|boolean
a|Delete


|delete_child
|boolean
a|Delete Child


|execute_file
|boolean
a|Execute File


|full_control
|boolean
a|Full Control


|read_attr
|boolean
a|Read Attributes


|read_data
|boolean
a|Read Data


|read_ea
|boolean
a|Read Extended Attributes


|read_perm
|boolean
a|Read Permissions


|synchronize
|boolean
a|Synchronize


|write_attr
|boolean
a|Write Attributes


|write_data
|boolean
a|Write Data


|write_ea
|boolean
a|Write Extended Attributes


|write_owner
|boolean
a|Write Owner


|write_perm
|boolean
a|Write Permission


|===


[#apply_to]
[.api-collapsible-fifth-title]
apply_to

Specifies where to apply the DACL or SACL entries.
You can specify more than one value by using a comma-delimited list.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|files
|boolean
a|Apply to Files


|sub_folders
|boolean
a|Apply to all sub-folders


|this_folder
|boolean
a|Apply only to this folder


|===


[#file_directory_security_acl]
[.api-collapsible-fifth-title]
file_directory_security_acl

Manages the DACLS or SACLS.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|access
|string
a|Specifies whether the ACL is for DACL or SACL.
The available values are:

* access_allow                     - DACL for allow access
* access_deny                      - DACL for deny access
* audit_success                    - SACL for success access
* audit_failure                    - SACL for failure access


|advanced_rights
|link:#advanced_rights[advanced_rights]
a|Specifies the advanced access right controlled by the ACE for the account specified.
 You can specify more than one "advanced-rights" value by using a comma-delimited list.


|apply_to
|link:#apply_to[apply_to]
a|Specifies where to apply the DACL or SACL entries.
You can specify more than one value by using a comma-delimited list.


|ignore_paths
|array[string]
a|Specifies that permissions on this file or directory cannot be replaced.


|propagation_mode
|string
a|Specifies how to propagate security settings to child subfolders and files.
This setting determines how child files/folders contained within a parent
folder inherit access control and audit information from the parent folder.
The available values are:

* propogate    - propagate inheritable permissions to all subfolders and files
* replace      - replace existing permissions on all subfolders and files with inheritable permissions


|rights
|string
a|Specifies the access right controlled by the ACE for the account specified.
The "rights" parameter is mutually exclusive with the "advanced_rights"
parameter. If you specify the "rights" parameter, you can specify one
of the following "rights" values:


|user
|string
a|Specifies the account to which the ACE applies.
You can specify either name or SID.


|===


[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
