---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-snapmirror-policies.html'
summary: 'Create a SnapMirror policy'
---

= Create a SnapMirror policy

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/snapmirror/policies`#

*Introduced In:* 9.6

Creates a SnapMirror policy. The property "identity_preservation" is applicable to only SnapMirror relationships with SVM endpoints and it indicates which configuration of the source SVM is replicated to the destination SVM.

It takes the following values:

* `full` - indicates that the source SVM configuration is replicated to the destination SVM endpoint.
* `exclude_network_config` - indicates that the source SVM configuration other than network configuration is replicated to the destination SVM endpoint.
* `exclude_network_and_protocol_config` - indicates that the source SVM configuration is not replicated to the destination SVM endpoint.

== Important notes

* The property "identity_preservation" is applicable to only SnapMirror relationships with SVM endpoints and it indicates which configuration of the source SVM is replicated to the destination SVM.
* The properties "identity_preservation" and "transfer_schedule" are not applicable for "sync" type policies.
* The properties "copy_all_source_snapshots", "copy_latest_source_snapshot", and "create_snapshot_on_source" are mutually exclusive.
* The properties "copy_all_source_snapshots", "copy_latest_source_snapshot", and "create_snapshot_on_source" are not applicable for "sync" type policies.
* No "retention" properties can be specified if "copy_all_source_snapshots" or 'copy_latest_source_snapshot' is specified.
* The properties "retention.creation_schedule" and "retention.prefix" are not applicable for "sync" type policies.
* The property "retention.creation_schedule" is not applicable for "async" policies with "create_snapshot_on_source" set to "false".
* The property "sync_common_snapshot_schedule" is not applicable for an "async" type policy.
* The property "retention.count" specifies the maximum number of Snapshot copies that are retained on the SnapMirror destination volume.
* When the property "retention.label" is specified, the Snapshot copies that have a SnapMirror label matching this property is transferred to the SnapMirror destination.
* When the property "retention.creation_schedule" is specified, Snapshot copies are directly created on the SnapMirror destination. The Snapshot copies created have the same content as the latest Snapshot copy already present on the SnapMirror destination.
* The property "transfer_schedule" cannot be set to null (no-quotes) during SnapMirror policy POST.

== Required properties

* `name` - Name of the new SnapMirror policy.

== Recommended optional properties

* `svm.name` or `svm.uuid` - Name or UUID of the SVM that owns the SnapMirror policy.

== Default property values

If not specified in POST, the following default property values are assigned:

* `type` - _async_
* `sync_type` - _sync_ (when `type` is _sync_)
* `network_compression_enabled` - _false_
* `throttle` - _0_
* `identity_preservation` - `_exclude_network_and_protocol_config_`

== Related ONTAP commands

* `snapmirror policy create`

== Examples

Creating a SnapMirror policy of type "sync"

----
 POST "/api/snapmirror/policies/" '{"name": "policy1", "svm.name": "VS0", "type": "sync", "sync_type": "sync"}'
----

Creating a SnapMirror policy of type "async" with two sets of retention values, one with a creation_schedule

----
 POST "/api/snapmirror/policies" '{"name": "policy_ret", "svm": {"name": "vs1"}, "retention": [{"label": "weekly", "count": "2", "creation_schedule": {"name": "weekly"}}, {"label":"daily", "count":"7"}]}'
----

Creating a SnapMirror policy of type "async"

----
 POST "/api/snapmirror/policies" '{"name": "newPolicy", "svm":{"name" : "vs1"}, "type": "async"}'
----

Creating a SnapMirror policy of type "async" which replicates all Snapshot copies

----
 POST "/api/snapmirror/policies" '{"name": "newPolicy", "svm":{"name" : "vs1"}, "type": "async", "copy_all_source_snapshots": "true"}'
----

Creating a SnapMirror policy of type "async" which replicates latest Snapshot copy

----
 POST "/api/snapmirror/policies" '{"name": "newPolicy2", "svm":{"name" : "vs1"}, "type": "async", "copy_latest_source_snapshot": "true"}'
----

Creating a SnapMirror policy of type "async" which does not create Snapshot copies on source

----
 POST "/api/snapmirror/policies" '{"name": "newPolicy", "svm":{"name" : "vs1"}, "type": "async", "create_snapshot_on_source": "false", "retention": [{"label": "daily", "count": 7}]}'
----

Creating a SnapMirror policy of type "sync" with sync_type as "automated_failover"

----
 POST "/api/snapmirror/policies/" '{"name": "policy1", "svm.name": "VS0", "type": "sync", "sync_type": "automated_failover" }'
----

== Learn more

* link:manage_snapmirror_policies.html[DOC /snapmirror/policies]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|Comment associated with the policy.


|copy_all_source_snapshots
|boolean
a|Specifies that all the source Snapshot copies (including the one created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|copy_latest_source_snapshot
|boolean
a|Specifies that the latest source Snapshot copy (created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|create_snapshot_on_source
|boolean
a|Specifies whether a new Snapshot copy should be created on the source at the beginning of an update or resync operation. This is applicable only to async policies. Property can only be set to 'false'.


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type.


|name
|string
a|Name of the policy.


|network_compression_enabled
|boolean
a|Specifies whether network compression is enabled for transfers. This is applicable only to the policies of type "async".


|retention
|array[link:#snapmirror_policy_rule[snapmirror_policy_rule]]
a|Policy on Snapshot copy retention.


|scope
|string
a|Set to "svm" for policies owned by an SVM, otherwise set to "cluster".


|svm
|link:#svm[svm]
a|

|sync_common_snapshot_schedule
|link:#sync_common_snapshot_schedule[sync_common_snapshot_schedule]
a|Schedule used to create common Snapshot copies for synchronous relationships.


|sync_type
|string
a|

|throttle
|integer
a|Throttle in KB/s. Default to unlimited.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|The schedule used to update asynchronous relationships.


|type
|string
a|

|uuid
|string
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "comment": "string",
  "copy_all_source_snapshots": 1,
  "copy_latest_source_snapshot": 1,
  "create_snapshot_on_source": "",
  "identity_preservation": "string",
  "name": "Asynchronous",
  "retention": [
    {
      "count": "7",
      "creation_schedule": {
        "name": "weekly",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "label": "hourly",
      "prefix": "string"
    }
  ],
  "scope": "string",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "sync_common_snapshot_schedule": {
    "name": "weekly",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "sync_type": "string",
  "throttle": 0,
  "transfer_schedule": {
    "name": "weekly",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "type": "string",
  "uuid": "4ea7a442-86d1-11e0-ae1c-123478563412"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response codes
//start table
[cols=2*,options=header]
|===
 Error code +
//end row
//start row
|Description
//end row
//start row
|
//end row
//start row
|---------
//end row
//start row
|----------
//end row
//start row
|
//end row
//start row
|13303850  +
//end row
//start row
|Invalid input parameter
//end row
//start row
|
//end row
//start row
|13303887  +
//end row
//start row
|Failed to create SnapMirror policy. Reason: Maximum number of allowed retention rules reached
//end row
//start row
|
//end row
//start row
|13304083  +
//end row
//start row
|The specified property is not supported because all nodes in the cluster are not capable of supporting this property.
//end row
//start row
|
//end row
//start row
|13304084  +
//end row
//start row
|Properties specified are mutually exclusive. Provide only one property.
//end row
//start row
|
//end row
//start row
|13304085  +
//end row
//start row
|The specified property does not support the specified value.
//end row
|===
//end table


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#creation_schedule]
[.api-collapsible-fifth-title]
creation_schedule

Schedule used to create Snapshot copies on the destination for long term retention.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy_rule]
[.api-collapsible-fifth-title]
snapmirror_policy_rule

SnapMirror policy rule for retention.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|Number of Snapshot copies to be kept for retention.


|creation_schedule
|link:#creation_schedule[creation_schedule]
a|Schedule used to create Snapshot copies on the destination for long term retention.


|label
|string
a|Snapshot copy label


|prefix
|string
a|Specifies the prefix for the Snapshot copy name to be created as per the schedule. If no value is specified, then the label is used as the prefix.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#sync_common_snapshot_schedule]
[.api-collapsible-fifth-title]
sync_common_snapshot_schedule

Schedule used to create common Snapshot copies for synchronous relationships.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#transfer_schedule]
[.api-collapsible-fifth-title]
transfer_schedule

The schedule used to update asynchronous relationships.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Job schedule name


|uuid
|string
a|Job schedule UUID


|===


[#snapmirror_policy]
[.api-collapsible-fifth-title]
snapmirror_policy

SnapMirror policy information. SnapMirror policy can either be of type "async" or "sync".
The policy type "async" can be associated with a SnapMirror relationship that has either the FlexVol volume or FlexGroup volume or SVM as the endpoint.
The policy type "sync" along with "sync_type" as "sync" or "strict_sync" can be associated with a SnapMirror relationship that has FlexVol volume as the endpoint. The policy type "sync" can have a "sync_type" of either "sync", "strict_sync" or "automated_failover". If the "sync_type" is "sync" then a write success is returned to the client after writing the data to the source endpoint and before writing the data to the destination endpoint. If the "sync_type" is "strict_sync" then a write success is returned to the client after writing the data to the both source and destination endpoints.
If the "sync_type" is "automated_failover" then the policy can be associated with a SnapMirror relationship that has Consistency Group as the endpoint. Use the "sync" policy with "sync_type" as "automated_failover" to establish SnapMirror relationships for business continuity usecases. SnapMirror relationships with policy type as "sync" and "sync_type" as "automated_failover" can be monitored by the Mediator, if configured. In case the source Consistency Group endpoint is not reachable, the Mediator may trigger a failover to the destination Consistency Group endpoint.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|Comment associated with the policy.


|copy_all_source_snapshots
|boolean
a|Specifies that all the source Snapshot copies (including the one created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|copy_latest_source_snapshot
|boolean
a|Specifies that the latest source Snapshot copy (created by SnapMirror before the transfer begins) should be copied to the destination on a transfer. "Retention" properties cannot be specified along with this property. This is applicable only to async policies. Property can only be set to 'true'.


|create_snapshot_on_source
|boolean
a|Specifies whether a new Snapshot copy should be created on the source at the beginning of an update or resync operation. This is applicable only to async policies. Property can only be set to 'false'.


|identity_preservation
|string
a|Specifies which configuration of the source SVM is replicated to the destination SVM. This property is applicable only for SVM data protection with "async" policy type.


|name
|string
a|Name of the policy.


|network_compression_enabled
|boolean
a|Specifies whether network compression is enabled for transfers. This is applicable only to the policies of type "async".


|retention
|array[link:#snapmirror_policy_rule[snapmirror_policy_rule]]
a|Policy on Snapshot copy retention.


|scope
|string
a|Set to "svm" for policies owned by an SVM, otherwise set to "cluster".


|svm
|link:#svm[svm]
a|

|sync_common_snapshot_schedule
|link:#sync_common_snapshot_schedule[sync_common_snapshot_schedule]
a|Schedule used to create common Snapshot copies for synchronous relationships.


|sync_type
|string
a|

|throttle
|integer
a|Throttle in KB/s. Default to unlimited.


|transfer_schedule
|link:#transfer_schedule[transfer_schedule]
a|The schedule used to update asynchronous relationships.


|type
|string
a|

|uuid
|string
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
