---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-nvme-subsystems.html'
summary: 'Create an NVMe subsystem'
---

= Create an NVMe subsystem

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/nvme/subsystems`#

*Introduced In:* 9.6

Creates an NVMe subsystem.

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the NVMe subsystem.
* `name` - Name for NVMe subsystem. Once created, an NVMe subsytem cannot be renamed.
* `os_type` - Operating system of the NVMe subsystem's hosts.

== Related ONTAP commands

* `vserver nvme subsystem create`

== Learn more

* link:manage_nvme_subsystems.html[DOC /protocols/nvme/subsystems]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A configurable comment for the NVMe subsystem. Optional in POST and PATCH.


|delete_on_unmap
|boolean
a|An option that causes the subsystem to be deleted when the last subsystem map associated with it is deleted. This property defaults to _false_ when the subsystem is created.


|hosts
|array[link:#hosts[hosts]]
a|The NVMe hosts configured for access to the NVMe subsystem. Optional in POST.


|io_queue
|link:#io_queue[io_queue]
a|The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


|name
|string
a|The name of the NVMe subsystem. Once created, an NVMe subsystem cannot be renamed. Required in POST.


|os_type
|string
a|The host operating system of the NVMe subsystem's hosts. Required in POST.


|serial_number
|string
a|The serial number of the NVMe subsystem.


|subsystem_maps
|array[link:#subsystem_maps[subsystem_maps]]
a|The NVMe namespaces mapped to the NVMe subsystem.

There is an added cost to retrieving property values for `subsystem_maps`. They are not populated for either a collection GET or an instance GET unless explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|svm
|link:#svm[svm]
a|

|target_nqn
|string
a|The NVMe qualified name (NQN) used to identify the NVMe storage target.


|uuid
|string
a|The unique identifier of the NVMe subsystem.


|vendor_uuids
|array[string]
a|Vendor-specific identifiers (UUIDs) optionally assigned to an NVMe subsystem when the subsystem is created. The identifiers are used to enable vendor-specific NVMe protocol features. The identifiers are provided by a host application vendor and shared with NetApp prior to a joint product release. Creating an NVMe subsystem with an unknown or non-specific identifier will have no effect on the NVMe subsystem. Refer to the ONTAP SAN Administration Guide for a list of the supported vendor-specific identifiers. After a subsystem is created, the vendor-specific identifiers cannot be changed or removed. Optional in POST.

* Introduced in: 9.9
* readCreate: 1


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "comment": "string",
  "hosts": [
    {
      "nqn": "nqn.1992-01.example.com:string"
    }
  ],
  "io_queue": {
    "default": {
      "count": "4",
      "depth": "16"
    }
  },
  "name": "subsystem1",
  "os_type": "string",
  "serial_number": "wCVsgFMiuMhVAAAAAAAB",
  "subsystem_maps": [
    {
      "anagrpid": "00103050h",
      "namespace": {
        "name": "/vol/vol1/namespace1",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "nsid": "00000001h"
    }
  ],
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "target_nqn": "nqn.1992-01.example.com:string",
  "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
  "vendor_uuids": [
    "1447f0f4-42e5-0dfc-871a-dc9b3f92d8f8"
  ]
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records.


|records
|array[link:#nvme_subsystem[nvme_subsystem]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "records": [
    {
      "comment": "string",
      "hosts": [
        {
          "nqn": "nqn.1992-01.example.com:string"
        }
      ],
      "io_queue": {
        "default": {
          "count": "4",
          "depth": "16"
        }
      },
      "name": "subsystem1",
      "os_type": "string",
      "serial_number": "wCVsgFMiuMhVAAAAAAAB",
      "subsystem_maps": [
        {
          "anagrpid": "00103050h",
          "namespace": {
            "name": "/vol/vol1/namespace1",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "nsid": "00000001h"
        }
      ],
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "target_nqn": "nqn.1992-01.example.com:string",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412",
      "vendor_uuids": [
        "1447f0f4-42e5-0dfc-871a-dc9b3f92d8f8"
      ]
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 2621462
| The supplied SVM does not exist.

| 2621706
| The specified `svm.uuid` and `svm.name` do not refer to the same SVM.

| 2621707
| The svm.uuid or svm.name must be provided.

| 72089635
| Setting vendor-specific UUIDs on NVMe subsystems is not supported until the effective cluster version is 9.9 or later.

| 72089709
| The NVMe subsystem name contains an invalid character.

| 72089711
| An invalid vendor-specific UUID was specified.

| 72089712
| A duplicate vendor-specific UUID was specific.

| 72089713
| Too many vendor UUIDs were supplied.

| 72089771
| The NQN is invalid. A non-empty qualifier is required after the prefix. An example of a valid NQN is _nqn.1992-01.com.example:string_.

| 72089772
| The NQN is invalid. Add the prefix _'nqn'_. An example of a valid NQN is _nqn.1992-01.com.example:string_.

| 72089773
| The NQN is invalid. The date field must be formatted _yyyy-mm_. An example of a valid NQN is _nqn.1992-01.com.example:string_.

| 72090025
| The NVMe subsystem already exists for the SVM.

| 72090029
| The NVMe service does not exist.

| 72090030
| A partial success occured while adding multiple NVMe subsystem hosts to an NVMe subsystem.

| 72090035
| Passing NVMe subsystem host NQNs on NVMe subsystem POST requires an effective cluster version of 9.7 or later.

| 72090036
| The `hosts.nqn` NVMe subsystem property must contain unique values.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#hosts]
[.api-collapsible-fifth-title]
hosts

[cols=3*,options=header]
|===
|Name
|Type
|Description

|nqn
|string
a|The NVMe qualified name (NQN) used to identify the NVMe storage target.


|===


[#default]
[.api-collapsible-fifth-title]
default

The default I/O queue parameters inherited by NVMe hosts in the NVMe subsystem.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|count
|integer
a|The number of host I/O queue pairs.


|depth
|integer
a|The host I/O queue depth.


|===


[#io_queue]
[.api-collapsible-fifth-title]
io_queue

The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|default
|link:#default[default]
a|The default I/O queue parameters inherited by NVMe hosts in the NVMe subsystem.


|===


[#namespace]
[.api-collapsible-fifth-title]
namespace

An NVMe namespace mapped to the NVMe subsystem.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the NVMe namespace.


|uuid
|string
a|The unique identifier of the NVMe namespace.


|===


[#subsystem_maps]
[.api-collapsible-fifth-title]
subsystem_maps

An NVMe namespace mapped to the NVMe subsystem.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|anagrpid
|string
a|The Asymmetric Namespace Access Group ID (ANAGRPID) of the NVMe namespace.

The format for an ANAGRPIP is 8 hexadecimal digits (zero-filled) followed by a lower case "h".


|namespace
|link:#namespace[namespace]
a|An NVMe namespace mapped to the NVMe subsystem.


|nsid
|string
a|The NVMe namespace identifier. This is an identifier used by an NVMe controller to provide access to the NVMe namespace.

The format for an NVMe namespace identifier is 8 hexadecimal digits (zero-filled) followed by a lower case "h".


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#nvme_subsystem]
[.api-collapsible-fifth-title]
nvme_subsystem

An NVMe subsystem maintains configuration state and namespace access control for a set of NVMe-connected hosts.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|comment
|string
a|A configurable comment for the NVMe subsystem. Optional in POST and PATCH.


|delete_on_unmap
|boolean
a|An option that causes the subsystem to be deleted when the last subsystem map associated with it is deleted. This property defaults to _false_ when the subsystem is created.


|hosts
|array[link:#hosts[hosts]]
a|The NVMe hosts configured for access to the NVMe subsystem. Optional in POST.


|io_queue
|link:#io_queue[io_queue]
a|The properties of the submission queue used to submit I/O commands for execution by the NVMe controller.


|name
|string
a|The name of the NVMe subsystem. Once created, an NVMe subsystem cannot be renamed. Required in POST.


|os_type
|string
a|The host operating system of the NVMe subsystem's hosts. Required in POST.


|serial_number
|string
a|The serial number of the NVMe subsystem.


|subsystem_maps
|array[link:#subsystem_maps[subsystem_maps]]
a|The NVMe namespaces mapped to the NVMe subsystem.

There is an added cost to retrieving property values for `subsystem_maps`. They are not populated for either a collection GET or an instance GET unless explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|svm
|link:#svm[svm]
a|

|target_nqn
|string
a|The NVMe qualified name (NQN) used to identify the NVMe storage target.


|uuid
|string
a|The unique identifier of the NVMe subsystem.


|vendor_uuids
|array[string]
a|Vendor-specific identifiers (UUIDs) optionally assigned to an NVMe subsystem when the subsystem is created. The identifiers are used to enable vendor-specific NVMe protocol features. The identifiers are provided by a host application vendor and shared with NetApp prior to a joint product release. Creating an NVMe subsystem with an unknown or non-specific identifier will have no effect on the NVMe subsystem. Refer to the ONTAP SAN Administration Guide for a list of the supported vendor-specific identifiers. After a subsystem is created, the vendor-specific identifiers cannot be changed or removed. Optional in POST.

* Introduced in: 9.9
* readCreate: 1


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
