---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-san-lun-maps.html'
summary: 'Create a LUN map'
---

= Create a LUN map

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/san/lun-maps`#

*Introduced In:* 9.6

Creates a LUN map.

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the LUN map.
* `igroup.uuid` or `igroup.name` - Existing initiator group to map to the specified LUN.
* `lun.uuid` or `lun.name` - Existing LUN to map to the specified initiator group.

== Default property values

If not specified in POST, the following default property values are assigned.

* `logical_unit_number` - If no value is provided, ONTAP assigns the lowest available value.

== Related ONTAP commands

* `lun mapping create`

== Learn more

* link:manage_san_lun_maps.html[DOC /protocols/san/lun-maps]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|igroup
|link:#igroup[igroup]
a|The initiator group to which the LUN is mapped. Required in POST by supplying either the `igroup.uuid`, `igroup.name`, or both.


|logical_unit_number
|integer
a|The logical unit number assigned to the LUN when mapped to the specified initiator group. The number is used to identify the LUN to initiators in the initiator group when communicating through Fibre Channel Protocol or iSCSI. Optional in POST; if no value is provided, ONTAP assigns the lowest available value.

* example: 1
* Max value: 4095
* Min value: 0
* Introduced in: 9.6
* readCreate: 1


|lun
|link:#lun[lun]
a|The LUN to which the initiator group is mapped. Required in POST by supplying either the `lun.uuid`, `lun.name`, or both.


|svm
|link:#svm[svm]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "igroup": {
    "initiators": [
      "iqn.1998-01.com.corp.iscsi:name1"
    ],
    "name": "igroup1",
    "os_type": "string",
    "protocol": "string",
    "uuid": "1ad8544d-8cd1-91e0-9e1c-723478563412"
  },
  "logical_unit_number": "1",
  "lun": {
    "name": "/vol/volume1/qtree1/lun1",
    "node": {
      "name": "node1",
      "uuid": "1cf8aa42-8cd1-12e0-a11c-423468563412"
    },
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records.


|records
|array[link:#lun_map[lun_map]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "records": [
    {
      "igroup": {
        "initiators": [
          "iqn.1998-01.com.corp.iscsi:name1"
        ],
        "name": "igroup1",
        "os_type": "string",
        "protocol": "string",
        "uuid": "1ad8544d-8cd1-91e0-9e1c-723478563412"
      },
      "logical_unit_number": "1",
      "lun": {
        "name": "/vol/volume1/qtree1/lun1",
        "node": {
          "name": "node1",
          "uuid": "1cf8aa42-8cd1-12e0-a11c-423468563412"
        },
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 1254207
| The LUN is already mapped to the same initiator group.

| 2621462
| The specific SVM does not exist.

| 2621706
| Both the SVM UUID and SVM name were supplied, but don't refer to the same SVM.

| 2621707
| No SVM was specified. Either `svm.name` or `svm.uuid` must be supplied.

| 5374053
| The LUN is the destination of an ongoing restore operation and is inaccessible for I/O and management. Wait for the restore to complete and try the command again.

| 5374238
| The operation is not allowed on a LUN in a Snapshot copy.

| 5374316
| A LUN move operation is in progress on the source LUN.

| 5374329
| A LUN of class `vvol` cannot be mapped.

| 5374573
| A node has no interface configured with the iSCSI or Fibre Channel protocols for the specified SVM.

| 5374574
| Multiple nodes have no interface configured with the iSCSI or Fibre Channel protocols for the specified SVM.

| 5374581
| A node has no interface configured with the iSCSI protocol for the specified SVM.

| 5374582
| Multiple nodes have no interface configured with the iSCSI protocol for the specified SVM.

| 5374583
| A node has no interface configured with the Fibre Channel protocol for the specified SVM.

| 5374584
| Multiple nodes have no interface configured with the Fibre Channel protocol for the specified SVM.

| 5374901
| Either `lun.uuid` or `lun.name` must be provided to create a LUN map.

| 5374902
| Either `igroup.uuid` or `igroup.name` must be provided to create a LUN map.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#igroup]
[.api-collapsible-fifth-title]
igroup

The initiator group to which the LUN is mapped. Required in POST by supplying either the `igroup.uuid`, `igroup.name`, or both.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|initiators
|array[string]
a|The initiators that are members of the initiator group.


|name
|string
a|The name of the initiator group. Valid in POST.


|os_type
|string
a|The host operating system of the initiator group. All initiators in the group should be hosts of the same operating system.


|protocol
|string
a|The protocols supported by the initiator group. This restricts the type of initiators that can be added to the initiator group.


|uuid
|string
a|The unique identifier of the initiator group. Valid in POST.


|===


[#node]
[.api-collapsible-fifth-title]
node

The LUN node.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name the LUN's node.


|uuid
|string
a|The unique identifier of the LUN node.


|===


[#lun]
[.api-collapsible-fifth-title]
lun

The LUN to which the initiator group is mapped. Required in POST by supplying either the `lun.uuid`, `lun.name`, or both.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The fully qualified path name of the LUN composed of a "/vol" prefix, the volume name, the (optional) qtree name, and file name of the LUN. Valid in POST.


|node
|link:#node[node]
a|The LUN node.


|uuid
|string
a|The unique identifier of the LUN. Valid in POST.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#lun_map]
[.api-collapsible-fifth-title]
lun_map

A LUN map is an association between a LUN and an initiator group. When a LUN is mapped to an initiator group, the initiator group's initiators are granted access to the LUN. The relationship between a LUN and an initiator group is many LUNs to many initiator groups.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|igroup
|link:#igroup[igroup]
a|The initiator group to which the LUN is mapped. Required in POST by supplying either the `igroup.uuid`, `igroup.name`, or both.


|logical_unit_number
|integer
a|The logical unit number assigned to the LUN when mapped to the specified initiator group. The number is used to identify the LUN to initiators in the initiator group when communicating through Fibre Channel Protocol or iSCSI. Optional in POST; if no value is provided, ONTAP assigns the lowest available value.

* example: 1
* Max value: 4095
* Min value: 0
* Introduced in: 9.6
* readCreate: 1


|lun
|link:#lun[lun]
a|The LUN to which the initiator group is mapped. Required in POST by supplying either the `lun.uuid`, `lun.name`, or both.


|svm
|link:#svm[svm]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
