---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-storage-snaplock-event-retention-operations.html'
summary: 'Create an EBR policy'
---

= Create an EBR policy

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/storage/snaplock/event-retention/operations`#

*Introduced In:* 9.7

Creates an EBR policy.

== Required properties

* `path` - Path of the file.
* `policy.name` - Name of the EBR policy.

== Related ONTAP commands

* `snaplock event-retention apply`

== Learn more

* link:manage_event_based_retention_operations.html[DOC /storage/snaplock/event-retention/operations]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|Operation ID


|num_files_failed
|integer
a|Specifies the number of files on which the application of EBR policy failed.


|num_files_processed
|integer
a|Specifies the number of files on which EBR policy was applied successfully.


|num_files_skipped
|integer
a|Specifies the number of files on which the application of EBR policy was skipped.


|num_inodes_ignored
|integer
a|Specifies the number of inodes on which the application of EBR policy was not attempted because they were not regular files.


|path
|string
a|The path for the EBR operation. Specifies the path relative to the output volume root, of the form "/path". The path can be path to a file or a directory.


|policy
|link:#policy[policy]
a|

|state
|string
a|Specifies the operation status of an EBR operation.


|svm
|link:#svm[svm]
a|

|volume
|link:#volume[volume]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "id": "16842759",
  "num_files_failed": "0",
  "num_files_processed": "50",
  "num_files_skipped": "2",
  "num_inodes_ignored": "2",
  "path": "/dir1/file",
  "policy": {
    "name": "string",
    "retention_period": "P30M",
    "svm": {
      "name": "svm1",
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
    }
  },
  "state": "completed",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "volume": {
    "name": "volume1",
    "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|Operation ID


|num_files_failed
|integer
a|Specifies the number of files on which the application of EBR policy failed.


|num_files_processed
|integer
a|Specifies the number of files on which EBR policy was applied successfully.


|num_files_skipped
|integer
a|Specifies the number of files on which the application of EBR policy was skipped.


|num_inodes_ignored
|integer
a|Specifies the number of inodes on which the application of EBR policy was not attempted because they were not regular files.


|path
|string
a|The path for the EBR operation. Specifies the path relative to the output volume root, of the form "/path". The path can be path to a file or a directory.


|policy
|link:#policy[policy]
a|

|state
|string
a|Specifies the operation status of an EBR operation.


|svm
|link:#svm[svm]
a|

|volume
|link:#volume[volume]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "id": "16842759",
  "num_files_failed": "0",
  "num_files_processed": "50",
  "num_files_skipped": "2",
  "num_inodes_ignored": "2",
  "path": "/dir1/file",
  "policy": {
    "name": "string",
    "retention_period": "P30M",
    "svm": {
      "name": "svm1",
      "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
    }
  },
  "state": "completed",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "volume": {
    "name": "volume1",
    "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
  }
}
====

== Error

```
Status: Default, Error
```

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#policy]
[.api-collapsible-fifth-title]
policy

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|Specifies the EBR policy name


|retention_period
|string
a|Specifies the retention period of an event based retention policy. The retention period value represents a duration and must be specified in the ISO-8601 duration format. The retention period can be in years, months, days, hours or minutes. A period specified for years, months and days is represented in the ISO-8601 format as "P+++<num>+++Y", "P+++<num>+++M", "P+++<num>+++D" respectively. For example "P10Y" represents a duration of 10 years. Similarly, a duration in hours, minutes is represented by "PT+++<num>+++H", "PT+++<num>+++M" respectively. The period string must contain only a single time element i.e. either years, months, days, hours or minutes. A duration which combines different periods is not supported, example "P1Y10M" is not supported. Apart from the duration specified in the ISO-8601 format, the retention period field also accepts the strings "infinite" and "unspecified".+++</num>++++++</num>++++++</num>++++++</num>++++++</num>+++


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6


|===


[#ebr_operation]
[.api-collapsible-fifth-title]
ebr_operation

[cols=3*,options=header]
|===
|Name
|Type
|Description

|id
|integer
a|Operation ID


|num_files_failed
|integer
a|Specifies the number of files on which the application of EBR policy failed.


|num_files_processed
|integer
a|Specifies the number of files on which EBR policy was applied successfully.


|num_files_skipped
|integer
a|Specifies the number of files on which the application of EBR policy was skipped.


|num_inodes_ignored
|integer
a|Specifies the number of inodes on which the application of EBR policy was not attempted because they were not regular files.


|path
|string
a|The path for the EBR operation. Specifies the path relative to the output volume root, of the form "/path". The path can be path to a file or a directory.


|policy
|link:#policy[policy]
a|

|state
|string
a|Specifies the operation status of an EBR operation.


|svm
|link:#svm[svm]
a|

|volume
|link:#volume[volume]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
