---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-storage-file-move.html'
summary: 'Start a file move operation'
---

= Start a file move operation

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/storage/file/move`#

*Introduced In:* 9.8

Starts a file move operation. Only supported on flexible volumes.

== Required properties

* `files_to_move` - List of files with the destination they are to be moved to.

== Default property values

* `cutover_time` - _10_
* `hold_quiescence` - _false_
* `max_throughput` - _0_
* `reference_cutover_time` - _10_

== Related ONTAP commands

* `volume file move start`

== Examples

== Copying two files

The POST request is used to move file(s).

----

# The API:
/api/storage/file/move

# The call:
curl -X POST  "https://<mgmt-ip>/api/storage/file/move" -H "accept: application/hal+json" -d '{"files_to_move":[{"source":{"volume":{"name":"vol_a"},"svm":{"name":"vs0"},"path":"d1/src_f1"},"destination":{"volume":{"name":"vol_a"},"svm":{"name":"vs0"},"path":"d1/dst_f1"}}, {"source":{"volume":{"name":"vol_a"},"svm":{"name":"vs0"},"path":"d1/src_f2"},"destination":{"volume":{"name":"vol_a"},"svm":{"name":"vs0"},"path":"d1/dst_f2"}}]}'

# The response:
{
"job": {
  "uuid": "b89bc5dd-94a3-11e8-a7a3-0050568edf84",
  "_links": {
     "self": {
       "href": "/api/cluster/jobs/b89bc5dd-94a3-11e8-a7a3-0050568edf84"
     }
   }
 }
}
----


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|cutover_time
|integer
a|The maximum amount of time (in seconds) that the source can be quiesced before a destination file must be made available for read-write traffic.


|files_to_move
|array[link:#files_to_move[files_to_move]]
a|A list of source files along with the destination file they are moved to. If the terminal path component of the destination is a directory, then the source file's basename is replicated in that directory.


|max_throughput
|integer
a|The maximum amount of data (in bytes) that can be transferred per second in support of this operation.


|reference_cutover_time
|integer
a|The maximum amount of time (in seconds) that the source reference file can be quiesced before the corresponding destination file must be made available for read-write traffic.


|reference_file
|link:#reference_file[reference_file]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "cutover_time": "10",
  "files_to_move": [
    {
      "destination": {
        "path": "string",
        "svm": {
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        },
        "volume": {
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      },
      "source": {
        "path": "string",
        "svm": {
          "name": "svm1",
          "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
        },
        "volume": {
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      }
    }
  ],
  "reference_cutover_time": "10",
  "reference_file": {
    "path": "string",
    "volume": {
      "name": "volume1",
      "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
    }
  }
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 7012352
| File locations are inconsistent. All files must be on the same volume.

| 7012353
| Exceeded the file operations supported number of files.

| 7012354
| Unable to pair the number of source files to destination files.

| 7012357
| Cannot start a file operation until all cluster nodes support the file operations capability.

| 7012358
| The specified source path is invalid.

| 7012359
| The specified destination path is invalid.

| 7012360
| The SVMs are not in an intracluster peering relationship.

| 7012361
| The SVMs peering relationship does not include application "file-move".

| 7012362
| The SVMs are not yet in a peered state yet.

| 7012363
| Cannot move files. All file operations must be managed by the destination SVM's administrator.

| 7012365
| Copying a file between clusters is not supported.

| 7012367
| A reference path may only be specified if multiple source paths are specified.

| 7012368
| The reference path must have a matching source path.

| 7012371
| The reference cutover time exceeds the maximum allowable time.

| 7012374
| Source volume and destination volume have different home clusters.

| 7012376
| Operation not allowed on a volume that is part of a SnapMirror Synchronous relationship.

| 7012377
| Cannot start a file move operation on the volume because an active volume conversion is in progress.

| 13107223
| Operation not supported for FlexGroup volumes or FlexGroup constituents.

| 196608143
| Cannot start the operation. The volume is undergoing a secure purge operation.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#svm]
[.api-collapsible-fifth-title]
svm

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7


|===


[#destination]
[.api-collapsible-fifth-title]
destination

[cols=3*,options=header]
|===
|Name
|Type
|Description

|path
|string
a|Path of the file or directory.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|volume
|link:#volume[volume]
a|

|===


[#source]
[.api-collapsible-fifth-title]
source

[cols=3*,options=header]
|===
|Name
|Type
|Description

|path
|string
a|Path of the file or directory.


|svm
|link:#svm[svm]
a|SVM, applies only to SVM-scoped objects.


|volume
|link:#volume[volume]
a|

|===


[#files_to_move]
[.api-collapsible-fifth-title]
files_to_move

[cols=3*,options=header]
|===
|Name
|Type
|Description

|destination
|link:#destination[destination]
a|

|source
|link:#source[source]
a|

|===


[#volume]
[.api-collapsible-fifth-title]
volume

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the volume.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6


|===


[#reference_file]
[.api-collapsible-fifth-title]
reference_file

[cols=3*,options=header]
|===
|Name
|Type
|Description

|path
|string
a|The source reference file. If a reference file is specified, data for other files being moved will be transferred as a difference from the reference file. This can save bandwidth and destination storage if the specified source files share blocks. If provided, this input must match one of the source file paths. This input need not be provided if only one source file is specified.


|volume
|link:#volume[volume]
a|

|===


[#file_move]
[.api-collapsible-fifth-title]
file_move

File move


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cutover_time
|integer
a|The maximum amount of time (in seconds) that the source can be quiesced before a destination file must be made available for read-write traffic.


|files_to_move
|array[link:#files_to_move[files_to_move]]
a|A list of source files along with the destination file they are moved to. If the terminal path component of the destination is a directory, then the source file's basename is replicated in that directory.


|max_throughput
|integer
a|The maximum amount of data (in bytes) that can be transferred per second in support of this operation.


|reference_cutover_time
|integer
a|The maximum amount of time (in seconds) that the source reference file can be quiesced before the corresponding destination file must be made available for read-write traffic.


|reference_file
|link:#reference_file[reference_file]
a|

|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
