---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-cloud-targets.html'
summary: 'Create a cloud target'
---

= Create a cloud target

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/cloud/targets`#

*Introduced In:* 9.6

Creates a cloud target.

== Required properties

* `name` - Name for the cloud target.
* `owner` - Owner of the target: _fabricpool_, _snapmirror_.
* `provider_type` - Type of cloud provider: _AWS_S3_, _Azure_Cloud_, _SGWS_, _IBM_COS_, _AliCloud_, _GoogleCloud_, _ONTAP_S3_.
* `server` - Fully qualified domain name of the object store server. Required when `provider_type` is one of the following: _SGWS_, _IBM_COS_, _AliCloud_.
* `container` - Data bucket/container name.
* `access_key` - Access key ID if `provider_type` is not _Azure_Cloud_ and `authentication_type` is _key_.
* `secret_password` - Secret access key if `provider_type` is not _Azure_Cloud_ and `authentication_type` is _key_.
* `azure_account` - Azure account if `provider_type` is _Azure_Cloud_.
* `azure_private_key` - Azure access key if `provider_type` is _Azure_Cloud_.
* `cap_url` - Full URL of the request to a CAP server for retrieving temporary credentials if `authentication_type` is _cap_.
* `svm.name` or `svm.uuid` - Name or UUID of SVM if `owner` is _snapmirror_.
* `snapmirror_use` - Use of the cloud target if `owner` is _snapmirror_: data, metadata.

== Recommended optional properties

* `authentication_type` - Authentication used to access the target: _key_, _cap_, _ec2_iam_, _gcp_sa_, _azure_msi_.
* `ssl_enabled` - SSL/HTTPS enabled or disabled.
* `port` - Port number of the object store that ONTAP uses when establishing a connection.
* `ipspace` - IPspace to use in order to reach the cloud target.
* `use_http_proxy` - Use the HTTP proxy when connecting to the object store server.

== Default property values

* `authentication_type`
* _ec2_iam_ - if running in Cloud Volumes ONTAP in AWS
* _gcp_sa_ - if running in Cloud Volumes ONTAP in GCP
* _azure_msi_ - if running in Cloud Volumes ONTAP in Azure
* _key_  - in all other cases.
* `server`
* _s3.amazonaws.com_ - if `provider_type` is _AWS_S3_
* _blob.core.windows.net_ - if `provider_type` is _Azure_Cloud_
* _storage.googleapis.com_ - if `provider_type` is _GoogleCloud_
* `ssl_enabled` - _true_
* `port`
* _443_ if `ssl_enabled` is _true_ and `provider_type` is not _SGWS_
* _8082_ if `ssl_enabled` is _true_ and `provider_type` is _SGWS_
* _80_ if `ssl_enabled` is _false_ and `provider_type` is not _SGWS_
* _8084_ if `ssl_enabled` is _false_ and `provider_type` is _SGWS_
* `ipspace` - _Default_
* `certificate_validation_enabled` - _true_
* `ignore_warnings` - _false_
* `check_only` - _false_
* `use_http_proxy` - _false_
* `server_side_encryption`
* _none_ - if `provider_type` is _ONTAP_S3_
* _sse_s3_ - if `provider_type` is not _ONTAP_S3_
* `url_style`
* _path_style_ - if `provider_type` is neither _AWS_S3_ nor _AliCloud_
* _virtual_hosted_style_ - if `provider_type` is either _AWS_S3 or _AliCloud__

== Related ONTAP commands

* `storage aggregate object-store config create`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|ignore_warnings
|boolean
|query
|False
a|Specifies whether or not warning codes should be ignored.


|check_only
|boolean
|query
|False
a|Do not create the target configuration, only check that the POST request succeeds.


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0


|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_key
|string
a|Access key ID for AWS_S3 and other S3 compatible provider types.


|authentication_type
|string
a|Authentication used to access the target. SnapMirror does not yet support CAP. Required in POST.


|azure_account
|string
a|Azure account


|azure_private_key
|string
a|Azure access key


|cap_url
|string
a|This parameter is available only when auth-type is CAP. It specifies a full URL of the request to a CAP server for retrieving temporary credentials (access-key, secret-pasword, and session token) for accessing the object store.


|certificate_validation_enabled
|boolean
a|Is SSL/TLS certificate validation enabled? The default value is true. This can only be modified for SGWS, IBM_COS, and ONTAP_S3 provider types.

* Introduced in: 9.6


|cluster
|link:#cluster[cluster]
a|

|container
|string
a|Data bucket/container name


|ipspace
|link:#ipspace[ipspace]
a|IPspace to use in order to reach the cloud target.


|name
|string
a|Cloud target name


|owner
|string
a|Owner of the target. Allowed values are FabricPool or SnapMirror. A target can be used by only one feature.


|port
|integer
a|Port number of the object store that ONTAP uses when establishing a connection. Required in POST.

* Introduced in: 9.6


|provider_type
|string
a|Type of cloud provider. Allowed values depend on owner type. For FabricPool, AliCloud, AWS_S3, Azure_Cloud, GoggleCloud, IBM_COS, SGWS, and ONTAP_S3 are allowed. For SnapMirror, the valid values are AWS_S3 or SGWS.

* Introduced in: 9.6
* readCreate: 1


|secret_password
|string
a|Secret access key for AWS_S3 and other S3 compatible provider types.


|server
|string
a|Fully qualified domain name of the object store server. Required on POST.  For Amazon S3, server name must be an AWS regional endpoint in the format s3.amazonaws.com or s3-+++<region>+++.amazonaws.com, for example, s3-us-west-2.amazonaws.com. The region of the server and the bucket must match. For Azure, if the server is a "blob.core.windows.net" or a "blob.core.usgovcloudapi.net", then a value of azure-account followed by a period is added in front of the server.+++</region>+++


|server_side_encryption
|string
a|Encryption of data at rest by the object store server for AWS_S3 and other S3 compatible provider types. This is an advanced property. In most cases it is best not to change default value of "sse_s3" for object store servers which support SSE-S3 encryption. The encryption is in addition to any encryption done by ONTAP at a volume or at an aggregate level. Note that changing this option does not change encryption of data which already exist in the object store.

* enum: ["none", "sse_s3"]
* Introduced in: 9.7


|snapmirror_use
|string
a|Use of the cloud target by SnapMirror.


|ssl_enabled
|boolean
a|SSL/HTTPS enabled or not


|svm
|link:#svm[svm]
a|This field is only applicable when used for SnapMirror. For POST and PATCH, SVM information is required for SnapMirror targets and not allowed for FabricPool targets.


|url_style
|string
a|URL style used to access S3 bucket.


|use_http_proxy
|boolean
a|Use HTTP proxy when connecting to the object store.


|used
|integer
a|The amount of cloud space used by all the aggregates attached to the target, in bytes. This field is only populated for FabricPool targets. The value is recalculated once every 5 minutes.


|uuid
|string
a|Cloud target UUID


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "access_key": "string",
  "authentication_type": "string",
  "azure_account": "string",
  "azure_private_key": "string",
  "cap_url": "https://123.45.67.89:1234/CAP/api/v1/credentials?agency=myagency&mission=mymission&role=myrole",
  "cluster": {
    "name": "string",
    "uuid": "string"
  },
  "container": "bucket1",
  "ipspace": {
    "name": "exchange",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "name": "string",
  "owner": "string",
  "provider_type": "string",
  "secret_password": "string",
  "server": "string",
  "server_side_encryption": "string",
  "snapmirror_use": "string",
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  },
  "url_style": "string",
  "used": 0,
  "uuid": "string"
}
====

== Response

```
Status: 202, Accepted
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Error

```
Status: Default, Error
```

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#cluster]
[.api-collapsible-fifth-title]
cluster

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the cluster that owns the cloud target. For POST, this accepts the name of the peer cluster only if the cluster is in switchover state.


|uuid
|string
a|The UUID of the cluster that owns the cloud target. For POST, this accepts the UUID of the peer cluster only if the cluster is in switchover state.


|===


[#ipspace]
[.api-collapsible-fifth-title]
ipspace

IPspace to use in order to reach the cloud target.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|IPspace name


|uuid
|string
a|IPspace UUID


|===


[#svm]
[.api-collapsible-fifth-title]
svm

This field is only applicable when used for SnapMirror. For POST and PATCH, SVM information is required for SnapMirror targets and not allowed for FabricPool targets.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#cloud_target]
[.api-collapsible-fifth-title]
cloud_target

[cols=3*,options=header]
|===
|Name
|Type
|Description

|access_key
|string
a|Access key ID for AWS_S3 and other S3 compatible provider types.


|authentication_type
|string
a|Authentication used to access the target. SnapMirror does not yet support CAP. Required in POST.


|azure_account
|string
a|Azure account


|azure_private_key
|string
a|Azure access key


|cap_url
|string
a|This parameter is available only when auth-type is CAP. It specifies a full URL of the request to a CAP server for retrieving temporary credentials (access-key, secret-pasword, and session token) for accessing the object store.


|certificate_validation_enabled
|boolean
a|Is SSL/TLS certificate validation enabled? The default value is true. This can only be modified for SGWS, IBM_COS, and ONTAP_S3 provider types.

* Introduced in: 9.6


|cluster
|link:#cluster[cluster]
a|

|container
|string
a|Data bucket/container name


|ipspace
|link:#ipspace[ipspace]
a|IPspace to use in order to reach the cloud target.


|name
|string
a|Cloud target name


|owner
|string
a|Owner of the target. Allowed values are FabricPool or SnapMirror. A target can be used by only one feature.


|port
|integer
a|Port number of the object store that ONTAP uses when establishing a connection. Required in POST.

* Introduced in: 9.6


|provider_type
|string
a|Type of cloud provider. Allowed values depend on owner type. For FabricPool, AliCloud, AWS_S3, Azure_Cloud, GoggleCloud, IBM_COS, SGWS, and ONTAP_S3 are allowed. For SnapMirror, the valid values are AWS_S3 or SGWS.

* Introduced in: 9.6
* readCreate: 1


|secret_password
|string
a|Secret access key for AWS_S3 and other S3 compatible provider types.


|server
|string
a|Fully qualified domain name of the object store server. Required on POST.  For Amazon S3, server name must be an AWS regional endpoint in the format s3.amazonaws.com or s3-+++<region>+++.amazonaws.com, for example, s3-us-west-2.amazonaws.com. The region of the server and the bucket must match. For Azure, if the server is a "blob.core.windows.net" or a "blob.core.usgovcloudapi.net", then a value of azure-account followed by a period is added in front of the server.+++</region>+++


|server_side_encryption
|string
a|Encryption of data at rest by the object store server for AWS_S3 and other S3 compatible provider types. This is an advanced property. In most cases it is best not to change default value of "sse_s3" for object store servers which support SSE-S3 encryption. The encryption is in addition to any encryption done by ONTAP at a volume or at an aggregate level. Note that changing this option does not change encryption of data which already exist in the object store.

* enum: ["none", "sse_s3"]
* Introduced in: 9.7


|snapmirror_use
|string
a|Use of the cloud target by SnapMirror.


|ssl_enabled
|boolean
a|SSL/HTTPS enabled or not


|svm
|link:#svm[svm]
a|This field is only applicable when used for SnapMirror. For POST and PATCH, SVM information is required for SnapMirror targets and not allowed for FabricPool targets.


|url_style
|string
a|URL style used to access S3 bucket.


|use_http_proxy
|boolean
a|Use HTTP proxy when connecting to the object store.


|used
|integer
a|The amount of cloud space used by all the aggregates attached to the target, in bytes. This field is only populated for FabricPool targets. The value is recalculated once every 5 minutes.


|uuid
|string
a|Cloud target UUID


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
