---
sidebar: sidebar
api: true
explorer: false
permalink: 'post-protocols-nvme-subsystem-maps.html'
summary: 'Create an NVMe subsystem map'
---

= Create an NVMe subsystem map

[.api-doc-operation .api-doc-operation-post]#POST# [.api-doc-code-block]#`/protocols/nvme/subsystem-maps`#

*Introduced In:* 9.6

Creates an NVMe subsystem map.

== Required properties

* `svm.uuid` or `svm.name` - Existing SVM in which to create the NVMe subsystem map.
* `namespace.uuid` or `namespace.name` - Existing NVMe namespace to map to the specified NVme subsystem.
* `subsystem.uuid` or `subsystem.name` - Existing NVMe subsystem to map to the specified NVMe namespace.

== Related ONTAP commands

* `vserver nvme subsystem map create`

== Learn more

* link:manage_nvme_subsystem_maps.html[DOC /protocols/nvme/subsystem-maps]


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_records
|boolean
|query
|False
a|The default is false.  If set to true, the records are returned.

* Default value:

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|anagrpid
|string
a|The Asymmetric Namespace Access Group ID (ANAGRPID) of the NVMe namespace.

The format for an ANAGRPID is 8 hexadecimal digits (zero-filled) followed by a lower case "h".

There is an added cost to retrieving this property's value. It is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|namespace
|link:#namespace[namespace]
a|The NVMe namespace to which the NVMe subsystem is mapped. Required in POST by supplying either the UUID, name, or both.


|nsid
|string
a|The NVMe namespace identifier. This is an identifier used by an NVMe controller to provide access to the NVMe namespace.

The format for an NVMe namespace identifier is 8 hexadecimal digits (zero-filled) followed by a lower case "h".


|subsystem
|link:#subsystem[subsystem]
a|The NVMe subsystem to which the NVMe namespace is mapped. Required in POST by supplying either `subsystem.uuid`, `subsystem.name`  or both.


|svm
|link:#svm[svm]
a|

|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "anagrpid": "00103050h",
  "namespace": {
    "name": "/vol/vol1/namespace1",
    "node": {
      "name": "node1",
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    },
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "nsid": "00000001h",
  "subsystem": {
    "name": "string",
    "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
  },
  "svm": {
    "name": "svm1",
    "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
  }
}
====

== Response

```
Status: 201, Created
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|num_records
|integer
a|Number of records.


|records
|array[link:#nvme_subsystem_map[nvme_subsystem_map]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "records": [
    {
      "anagrpid": "00103050h",
      "namespace": {
        "name": "/vol/vol1/namespace1",
        "node": {
          "name": "node1",
          "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
        },
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "nsid": "00000001h",
      "subsystem": {
        "name": "string",
        "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
      },
      "svm": {
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      }
    }
  ]
}
====

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 72089790
| The supplied NVMe namespace is already mapped to the supplied NVMe subsystem.

| 72089793
| An NVMe namespace in a Snapshot copy cannot be mapped.

| 72089799
| The NVMe namespace is the destination of an ongoing restore operation and is inaccessible for I/O and management.

| 72089902
| A node does not have an NVMe interface configured.

| 72089903
| Multiple nodes do not have an NVMe interface configured.

| 72089904
| The aggregate must be given back to its home node prior to mapping the NVMe namespace it contains.

| 72090001
| The NVMe subsystem specified by `subsystem.uuid` was not found.

| 72090005
| The specified `namespace.uuid` and `namespace.name` refer to different NVMe namespaces.

| 72090006
| The NVMe namespace specified by `namespace.uuid` was not found.

| 72090007
| The NVMe namespace specified by `namespace.name` was not found.

| 72090020
| The specified `subsystem.uuid` and `subsystem.name` refer to different NVMe subsystems.

| 72090021
| The NVMe subsystem specified by `subsystem.name` was not found.
|===


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#node]
[.api-collapsible-fifth-title]
node

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|

|uuid
|string
a|

|===


[#namespace]
[.api-collapsible-fifth-title]
namespace

The NVMe namespace to which the NVMe subsystem is mapped. Required in POST by supplying either the UUID, name, or both.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The fully qualified path name of the NVMe namespace composed from the volume name, qtree name, and file name of the NVMe namespace. Valid in POST.


|node
|link:#node[node]
a|

|uuid
|string
a|The unique identifier of the NVMe namespace. Valid in POST.


|===


[#subsystem]
[.api-collapsible-fifth-title]
subsystem

The NVMe subsystem to which the NVMe namespace is mapped. Required in POST by supplying either `subsystem.uuid`, `subsystem.name`  or both.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the NVMe subsystem.


|uuid
|string
a|The unique identifier of the NVMe subsystem.


|===


[#svm]
[.api-collapsible-fifth-title]
svm

[cols=3*,options=header]
|===
|Name
|Type
|Description

|name
|string
a|The name of the SVM.


|uuid
|string
a|The unique identifier of the SVM.


|===


[#nvme_subsystem_map]
[.api-collapsible-fifth-title]
nvme_subsystem_map

An NVMe subsystem map is an association of an NVMe namespace with an NVMe subsystem. When an NVMe namespace is mapped to an NVMe subsystem, the NVMe subsystem's hosts are granted access to the NVMe namespace. The relationship between an NVMe subsystem and an NVMe namespace is one subsystem to many namespaces.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|anagrpid
|string
a|The Asymmetric Namespace Access Group ID (ANAGRPID) of the NVMe namespace.

The format for an ANAGRPID is 8 hexadecimal digits (zero-filled) followed by a lower case "h".

There is an added cost to retrieving this property's value. It is not populated for either a collection GET or an instance GET unless it is explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[Requesting specific fields] to learn more.


|namespace
|link:#namespace[namespace]
a|The NVMe namespace to which the NVMe subsystem is mapped. Required in POST by supplying either the UUID, name, or both.


|nsid
|string
a|The NVMe namespace identifier. This is an identifier used by an NVMe controller to provide access to the NVMe namespace.

The format for an NVMe namespace identifier is 8 hexadecimal digits (zero-filled) followed by a lower case "h".


|subsystem
|link:#subsystem[subsystem]
a|The NVMe subsystem to which the NVMe namespace is mapped. Required in POST by supplying either `subsystem.uuid`, `subsystem.name`  or both.


|svm
|link:#svm[svm]
a|

|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#error]
[.api-collapsible-fifth-title]
error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
