settings:
  name: REST API reference 
  github_edit: false
  downlevel: true
  internal:
    pdf_enabled: true
    avatars_enabled: false
    lipi_enabled: false
    api_enabled: true
    api_standardize: false
  prod:
    pdf_enabled: true
    avatars_enabled: false
    harmony_enabled: false
    lipi_enabled: false
    api_enabled: true
    api_standardize: false
  versions: 
  # This Repo
  - version-number: "9.9.1"
    url: /ontap-restapi-991
  # Additional Releases
  - version-number: "9.18.1"
    url: /ontap-restapi
  - version-number: "9.17.1"
    url: /ontap-restapi-9171
  - version-number: "9.16.1"
    url: /ontap-restapi-9161
  - version-number: "9.15.1"
    url: /ontap-restapi-9151    
  - version-number: "9.14.1"
    url: /ontap-restapi-9141
  - version-number: "9.13.1"
    url: /ontap-restapi-9131
  - version-number: "9.12.1" 
    url: /ontap-restapi-9121
  - version-number: "9.11.1"
    url: /ontap-restapi-9111
  - version-number: "9.10.1"
    url: /ontap-restapi-9101 

sidebar: 
  entries:
    - title: ONTAP 9.9.1 REST API reference  
      url: /index.html
    - section: ontap
    - title: Legal notices
      url: /legal-notices.html

product-family: 
  name: ONTAP
  repo: ontap-family
