settings:
  name: ONTAP 9.9.1 REST API reference 
  github_edit: false
  downlevel: true
  internal:
    pdf_enabled: true
    avatars_enabled: false
    lipi_enabled: false
    api_enabled: true
  prod:
    pdf_enabled: true
    avatars_enabled: false
    harmony_enabled: false
    lipi_enabled: false
    api_enabled: true
  versions: 
  # This Repo
  - version-number: "9.9.1"
    url: /ontap-restapi-991
  # Additional Releases
  - version-number: "9.15.1"
    url: /ontap-restapi
  - version-number: "9.14.1"
    url: /ontap-restapi-9141
  - version-number: "9.13.1"
    url: /ontap-restapi-9131
  - version-number: "9.12.1" 
    url: /ontap-restapi-9121
  - version-number: "9.11.1"
    url: /ontap-restapi-9111
  - version-number: "9.10.1"
    url: /ontap-restapi-9101
  - version-number: "9.8"
    url: /ontap-restapi-98
  - version-number: "9.7"
    url: /ontap-restapi-97 
  - version-number: "9.6"
    url: /ontap-restapi-96   

sidebar: 
  entries:
    - title: ONTAP 9.9.1 REST API docs 
      url: /index.html
    - section: ontap
    - title: Legal notices
      url: /legal-notices.html

product-family: 
  name: ONTAP
  repo: ontap-family
