settings:
  name: ONTAP 9.9.1 REST API Documentation 
  github_edit: false
  github_issue: false
  internal:
    pdf_enabled: true
    avatars_enabled: false
    lipi_enabled: false
    api_enabled: true
  prod:
    pdf_enabled: true
    avatars_enabled: false
    harmony_enabled: false
    lipi_enabled: false
    api_enabled: true
  versions: 
  # This Repo
  - name: ONTAP
    url: /ontap-restapi-991
    version-number: "9.9.1"
  # Additional Releases
  - name: ONTAP
    url: /ontap-restapi-9131
    version-number: "9.13.1"
  - name: ONTAP
    url: /ontap-restapi-9121
    version-number: "9.12.1"
  - name: ONTAP
    url: /ontap-restapi-9111
    version-number: "9.11.1"
  - name: ONTAP
    url: /ontap-restapi-9101
    version-number: "9.10.1"
  - name: ONTAP
    url: /ontap-restapi-98 
    version-number: "9.8"
  - name: ONTAP
    url: /ontap-restapi-97 
    version-number: "9.7"
  - name: ONTAP
    url: /ontap-restapi-96 
    version-number: "9.6"    

sidebar: 
  entries:
    - title: ONTAP 9.9.1 REST API docs 
      url: /index.html
    - section: ontap
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: REST API docs for other ONTAP releases 
      links:
      - title: ONTAP 9.13.1
        url: https://docs.netapp.com/us-en/ontap-restapi-9131/index.html
      - title: ONTAP 9.12.1
        url: https://docs.netapp.com/us-en/ontap-restapi-9121/index.html  
      - title: ONTAP 9.11.1
        url: https://docs.netapp.com/us-en/ontap-restapi-9111/index.html
      - title: ONTAP 9.10.1
        url: https://docs.netapp.com/us-en/ontap-restapi-9101/index.html
      - title: ONTAP 9.8
        url: https://docs.netapp.com/us-en/ontap-restapi-98/index.html
      - title: ONTAP 9.7
        url: https://docs.netapp.com/us-en/ontap-restapi-97/index.html
      - title: ONTAP 9.6
        url: https://docs.netapp.com/us-en/ontap-restapi-96/index.html    
    - title: More resources 
      links:
        - title: ONTAP 9 Release Notes
          url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
        - title: ONTAP CLI comparison tool 
          url: https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html#cli-comparison-tool
        - title: ONTAP 9 documentation 
          url: https://docs.netapp.com/us-en/ontap/
        - title: Accessing ONTAP commands 
          url: https://docs.netapp.com/us-en/ontap/system-admin/access-man-pages-concept.html
        - title: Automate with the REST API 
          url: https://docs.netapp.com/us-en/ontap-automation/getting_started_with_the_rest_api.html

product-family: 
  name: ONTAP
  repo: ontap-family
  sidebar_label: All ONTAP product documentation