---
sidebar: sidebar
api: true
explorer: false
permalink: 'storage_quota_endpoints.html'
summary: 'ONTAP REST API storage quota endpoints'
---

= ONTAP REST API storage quota endpoints



== Overview

Quotas provide a way to restrict or track the files and space usage by a user, group, or qtree. Quotas are enabled for a specific FlexVol or a FlexGroup volume.

Quotas can have soft or hard limits. Soft limits cause ONTAP to send a notification when specified limits are exceeded. Hard limits prevent a write operation from succeeding when specified limits are exceeded.

== Quota policy rule APIs

Quotas are defined as quota policy rules specific to FlexVol or FlexGroup volumes. Each quota rule has a type. The type can be either "user", "group", or "tree".

The following APIs can be used to perform create, retrieve, modify, and delete operations related to quota policy rules for a FlexVol or a FlexGroup volume.

&ndash; POST      /api/storage/quota/rules

&ndash; GET       /api/storage/quota/rules

&ndash; GET       /api/storage/quota/rules/\{rule-uuid}

&ndash; PATCH     /api/storage/quota/rules/\{rule-uuid}

&ndash; DELETE    /api/storage/quota/rules/\{rule-uuid}

== Enabling and disabling quotas

After the quota rules are created, the quota rules need to be enabled on each FlexVol or FlexGroup volume for soft or hard limits to take effect in the filesystem. Enabling quotas can be done on a volume-by-volume basis.

The following APIs can be used to enable and disable and obtain the quota state for a FlexVol or a FlexGroup volume.

&ndash; PATCH  /api/storage/volumes/\{volume-uuid} -d '{"quota.enabled":"true"}'

&ndash; PATCH  /api/storage/volumes/\{volume-uuid} -d '{"quota.enabled":"false"}'

&ndash; GET    /api/storage/volumes/\{volume-uuid}/?fields=quota.state

== Quota report APIs

Quota report records provide usage information for a user, group, or qtree against the quota limits configured on a FlexVol or a FlexGroup volume.
The following APIs can be used to retrieve quota reports associated with a FlexVol or a FlexGroup volume.

&ndash; GET    /api/storage/quota/reports

&ndash; GET    /api/storage/quota/reports/\{volume-uuid}/\{index}

== Quota resize

Quota resize allows you to modify the quota limits directly in the filesystem.

It is important to note that quota must be enabled on a FlexVol or a FlexGroup volume for `quota resize` to take effect.
You can perform a `quota resize` using the quota policy rule PATCH API. If the quota is disabled on the volume, the quota policy rule PATCH API modifies the rule, but this does not affect the limits in the filesystem.
The following API can be used to perform `quota resize` provided quota is enabled on the volume.

&ndash; PATCH  /api/storage/quota/rules/\{rule-uuid}
The changed limits in the filesystem can be confirmed using the quota report REST API.

&ndash; GET  /api/storage/quota/reports


