---
sidebar: sidebar
api: true
explorer: false
permalink: 'view_nfs_connected_clients.html'
summary: 'View NFS connected clients'
---

= View NFS connected clients



== Overview

ONTAP connected clients show functionality is mainly used to provide a list of currently connected NFS clients. It also provides a potential list of other NFS clients that can be connected but are currently idle.

The following are details of the fields retrieved for the Connected Clients GET API:

node.name: The node name hosting this record; basically the node hosting the "server_ip".
node.uuid: The node UUID hosting this record; basically the node hosting the "server_ip".
svm.name: The svm name to which the "server_ip" belongs to.
svm.uuid: The svm uuid to which the "server_ip" belongs to.
server_ip: All clients that are connected to this interface are displayed in rows.
client_ip: The IP address of the client that is connected to the interface.
volume.name: The name of the volume the client is accessing.
volume.uuid: The UUID of the volume the client is accessing. This field is expensive field and will be fetched in advance privilege level.
protocol: The NFS protocol version over which client is accessing the volume.
export_policy.id: The export policy ID associated with the volume.
export_policy.name: The export policy name associated with the volume.
idle_duration: The time elapsed since the last request was sent by the client for this volume.
local_request_count: A counter that tracks requests that are sent to the volume with fast-path to local node.
remote_request_count: A counter that tracks requests that are sent to the volume with slow-path to remote node.

== Example

=== Retrieves connected client information

----

# The API:
GET /protocols/nfs/connected-clients

# The call:
curl -X GET "https://<cluster-mgmt-ip>/api/protocols/nfs/connected-clients?return_timeout=15&return_records=true" -H "accept: application/json"

# The response:
{
"records": [
{
   "svm": {
     "uuid": "c642db55-b8d0-11e9-9ad1-0050568e8480",
     "name": "vs1"
   },
   "node": {
     "uuid": "cc282893-b82f-11e9-a3ad-0050568e8480",
     "name": "vsim1"
   },
   "server_ip": "10.140.72.214",
   "client_ip": "10.140.137.57",
   "volume": {
     "name": "rvol1",
     "uuid": "c6bbc6f2-b8d0-11e9-9ad1-0050568e8480"
   },
   "protocol": "nfs4"
 },
 {
   "svm": {
     "uuid": "c642db55-b8d0-11e9-9ad1-0050568e8480",
     "name": "vs1"
   },
   "node": {
     "uuid": "cc282893-b82f-11e9-a3ad-0050568e8480",
     "name": "vsim1"
   },
   "server_ip": "10.140.72.214",
   "client_ip": "10.140.137.57",
   "volume": {
     "name": "vol1",
     "uuid": "d28d1999-b8d0-11e9-9ad1-0050568e8480"
   },
   "protocol": "nfs3"
 },
 {
   "svm": {
     "uuid": "c642db55-b8d0-11e9-9ad1-0050568e8480",
     "name": "vs1"
   },
   "node": {
     "uuid": "cc282893-b82f-11e9-a3ad-0050568e8480",
     "name": "vsim1"
   },
   "server_ip": "10.140.72.214",
   "client_ip": "10.140.137.57",
   "volume": {
     "name": "vol1",
     "uuid": "d28d1999-b8d0-11e9-9ad1-0050568e8480"
   },
   "protocol": "nfs4"
 }],
 "num_records": 3
}
----


